rpma: each thread registers only its own workspace
pmem/fio pull request #112
Opened 2021-01-13 18:39 UTC by janekmi

- each thread workspace starts from offset 0 of its registration
- no need for passing from server to client assumed workspace size
- no need for allocating an excessive amount of DRAM just to make sense of the client-assumed workspace offset
- no need for registering the whole PMEM when only its part is in use via a specific registration

2021-01-13 18:47 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: 0 of 1 files reviewed, all discussions resolved

___
*[engines/librpma.c, line 38 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx24Ls71xQF2-Xj27r:-MQx24Ls71xQF2-Xj27s:b-pujrv) ([raw file](https://github.com/pmem/fio/blob/07a20bc082b8df6058548df85c2ab10e8d11c25b/engines/librpma.c#L38)):*
> ```C
> 
> struct workspace {
> 	uint32_t size;		/* size of workspace for a single connection */
> ```

The size of the workspace is now the size of the registration.
___
*[engines/librpma.c, line 97 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx296x7C_n-Trs3E79:-MQx296x7C_n-Trs3E7A:b-fes5zt) ([raw file](https://github.com/pmem/fio/blob/07a20bc082b8df6058548df85c2ab10e8d11c25b/engines/librpma.c#L97)):*
> ```C
> 
> 	/* remote workspace description */
> 	size_t ws_offset;
> ```

The workspace offset is always 0.
___
*[engines/librpma.c, line 337 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx2E-15hDF01YLPWD_:-MQx2E-15hDF01YLPWDa:b-iq18wn) ([raw file](https://github.com/pmem/fio/blob/07a20bc082b8df6058548df85c2ab10e8d11c25b/engines/librpma.c#L337)):*
> ```C
> 			cd->ws_offset + ws->size, server_mr_size);
> 		goto err_conn_delete;
> 	}
> ```

All of these are now done on the server-side. The clients just got "a file" of the specific size. TBH we could even control the execution time via the client-side `size` option. Because FIO should generate the same offsets multiple times just to force us to transfer assumed `size` bytes.
___
*[engines/librpma.c, line 347 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx2h6z2GI6zF1M-fu-:-MQx2h6z2GI6zF1M-fu0:b3dumli) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L347)):*
> ```C
> 	}
> 
> 	cd->ws_size = server_mr_size;
> ```

The size of the workspace is now the size of the memory registration.
___
*[engines/librpma.c, line 509 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx2mSwErwsHAZfV3vi:-MQx2mSwErwsHAZfV3vj:b-r2vlr4) ([raw file](https://github.com/pmem/fio/blob/07a20bc082b8df6058548df85c2ab10e8d11c25b/engines/librpma.c#L509)):*
> ```C
> 	struct client_data *cd = td->io_ops_data;
> 	size_t dst_offset = (char *)(io_u->xfer_buf) - cd->orig_buffer_aligned;
> 	size_t src_offset = cd->ws_offset + io_u->offset;
> ```

The best thing is... the workspace offset is always 0 now.
___
*[engines/librpma.c, line 528 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx2yMfENn3ZwQyt9WF:-MQx2yMfENn3ZwQyt9WG:b-qy9c6t) ([raw file](https://github.com/pmem/fio/blob/07a20bc082b8df6058548df85c2ab10e8d11c25b/engines/librpma.c#L528)):*
> ```C
> 	struct client_data *cd = td->io_ops_data;
> 	size_t src_offset = (char *)(io_u->xfer_buf) - cd->orig_buffer_aligned;
> 	size_t dst_offset = cd->ws_offset + io_u->offset;
> ```

`ws_offset == 0`
___
*[engines/librpma.c, line 549 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx30CsDjvB9AOvPt9B:-MQx30CsDjvB9AOvPt9C:b-qy9c6t) ([raw file](https://github.com/pmem/fio/blob/07a20bc082b8df6058548df85c2ab10e8d11c25b/engines/librpma.c#L549)):*
> ```C
> {
> 	struct client_data *cd = td->io_ops_data;
> 	size_t dst_offset = cd->ws_offset + first_io_u->offset;
> ```

`ws_offset == 0`
___
*[engines/librpma.c, line 984 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx36IZ9j3Ho_rnaXyd:-MQx36IZ9j3Ho_rnaXye:bri1uql) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L984)):*
> ```C
> 	int is_pmem = 0;
> 	/* XXX assuming size is page aligned */
> 	size_t ws_offset = (td->thread_number - 1) * size;
> ```

@grom72 I think we can eventually use `get_start_offset()` but I have decided it is not part of this change. Especially it will affect job files etc. etc.
___
*[engines/librpma.c, line 1018 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx3KBBCbZxSkbovXFd:-MQx3KBBCbZxSkbovXFe:b-uzylyy) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L1018)):*
> ```C
> 			filename, size_mmap, ws_offset + size);
> 		goto err_unmap;
> 	}
> ```

Now the server-side validates if it can carve out a workspace for itself from the provided PMEM file.
___
*[engines/librpma.c, line 1027 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx3XBJCrZ4ApdHQoaS:-MQx3XBJCrZ4ApdHQoaT:b-boetnh) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L1027)):*
> ```C
> err_unmap:
> 	(void) pmem_unmap(mem_ptr, size_mmap);
> 	return NULL;
> ```

Sorry, too many occurrences of the same error handling section.
___
*[engines/librpma.c, line 1066 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQx3cCI6L9h8deSejQz:-MQx3cCI6L9h8deSejR-:bwtxv7t) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L1066)):*
> ```C
> 	char *mem_ptr = NULL;
> 	size_t mr_desc_size;
> 	size_t mem_size = td->o.size;
> ```

Memory footprint reduction!


<!-- Sent from Reviewable.io -->

2021-01-14 09:03 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 983 at r1](https://reviewable.io/reviews/pmem/fio/112#-MQzveJ8A61mNKADIdck:-MQzveJ8A61mNKADIdcl:b-tnjdf3) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L983)):*
> ```
> 	int is_pmem = 0;
> 	/* XXX assuming size is page aligned */
> ```

Add an empty line in between, please.
___
*[engines/librpma.c, line 999 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-75HFErvc6JapCwXb:-MR-75HFErvc6JapCwXc:bychyzv) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L999)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> 	/* map the file */
> 	mem_ptr = pmem_map_file(filename, 0 /* len */, 0 /* flags */,
> 			0 /* mode */, &size_mmap, &is_pmem);
> 	if (mem_ptr == NULL) {
> 		log_err("fio: pmem_map_file(%s) failed\n", filename);
> 		/* pmem_map_file() sets errno on failure */
> 		td_verror(td, errno, "pmem_map_file");
> 		return NULL;
> 	}
> ```
</details>


I think we could call `pmem_map_file()` only once in init() or setup() and only pass here the pointer `mem_ptr`, could we?
___
*[engines/librpma.c, line 1018 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-5SmR0UvVRl3J9M4o:-MR-5SmS8Ht5OmAwupZp:b-qfbsk) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L1018)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 	/* check size of allocated persistent memory */
> 	if (size_mmap <= ws_offset) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu <= %zu)\n",
> 			filename, size_mmap, ws_offset);
> 		goto err_unmap;
> 	} else if (size_mmap < ws_offset + size) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
> 			filename, size_mmap, ws_offset + size);
> 		goto err_unmap;
> 	}
> ```
</details>


This is enough and does exactly the same (because the first `ws_offset` equals 0 and the second condition equals the first one in the next thread):
```
	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			filename, size_mmap, ws_offset + size);
		goto err_unmap;
	}
```


<!-- Sent from Reviewable.io -->

2021-01-14 09:21 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 999 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-75HFErvc6JapCwXb:-MR-9Lj3AH6C9Hf0d-uU:b-7kh5g2) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L999)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* map the file */
> 	mem_ptr = pmem_map_file(filename, 0 /* len */, 0 /* flags */,
> 			0 /* mode */, &size_mmap, &is_pmem);
> 	if (mem_ptr == NULL) {
> 		log_err("fio: pmem_map_file(%s) failed\n", filename);
> 		/* pmem_map_file() sets errno on failure */
> 		td_verror(td, errno, "pmem_map_file");
> 		return NULL;
> 	}
> ```

I think we could call `pmem_map_file()` only once in init() or setup() and only pass here the pointer `mem_ptr`, could we?
</blockquote></details>

`init()` and `setup()` are called for each thread separately. No gain from moving `pmem_map_file()` to any other hook.


<!-- Sent from Reviewable.io -->

2021-01-14 09:25 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 1018 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-5SmR0UvVRl3J9M4o:-MR-CR8pEv3nlIWie1vw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L1018)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* check size of allocated persistent memory */
> 	if (size_mmap <= ws_offset) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu <= %zu)\n",
> 			filename, size_mmap, ws_offset);
> 		goto err_unmap;
> 	} else if (size_mmap < ws_offset + size) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
> 			filename, size_mmap, ws_offset + size);
> 		goto err_unmap;
> 	}
> ```

This is enough and does exactly the same (because the first `ws_offset` equals 0 and the second condition equals the first one in the next thread):
```
	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			filename, size_mmap, ws_offset + size);
		goto err_unmap;
	}
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 09:25 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 999 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-75HFErvc6JapCwXb:-MR-CNK9BuYmR04YhG9x:bsq39dj) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L999)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`init()` and `setup()` are called for each thread separately. No gain from moving `pmem_map_file()` to any other hook.
</blockquote></details>

So there is no hook called only once for all threads, before all threads start? :-(


<!-- Sent from Reviewable.io -->

2021-01-14 09:26 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-14 09:27 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112#-:-MR-D86M7wNm8Y-q202H:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-14 09:30 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 999 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-75HFErvc6JapCwXb:-MR-CtAY7sw4100T1LQH:b-3eh3e5) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L999)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So there is no hook called only once for all threads, before all threads start? :-(
</blockquote></details>

FIO supports such a configuration. But we have deliberately given it up (`create_serialize=0`) because we wanted to have `open_file()` hook called after the `init()`. I think we can win using pmem2 to map only the part we are interested in.


<!-- Sent from Reviewable.io -->

2021-01-14 09:39 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-14 09:40 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[engines/librpma.c, line 999 at r1](https://reviewable.io/reviews/pmem/fio/112#-MR-75HFErvc6JapCwXb:-MR-G-_MEW0RuB_Gjf7e:b-kufkx2) ([raw file](https://github.com/pmem/fio/blob/88398f63a36697d27c5586c768de082c72e9904e/engines/librpma.c#L999)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

FIO supports such a configuration. But we have deliberately given it up (`create_serialize=0`) because we wanted to have `open_file()` hook called after the `init()`. I think we can win using pmem2 to map only the part we are interested in.
</blockquote></details>

I see, thanks.


<!-- Sent from Reviewable.io -->

2021-01-14 10:16 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/112#-:-MR-OPMaAJCQFHjSc00t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-14 10:20 UTC, merged