rpma: add FIO_DISKLESSIO flag for server ioengine
pmem/fio pull request #257
Opened 2021-07-20 09:20 UTC by yangx-jy

When we use 64 threads to run server ioengine with DRAM, setup_files() will create the unused 'malloc' file by some operations (e.g. fallocate, ftruncate).  This behavior makes server spend more time to prepare the connection so that client always triggers the "The maximum number of retries exceeded." error.  See the detailed output:
```
...
Thread [7]: The maximum number of retries exceeded. Closing. IOPS][eta 01m:00s]
Thread [7]: Connected after retry #10
Thread [29]: Connected after retry #9
Thread [2]: The maximum number of retries exceeded. Closing.
Thread [9]: The maximum number of retries exceeded. Closing.
Thread [2]: Connected after retry #10
Thread [9]: Connected after retry #10
Thread [15]: The maximum number of retries exceeded. Closing.
Thread [15]: Connected after retry #10
Thread [19]: The maximum number of retries exceeded. Closing.
Thread [19]: Connected after retry #10
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15279, err=-1/
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15284, err=-1/
fio: pid=15292, err=-1/
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15286, err=-1/
fio: pid=15296, err=-1/
Thread [30]: The maximum number of retries exceeded. Closing.
Thread [30]: Connected after retry #10
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15307, err=-1/
...
```

disallow setup_files() to create the unused 'malloc' file by adding
FIO_DISKLESSIO flag.

2021-07-20 09:34 UTC, yangx-jy commented
By the way, I tried to avoid the issue by increasing the number of connection retries before but the change impacted the bandwith of test (i.e. the bandwidth of test exceeds the max physical bandwidth (200Gb/s) of Mellanox), because 64 threads cannot do the read/write operations in parallel if each thread establishes connection at a long time interval.

2021-07-20 12:29 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/257#-:-Mf2t4rl07_i2nYmhGTB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-21 06:17 UTC, yangx-jy reviewed
@ldorau 

Ah, fsdax mode needs to allocate file by `fallocate()` so this change will break fsdax mode.
Perhaps, we need to do `fallocate()` for fsdax mode in librpma_fio_allocate_pmem().

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/257#-:-Mf6esLuC9RLf4pnJZe2:b-d20hkh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-22 07:05 UTC, yangx-jy reviewed
I try to fix the issue by adding create_on_open=1 for the DRAM mode instead.
See https://github.com/pmem/rpma/pull/1157

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/257#-:-MfC0_gG8WPjcEBO7WsB:brwifqr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-22 09:21 UTC, ldorau requested changes
Yes, that's right, https://github.com/pmem/rpma/pull/1157 seems to be the right fix, so you can close this PR.

<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/257#-:-MfCV2uT5jPogsJ0YD5x:bxn8zg9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-22 10:01 UTC, yangx-jy commented
Sure, I closed it.





<!-- Sent from Reviewable.io -->

2021-07-22 10:01 UTC, closed without merging