engines: libpmem2 engine
pmem/fio pull request #267
Opened 2022-02-09 14:07 UTC by blazej-smorawski

Fio engine based on libpmem2 for data writing.

2022-02-10 10:56 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-10 12:16 UTC, ldorau commented
Changed the base branch from master to pmdk (because the master branch always follows the axboe's master)

2022-02-10 12:17 UTC, ldorau commented
@blazej-smorawski I changed the base branch from master to pmdk (because the master branch always follows the axboe's master)

2022-02-11 11:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvccNkQA48pfu1KTQVl:-MvccNkQA48pfu1KTQVm:b-z35zuv) (no related file):*
@blazej-smorawski Don't you need to install the ` libpmem2-dev` package in the CI ?

---


<!-- Sent from Reviewable.io -->

2022-02-11 11:56 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvccNkQA48pfu1KTQVl:-Mvccw6_5V6GOjMHHM-E:b-nk472k) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@blazej-smorawski Don't you need to install the ` libpmem2-dev` package in the CI ?
</blockquote></details>

... or PMDK from sources to have libpmem2 installed in the OS?

---


<!-- Sent from Reviewable.io -->

2022-02-14 06:51 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-14 08:04 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

___
*[ci/travis-install-pmdk.sh, line 4 at r4](https://reviewable.io/reviews/pmem/fio/267#-MvrFZ65COQEOnmXGcTC:-MvrFZ65COQEOnmXGcTD:b-93wfuk) ([raw file](https://github.com/pmem/fio/blob/df597be63e26ef59c1538b3ce2026c83684ff7fb/ci/travis-install-pmdk.sh#L4)):*
> ```Shell
> 
> # pmdk v1.9.1 release
> PMDK_VERSION=1.9.1
> ```

This file should be renamed to actions-* because it is used by GitHub Actions, not by Travis.



_Code quote:_
```Shell
# pmdk v1.9.1 release
PMDK_VERSION=1.9.1
```


<!-- Sent from Reviewable.io -->

2022-02-14 08:09 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

___
*[ci/travis-install-pmdk.sh, line 4 at r4](https://reviewable.io/reviews/pmem/fio/267#-MvrFZ65COQEOnmXGcTC:-MvrGJ85-LeILVS9ysR0:b-e46970) ([raw file](https://github.com/pmem/fio/blob/df597be63e26ef59c1538b3ce2026c83684ff7fb/ci/travis-install-pmdk.sh#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This file should be renamed to actions-* because it is used by GitHub Actions, not by Travis.
</blockquote></details>

Sure, I'll make my own script for the GitHub Actions and by the way - sorry if you received the spam from failed builds, but I've run into some issues with linking these libs.


<!-- Sent from Reviewable.io -->

2022-02-14 08:39 UTC, ldorau reviewed
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @ldorau)

___
*[ci/travis-install-pmdk.sh, line 4 at r4](https://reviewable.io/reviews/pmem/fio/267#-MvrFZ65COQEOnmXGcTC:-MvrN6M08KVc5Q2NKr47:bryhk7k) ([raw file](https://github.com/pmem/fio/blob/df597be63e26ef59c1538b3ce2026c83684ff7fb/ci/travis-install-pmdk.sh#L4)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Sure, I'll make my own script for the GitHub Actions and by the way - sorry if you received the spam from failed builds, but I've run into some issues with linking these libs.
</blockquote></details>

It seems Travis is not used any more, so you can just rename this one.


<!-- Sent from Reviewable.io -->

2022-02-14 09:04 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @ldorau)

___
*[ci/travis-install-pmdk.sh, line 4 at r4](https://reviewable.io/reviews/pmem/fio/267#-MvrFZ65COQEOnmXGcTC:-MvrTM63EaXxgtg09Iw9:b-9fe97h) ([raw file](https://github.com/pmem/fio/blob/df597be63e26ef59c1538b3ce2026c83684ff7fb/ci/travis-install-pmdk.sh#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems Travis is not used any more, so you can just rename this one.
</blockquote></details>

Done, removed both unused Travis scripts.


<!-- Sent from Reviewable.io -->

2022-02-14 09:20 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-17 08:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvrXGXhDYpN9fvgtb_i:-Mw5n2shD-nesrNB4MRi:bcokty6) (no related file):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I saw that, but I do not know if it is related to the code I wrote. The error says 
`./os/os-linux.h:119:19: error: static declaration of 'gettid' follows non-static declaration
static inline int gettid(void)`. Have you got any ideas on how to fix that?
</blockquote></details>

I do not know yet. I had no time to dig into it so far.
I can update the pmdk branch to the current master and you can rebase. Maybe it helps? ;-) We can try.

---


<!-- Sent from Reviewable.io -->

2022-02-17 09:15 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvrXGXhDYpN9fvgtb_i:-Mw5wOJ41Qy43vUyLehZ:b-jqusrf) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not know yet. I had no time to dig into it so far.
I can update the pmdk branch to the current master and you can rebase. Maybe it helps? ;-) We can try.
</blockquote></details>

Sure, then I'll also check how the fuzzers work without any of my changes.

---


<!-- Sent from Reviewable.io -->

2022-02-17 12:14 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvrXGXhDYpN9fvgtb_i:-Mw6aSQMEF1OpfHZPpTn:b1dnkza) (no related file):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Sure, then I'll also check how the fuzzers work without any of my changes.
</blockquote></details>

I have updated the pmdk branch. Please update your repo and rebase on the current pmdk branch.

---
___
*[ci/actions-install.sh, line 71 at r7](https://reviewable.io/reviews/pmem/fio/267#-Mw6_eYlDNZaHE48GBcT:-Mw6_eYlDNZaHE48GBcU:b6d4uem) ([raw file](https://github.com/pmem/fio/blob/ffa77705e750e1c6c96f28a98165586b45d841c5/ci/actions-install.sh#L71)):*
> ```Shell
>        echo "Installing PMDK from sources"
>        "${SCRIPT_DIR}/actions-install-pmdk.sh"
>        sudo ldconfig -v
> ```

```
# PMDK libraries are installed in /usr/lib64/
sudo ldconfig -v /usr/lib64/
```



_Code quote:_
```Shell
sudo ldconfig -v
```


<!-- Sent from Reviewable.io -->

2022-02-18 07:06 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvrXGXhDYpN9fvgtb_i:-MwAdVqh0cI_WuGCk7--:bdt5385) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have updated the pmdk branch. Please update your repo and rebase on the current pmdk branch.
</blockquote></details>

I rebased onto updated pmdk branch, got same errors, then I pushed an empty branch without any changes and also got the errors, so I think it's not on my side.

---


<!-- Sent from Reviewable.io -->

2022-02-18 07:20 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[ci/actions-install.sh, line 71 at r7](https://reviewable.io/reviews/pmem/fio/267#-Mw6_eYlDNZaHE48GBcT:-MwAgp4sCRcwpBPQCF7l:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ffa77705e750e1c6c96f28a98165586b45d841c5/ci/actions-install.sh#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
# PMDK libraries are installed in /usr/lib64/
sudo ldconfig -v /usr/lib64/
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-18 09:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvrXGXhDYpN9fvgtb_i:-MwB4G74-tVuSb_h6f6u:b-hxto5c) (no related file):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I rebased onto updated pmdk branch, got same errors, then I pushed an empty branch without any changes and also got the errors, so I think it's not on my side.
</blockquote></details>

No, without your changes all CI builds pass:
https://github.com/pmem/fio/pull/274

so it probably is on your side.

---


<!-- Sent from Reviewable.io -->

2022-02-18 09:12 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-18 09:14 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-18 11:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 1 of 11 files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MvrXGXhDYpN9fvgtb_i:-MwBZY0N51X62EH9oCxY:b-y6w145) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, without your changes all CI builds pass:
https://github.com/pmem/fio/pull/274

so it probably is on your side.
</blockquote></details>

CIFuzz build temporarily removed in https://github.com/pmem/fio/pull/276

---


<!-- Sent from Reviewable.io -->

2022-02-18 11:26 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MwB_8D50RS8glsqmZvW:-MwB_8D50RS8glsqmZvX:bckpjvo) (no related file):*
Revert and rebase the original PR, please

---


<!-- Sent from Reviewable.io -->

2022-02-18 11:35 UTC, ldorau requested changes
> Reviewed 3 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

___
*[ci/actions-install.sh, line 51 at r13](https://reviewable.io/reviews/pmem/fio/267#-MwBbBksBq-HYmdCulij:-MwBbBksBq-HYmdCulik:b-i98p9) ([raw file](https://github.com/pmem/fio/blob/a9902598d2614cbc8b089232aaf1edf62f564ad7/ci/actions-install.sh#L51)):*
> ```Shell
>                 libnbd-dev
>                 libpmem-dev
>                 libpmemblk-dev
> ```

They should be removed now



_Code quote:_
```Shell
                libpmem-dev
                libpmemblk-dev
```


<!-- Sent from Reviewable.io -->

2022-02-18 11:43 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[ci/actions-install.sh, line 51 at r13](https://reviewable.io/reviews/pmem/fio/267#-MwBbBksBq-HYmdCulij:-MwBd3Wz3lem7_5Epkgc:b-2v9gy9) ([raw file](https://github.com/pmem/fio/blob/a9902598d2614cbc8b089232aaf1edf62f564ad7/ci/actions-install.sh#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

They should be removed now
</blockquote></details>

Done. Messed this up while reverting changes.


<!-- Sent from Reviewable.io -->

2022-02-18 11:50 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r11, 1 of 10 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-21 07:45 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[configure, line 2206 at r14](https://reviewable.io/reviews/pmem/fio/267#-MwBi5hg33TPxtkQdXsu:-MwQE5gq-AEn_2zqkCpR:blnc27o) ([raw file](https://github.com/pmem/fio/blob/3a06b946c8d1d1c35abc69c6dc798abe6c58a446/configure#L2206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Is libpmem required to have the pmem2 engine ???
</blockquote></details>

It's not I think, but I wanted to have it both under the condition `$disable_pmem`. Moved the `if` out, so it's possible to have libpmem2 without libpmem.
___
*[configure, line 2212 at r14](https://reviewable.io/reviews/pmem/fio/267#-MwBiQD7EZQR4mf4SgiN:-MwQDdReBPd4KaQFO8uA:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3a06b946c8d1d1c35abc69c6dc798abe6c58a446/configure#L2212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wrong indentation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 08:21 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

___
*[configure, line 2206 at r14](https://reviewable.io/reviews/pmem/fio/267#-MwBi5hg33TPxtkQdXsu:-MwQMAvC2XY1i5HmYu19:b-c6ldsb) ([raw file](https://github.com/pmem/fio/blob/3a06b946c8d1d1c35abc69c6dc798abe6c58a446/configure#L2206)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

It's not I think, but I wanted to have it both under the condition `$disable_pmem`. Moved the `if` out, so it's possible to have libpmem2 without libpmem.
</blockquote></details>

Exactly, it is not.

The `else pmemX=no` branches are redundant - the default value `"no"` should be set above instead.
___
*[configure, line 164 at r15](https://reviewable.io/reviews/pmem/fio/267#-MwQM1qA8VEAeq7SO2dN:-MwQM1qA8VEAeq7SO2dO:b-c0ezyx) ([raw file](https://github.com/pmem/fio/blob/716bfea7b5b530b99ff9926c6f5cb446eb9f9e0c/configure#L164)):*
> ```
> pmemblk="no"
> devdax="no"
> pmem="no"
> ```

```
pmem="no"
pmem2="no"
```



_Code quote:_
```
pmem="no"
```


<!-- Sent from Reviewable.io -->

2022-02-21 08:23 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @blazej-smorawski and @ldorau)

___
*[configure, line 2205 at r15](https://reviewable.io/reviews/pmem/fio/267#-MwQNAqOCPRvO4sG00A6:-MwQNAqOCPRvO4sG00A7:b-fhlo7o) ([raw file](https://github.com/pmem/fio/blob/716bfea7b5b530b99ff9926c6f5cb446eb9f9e0c/configure#L2205)):*
> ```
> print_config "libpmemblk" "$libpmemblk"
> 
> # Choose libpmem-based ioengines
> ```

outdated comment



_Code quote:_
```
# Choose libpmem-based ioengines
```


<!-- Sent from Reviewable.io -->

2022-02-21 09:55 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[configure, line 2206 at r14](https://reviewable.io/reviews/pmem/fio/267#-MwBi5hg33TPxtkQdXsu:-MwQhDf588HUVHey0YDZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3a06b946c8d1d1c35abc69c6dc798abe6c58a446/configure#L2206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Exactly, it is not.

The `else pmemX=no` branches are redundant - the default value `"no"` should be set above instead.
</blockquote></details>

Done.
___
*[configure, line 164 at r15](https://reviewable.io/reviews/pmem/fio/267#-MwQM1qA8VEAeq7SO2dN:-MwQhBadCAf52f85Mxgw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/716bfea7b5b530b99ff9926c6f5cb446eb9f9e0c/configure#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
pmem="no"
pmem2="no"
```
</blockquote></details>

Done.
___
*[configure, line 2205 at r15](https://reviewable.io/reviews/pmem/fio/267#-MwQNAqOCPRvO4sG00A6:-MwQhCJf8X8bKZbuS2jj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/716bfea7b5b530b99ff9926c6f5cb446eb9f9e0c/configure#L2205)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

outdated comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 09:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MxJDABUC40xCBjTwLYY:-MxJDABUC40xCBjTwLYZ:b-6pbo13) (no related file):*
@blazej-smorawski This PR is waiting for review of other folks ;-)

---


<!-- Sent from Reviewable.io -->

2022-03-07 15:07 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r6, 6 of 10 files at r13, 1 of 1 files at r14, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: all files reviewed, 12 unresolved discussions (waiting on @blazej-smorawski)

*[a discussion](https://reviewable.io/reviews/pmem/fio/267#-MxZutid-knJuAYmENVw:-MxZutid-knJuAYmENVx:bh6rnqc) (no related file):*
did you run this with valgrind/pmemcheck?

---
___
*[configure, line 3092 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZXLl75HwsTFLn9UB_:-MxZXLl75HwsTFLn9UBa:b-jbo2i5) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/configure#L3092)):*
> ```
> fi
> if test "$pmem2" = "yes" ; then
>   output_sym "CONFIG_LIBPMEM2"
> ```

quick grep told me that `CONFIG_LIBPMEM` is also defined in `config-host.h`
___
*[engines/libpmem2.c, line 22 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZbQeH1xqaCr3GL3Z2:-MxZbQeH1xqaCr3GL3Z3:b-wnvnxl) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L22)):*
> ```C
>  *
>  * IO engine that uses libpmem2 to write data (and memcpy to read)
>  *
> ```

you could write (similarily to libpmem engine) it requires PMDK/libpmem2 library (in version >= ...) - here or on top of the file
___
*[engines/libpmem2.c, line 31 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdeT43rAF35WWO_x9:-MxZdeT43rAF35WWO_xA:b-m4gg48) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L31)):*
> ```C
>  *   sync=1
>  *   directory=/mnt/pmem0/
>  *   bs=4k
> ```

is blocksize still relevant? its optimal value depends on granularity, I guess
___
*[engines/libpmem2.c, line 39 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdAzB3HLl0uou8RPU:-MxZdAzC2F9Q62m-lfXk:ba1v99d) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L39)):*
> ```C
>  *   after n write operations.
>  *
>  *   direct=1 means PMEM_F_MEM_NONTEMPORAL flag is set in memcpy.
> ```

`PMEM2_F_MEM_NONTEMPORAL`
___
*[engines/libpmem2.c, line 39 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdOkE7nqgCsSzbG3N:-MxZdOkF00cNMjURjEMB:b-pu2ory) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L39)):*
> ```C
>  *   after n write operations.
>  *
>  *   direct=1 means PMEM_F_MEM_NONTEMPORAL flag is set in memcpy.
> ```

I think you can be more precise: `memcpy.` -> `pmem2_memcpy_fn call.`
___
*[engines/libpmem2.c, line 72 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZbLfh243F-mX5AO9T:-MxZbLfh243F-mX5AO9U:bjfle7g) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L72)):*
> ```C
> 	    (o->fsync_blocks || o->fdatasync_blocks)) {
> 		log_err("libpmem2: mmap options dictate a minimum block size of "
> 				"%llu bytes\n",	(unsigned long long) page_size);
> ```

random 'tab' in the middle of the line
___
*[engines/libpmem2.c, line 72 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZrRCZ3HgO9F59egr8:-MxZrRCZ3HgO9F59egr9:b5wasie) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L72)):*
> ```C
> 	    (o->fsync_blocks || o->fdatasync_blocks)) {
> 		log_err("libpmem2: mmap options dictate a minimum block size of "
> 				"%llu bytes\n",	(unsigned long long) page_size);
> ```

hmm... depending on the hardware some smaller blocksizes can be acceptable...?
___
*[engines/libpmem2.c, line 124 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZqIzq3vKsyoqmyDY7:-MxZqIzq3vKsyoqmyDY8:bzhiyi) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L124)):*
> ```C
> 		flags = PMEM2_PROT_WRITE;
> 
> 		if (td->o.verify != VERIFY_NONE)
> ```

additional, redundant 'tab' here (and the line below)
___
*[engines/libpmem2.c, line 248 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZsg-11Fnfosud5EUT:-MxZsg-11Fnfosud5EUU:b-ryjupr) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L248)):*
> ```C
> 		 * Only for sequential write
> 		 */
> 		fdd->persist(fdd->libpmem2_ptr + f->first_write,f->last_write - f->first_write);
> ```

this line will be executed also for SYNC command - will it be able to read anything useful from `first/last_write`...?


<!-- Sent from Reviewable.io -->

2022-03-09 07:54 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 10 of 11 files reviewed, 12 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lukaszstolarczuk)

___
*[configure, line 3092 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZXLl75HwsTFLn9UB_:-MxhXfOB0vt18Ga2WazX:bajkwok) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/configure#L3092)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

quick grep told me that `CONFIG_LIBPMEM` is also defined in `config-host.h`
</blockquote></details>

I'm not sure if I understand everything correctly but I think that the defines in `config-host.h` appear there, after using `configure`, so the `CONFIG_LIBPMEM2` will appear there too if the machine supports it.
___
*[engines/libpmem2.c, line 22 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZbQeH1xqaCr3GL3Z2:-MxhZSsi0FgIkcC8R7Zn:bgtu0hm) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could write (similarily to libpmem engine) it requires PMDK/libpmem2 library (in version >= ...) - here or on top of the file
</blockquote></details>

Libpmem2 was introduced in PMDK 1.10, so I added the requirement of PMDK 1.10.
___
*[engines/libpmem2.c, line 31 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdeT43rAF35WWO_x9:-Mxh_0p4BIKO1V7q6hWe:b-ny4efu) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is blocksize still relevant? its optimal value depends on granularity, I guess
</blockquote></details>

Sure, but I think that it's useful for benchmarking purposes to check how different sizes of memcpy perform, which is determined by the blocksize, so we can see how it performs with 2MiB memcpy or some other kinds. It was useful for comparing libpmem2 with asynchronous pmem write using miniasync because, in the case of multithreaded write, only big blocksizes make sense.
___
*[engines/libpmem2.c, line 34 at r17](https://reviewable.io/reviews/pmem/fio/267#-Mx4DKTV7Gc3yG6bxwzs:-Mxh_uiCC_FQmnqhCLjx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L34)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

Otherwise `it` is not
</blockquote></details>

Done.
___
*[engines/libpmem2.c, line 39 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdAzB3HLl0uou8RPU:-Mxha2Nq-2wLTu01funj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`PMEM2_F_MEM_NONTEMPORAL`
</blockquote></details>

Done.
___
*[engines/libpmem2.c, line 39 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdOkE7nqgCsSzbG3N:-Mxha2hxDYJ33uBX2eP2:bb74ce2) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you can be more precise: `memcpy.` -> `pmem2_memcpy_fn call.`
</blockquote></details>

Sure
___
*[engines/libpmem2.c, line 72 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZbLfh243F-mX5AO9T:-Mxhaiqd1M7qfe9GqAlg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

random 'tab' in the middle of the line
</blockquote></details>

Done.
___
*[engines/libpmem2.c, line 124 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZqIzq3vKsyoqmyDY7:-MxhbWFL1RVt_9yAx3BY:bvov65y) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L124)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

additional, redundant 'tab' here (and the line below)
</blockquote></details>

Isn't it still in the scope of the `else if` few lines above? So, it's at the same indentation as `flags = ...`.


<!-- Sent from Reviewable.io -->

2022-03-09 08:13 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lukaszstolarczuk)

___
*[configure, line 3092 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZXLl75HwsTFLn9UB_:-MxhhoCKDCaRNmanQpBJ:b7txw7e) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/configure#L3092)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

I'm not sure if I understand everything correctly but I think that the defines in `config-host.h` appear there, after using `configure`, so the `CONFIG_LIBPMEM2` will appear there too if the machine supports it.
</blockquote></details>

hmm ok, I didn't run your code, so it'd be best if you check if it appears in your `config-host.h` - if yes, then mystery solved :wink: 
___
*[engines/libpmem2.c, line 31 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdeT43rAF35WWO_x9:-MxhizAk3SGzjMHrHOAT:bid70hh) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L31)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Sure, but I think that it's useful for benchmarking purposes to check how different sizes of memcpy perform, which is determined by the blocksize, so we can see how it performs with 2MiB memcpy or some other kinds. It was useful for comparing libpmem2 with asynchronous pmem write using miniasync because, in the case of multithreaded write, only big blocksizes make sense.
</blockquote></details>

hmm, yeah, I know, but I always looked at the `Other relevant settings` section as "something you'd rather have to set in your benchmark, for the measurements to make sense" - just saying... :wink: 
___
*[engines/libpmem2.c, line 124 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZqIzq3vKsyoqmyDY7:-MxhiZSv61AmUopogbvm:b-z1cvhv) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L124)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Isn't it still in the scope of the `else if` few lines above? So, it's at the same indentation as `flags = ...`.
</blockquote></details>

hah, of course, you got me :smile: 


<!-- Sent from Reviewable.io -->

2022-03-09 08:36 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-03-09 15:37 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lukaszstolarczuk)

___
*[configure, line 3092 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZXLl75HwsTFLn9UB_:-MxjItqI4Fphd8dJuEeG:bxhgohj) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/configure#L3092)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm ok, I didn't run your code, so it'd be best if you check if it appears in your `config-host.h` - if yes, then mystery solved :wink: 
</blockquote></details>

It does :D, if it wouldn't appear there, I would not be able to use the engine
___
*[engines/libpmem2.c, line 31 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdeT43rAF35WWO_x9:-MxjJHRO3UOXPlwoZjJ5:b-gzgty) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm, yeah, I know, but I always looked at the `Other relevant settings` section as "something you'd rather have to set in your benchmark, for the measurements to make sense" - just saying... :wink: 
</blockquote></details>

Now, I understand what you mean :), I'll remove that in case somebody thinks that he has to use 4kiB blocksize
___
*[engines/libpmem2.c, line 72 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZrRCZ3HgO9F59egr8:-MxjJh0LDijhSWa01wTN:bpp6wr4) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... depending on the hardware some smaller blocksizes can be acceptable...?
</blockquote></details>

I copied it from the libpmem engine I think. Tomorrow I'll have a closer look at that.
___
*[engines/libpmem2.c, line 248 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZsg-11Fnfosud5EUT:-MxjJzpVE3C4mQz8O2Qo:bgdmyaj) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L248)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this line will be executed also for SYNC command - will it be able to read anything useful from `first/last_write`...?
</blockquote></details>

I'll check if it works properly with just sync.


<!-- Sent from Reviewable.io -->

2022-03-10 18:07 UTC, blazej-smorawski reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/267)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lukaszstolarczuk)

___
*[engines/libpmem2.c, line 31 at r17](https://reviewable.io/reviews/pmem/fio/267#-MxZdeT43rAF35WWO_x9:-Mxp-qj8CnflqgKzqxZf:b-wai21a) ([raw file](https://github.com/pmem/fio/blob/5bacf0d5564511538e6767e3428092d9c53ef19d/engines/libpmem2.c#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you have some thoughts about these values you can always explain them in the comment below (e.g. like for sync=1 or direct=1) :wink:
</blockquote></details>

Yea, I'll do it like that


<!-- Sent from Reviewable.io -->

2022-04-06 06:29 UTC, blazej-smorawski commented
Hi, I decided to close the pull request, because I have done a lot of changes to the engine in order to support libpmem2 asynchronous operations and DSA based movers. As soon as the new engine is done, I'll create a new pull request.

2022-04-06 06:29 UTC, closed without merging