engines: librpma_fio -  libpmem to libpmem2
pmem/fio pull request #269
Opened 2022-02-13 23:15 UTC by haichangsi

2022-02-13 23:21 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[engines/librpma_fio.c, line 208 at r1](https://reviewable.io/reviews/pmem/fio/269#-MvpNB6zCeSoJqa28ziB:-MvpNB6zCeSoJqa28ziC:b-dhqgut) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.c#L208)):*
> ```C
> }
> 
> void librpma_fio_free(struct librpma_fio_mem *mem)
> ```

because of this function I decided to temporarily add new libpmem2 structures  to librpma_fio_mem structure, I am not sure which way to choose (new struct or modify the existing one everywhere)


<!-- Sent from Reviewable.io -->

2022-02-13 23:25 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 2 files reviewed, 2 unresolved discussions

___
*[engines/librpma_fio.h, line 72 at r1](https://reviewable.io/reviews/pmem/fio/269#-MvpOX5V6aftI7Uz6Yl9:-MvpOX5W0h4Phr3bnw5L:b-rwtyg9) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.h#L72)):*
> ```objc
> struct librpma_fio_mem {
> 	/* memory buffer */
> 	char *mem_ptr;
> ```

There is no need to keep mem_ptr and size_mmap beacuse of possibility of getting these informations from pmem2_map, I kept it temporarily to ask about an opinion 


<!-- Sent from Reviewable.io -->

2022-02-14 06:54 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_fio.c, line 162 at r1](https://reviewable.io/reviews/pmem/fio/269#-Mvr-d1J-dH9w3gI2m-o:-Mvr-d1K1q_kV7qVfoTD:b-ilg49f) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.c#L162)):*
> ```C
> 
> 	err = pmem2_map_new(&map, cfg, src);
> 	if (map == NULL)) {
> ```

`(map == NULL)`



_Code quote:_
```C
(map == NULL))
```


<!-- Sent from Reviewable.io -->

2022-02-14 13:14 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 162 at r1](https://reviewable.io/reviews/pmem/fio/269#-Mvr-d1J-dH9w3gI2m-o:-MvsMh1P6c1yMy4FqQ5k:b-896fix) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`(map == NULL)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 14:40 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvsepuM9etL92OxsjgU):*
rpma: replace libpmem with libpmem2

Ref: pmem/rpma#992



_Code quote:_
```
engines: librpma_fio -  libpmem to libpmem2
```


<!-- Sent from Reviewable.io -->

2022-02-14 16:04 UTC, lplewa requested changes

2022-02-14 16:04 UTC, lplewa commented on engines/librpma_fio.c
> +	close(fd);
dead code

2022-02-14 16:04 UTC, lplewa commented on engines/librpma_fio.c
> +		log_err("pmem2_config_new");
please add error handling

2022-02-14 16:04 UTC, lplewa commented on engines/librpma_fio.c
> +	if (map == NULL) {
check error code, instead of using variable

2022-02-14 16:04 UTC, lplewa commented on engines/librpma_fio.c
> +	if (err == PMEM2_E_GRANULARITY_NOT_SUPPORTED) {
dead code. please handle this check like in rpma example

2022-02-16 07:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvsepuM9etL92OxsjgU):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma: replace libpmem with libpmem2

Ref: pmem/rpma#992
</blockquote></details>

```
rpma: replace libpmem with libpmem2

Ref: pmem/rpma#992
```


<!-- Sent from Reviewable.io -->

2022-02-16 14:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-Mw1w-3a36-LkehfX7so:-Mw1w-3b9GOgwNHgL6T7:b-ujmq67) (no related file):*
Rebase please

---


<!-- Sent from Reviewable.io -->

2022-02-17 11:31 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @ldorau and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-Mw1w-3a36-LkehfX7so:-Mw6Rmjo7pZFy9U6Debm:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvsepuM9etL92OxsjgU):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
rpma: replace libpmem with libpmem2

Ref: pmem/rpma#992
```

</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 146 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-146:-Mw6RgWM9E4jgi2VY3Oi:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L146)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

please add error handling
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 162 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-162:-Mw6Rg7dDIXBK12zhX5s:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L162)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

check error code, instead of using variable
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 174 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-174:-Mw6RhIiAL85rJ92gtrt:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L174)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

dead code. please handle this check like in rpma example
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 198 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-198:-Mw6RhqU4e1P8Aed72eC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L198)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

dead code
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 216 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-216:-Mw6RiVp4pduOvgtTkqj:b-cheemp) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L216)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

is it correct?
</blockquote></details>

is it better now? any suggestions?


<!-- Sent from Reviewable.io -->

2022-02-17 11:49 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @ldorau and @lplewa)



<!-- Sent from Reviewable.io -->

2022-02-18 10:51 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @ldorau and @lplewa)



<!-- Sent from Reviewable.io -->

2022-02-18 11:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MwBXg8G3XNVT2J457_9:-MwBXg8H44iru-Q9zWVj:b-ujmq67) (no related file):*
Rebase please

---


<!-- Sent from Reviewable.io -->

2022-02-18 11:53 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)



<!-- Sent from Reviewable.io -->

2022-02-18 12:28 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 14 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 140 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBkgcv11Mn6v7EZd-P:-MwBkgcv11Mn6v7EZd-Q:b31ash2) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L140)):*
> ```C
> 		return NULL;
> 	}
> 	if((fd = open(f->file_name, O_RDWR)) < 0) {
> ```

missing empty line



_Code quote:_
```C
	}
	if((fd = open(f->file_name, O_RDWR)) < 0) {
```
___
*[engines/librpma_fio.c, line 146 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBlAa84HJP4orqllBX:-MwBlAa84HJP4orqllBY:b5vk8cu) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L146)):*
> ```C
> 
> 	if (pmem2_source_from_fd(&src, fd) != 0) {
> 		log_err("pmem2_source_from_fd");
> ```

`"fio: pmem2_source_from_fd() failed"`



_Code quote:_
```C
pmem2_source_from_fd"
```
___
*[engines/librpma_fio.c, line 151 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBla7o6r7AjCrElGeR:-MwBla7o6r7AjCrElGeS:b3kqx) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L151)):*
> ```C
> 
> 	if (pmem2_config_new(&cfg) != 0) {
> 		log_err("pmem2_config_new");
> ```

.



_Code quote:_
```C
log_err("pmem2_config_new");
```
___
*[engines/librpma_fio.c, line 162 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnLjP32IczZSsL6Bc:-MwBnLjP32IczZSsL6Bd:b-p8tvjk) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L162)):*
> ```C
> 
> 	if (pmem2_map_new(&map, cfg, src) != 0) {
> 		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
> ```

`pmem2_map_new`



_Code quote:_
```C
pmem_map_file
```
___
*[engines/librpma_fio.c, line 163 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnSbkCcNCOWo-Ig6u:-MwBnSbkCcNCOWo-Ig6v:b4gakvb) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L163)):*
> ```C
> 	if (pmem2_map_new(&map, cfg, src) != 0) {
> 		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
> 		/* pmem_map_file() sets errno on failure */
> ```

Is it still true for `pmem2_map_new` ?



_Code quote:_
```C
/* pmem_map_file() sets errno on failure */
```
___
*[engines/librpma_fio.c, line 164 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnWox4e2zlwndit-o:-MwBnWox4e2zlwndit-p:b-p8tvjk) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L164)):*
> ```C
> 		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
> 		/* pmem_map_file() sets errno on failure */
> 		td_verror(td, errno, "pmem_map_file");
> ```

`pmem2_map_new`



_Code quote:_
```C
pmem_map_file
```


<!-- Sent from Reviewable.io -->

2022-02-18 12:38 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 15 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 157 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBppBv08wyCFQPQ11I:-MwBppBv08wyCFQPQ11J:b3kqx) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L157)):*
> ```C
> 	if (pmem2_config_set_required_store_granularity(cfg,
> 					 PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 		log_err("pmem2_config_set_required_store_granularity");
> ```

.



_Code quote:_
```C
log_err("pmem2_config_set_required_store_granularity");
```


<!-- Sent from Reviewable.io -->

2022-02-18 14:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 26 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 183 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCHVXT9V4LD01lUEZk:-MwCHVXT9V4LD01lUEZl:b-j8smk0) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L183)):*
> ```C
> 
> 	mem->mem_ptr = mem_ptr;
> 	mem->size_mmap = size_mmap;
> ```

Intermediate variables are redundant:

```
	mem->mem_ptr = pmem2_map_get_address(map);
	mem->size_mmap = pmem2_map_get_size(map);

```



_Code quote:_
```C
	mem->mem_ptr = mem_ptr;
	mem->size_mmap = size_mmap;
```
___
*[engines/librpma_fio.c, line 189 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCHNC59ZghLrk04Uiu:-MwCHNC59ZghLrk04Uiv:b-58kki4) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L189)):*
> ```C
> 
> 	close(fd);
> 	return mem_ptr + ws_offset;
> ```

```
	mem->src = src;
	close(fd);

	return mem_ptr + ws_offset;
```



_Code quote:_
```C
	mem->src = src;

	close(fd);
	return mem_ptr + ws_offset;
```


<!-- Sent from Reviewable.io -->

2022-02-18 14:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 2 of 7 files reviewed, 28 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 119 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCHzjTClwI2I6PCdQ0:-MwCHzjTClwI2I6PCdQ1:b-p6p4y3) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L119)):*
> ```C
> 	struct pmem2_source *src = NULL;
> 	char *mem_ptr = NULL;
> 	size_t size_mmap = 0;
> ```

Redundant intermediate variables - see below.



_Code quote:_
```C
	char *mem_ptr = NULL;
	size_t size_mmap = 0;
```
___
*[engines/librpma_fio.c, line 169 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCHpMQDFiGsZVignMU:-MwCHpMR-17imxAcplul:b-gr4ckq) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L169)):*
> ```C
> 
> 	mem_ptr = pmem2_map_get_address(map);
> 	size_mmap = pmem2_map_get_size(map);
> ```

It can be moved below - see below.



_Code quote:_
```C
	mem_ptr = pmem2_map_get_address(map);
	size_mmap = pmem2_map_get_size(map);
```


<!-- Sent from Reviewable.io -->

2022-02-18 14:54 UTC, ldorau requested changes
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 3 of 7 files reviewed, 31 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.h, line 72 at r1](https://reviewable.io/reviews/pmem/fio/269#-MvpOX5V6aftI7Uz6Yl9:-MwCJCv2C1vpm8RjD3jC:bajogpa) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.h#L72)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

There is no need to keep mem_ptr and size_mmap beacuse of possibility of getting these informations from pmem2_map, I kept it temporarily to ask about an opinion 
</blockquote></details>

`mem_ptr` is required for DRAM and `size_mmap` is needed to check if it is an allocation from DRAM or not.
___
*[engines/librpma_fio.h, line 77 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCJbKNA1du9VQcEOZe:-MwCJbKNA1du9VQcEOZf:b-t1hfie) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.h#L77)):*
> ```objc
> 	size_t size_mmap;
> 
> 	struct pmem2_config *cfg;
> ```

Add a comment, please



_Code quote:_
```objc
	struct pmem2_config *cfg;
	struct pmem2_map *map;
	struct pmem2_source *src;
```
___
*[engines/librpma_fio.c, line 208 at r1](https://reviewable.io/reviews/pmem/fio/269#-MvpNB6zCeSoJqa28ziB:-MwCJls76FswoGFnTysI:bn847cd) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.c#L208)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

because of this function I decided to temporarily add new libpmem2 structures  to librpma_fio_mem structure, I am not sure which way to choose (new struct or modify the existing one everywhere)
</blockquote></details>

What "new libpmem2 structures" have you added? What do you mean?


<!-- Sent from Reviewable.io -->

2022-02-18 14:55 UTC, ldorau requested changes
> Reviewed 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 5 of 7 files reviewed, 33 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[Makefile, line 114 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCK4co8unUJhUN_UqV:-MwCK4co8unUJhUN_UqW:byb5fig) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/Makefile#L114)):*
> ```Makefile
>   librpma_apm_SRCS = engines/librpma_apm.c
>   librpma_fio_SRCS = engines/librpma_fio.c
>   librpma_apm_LIBS = -lrpma -lpmem -lpmem2
> ```

`-lpmem` can be removed now



_Code quote:_
```Makefile
-lpmem -lpmem2
```
___
*[Makefile, line 120 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCKAMrCVuS2VTu03jf:-MwCKAMrCVuS2VTu03jg:byb5fig) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/Makefile#L120)):*
> ```Makefile
>   librpma_gpspm_SRCS = engines/librpma_gpspm.c engines/librpma_gpspm_flush.pb-c.c
>   librpma_fio_SRCS = engines/librpma_fio.c
>   librpma_gpspm_LIBS = -lrpma -lpmem -lpmem2 -lprotobuf-c
> ```

`-lpmem` can be removed now



_Code quote:_
```Makefile
-lpmem -lpmem2 
```


<!-- Sent from Reviewable.io -->

2022-02-21 06:39 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 7 files reviewed, 35 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[configure, line 2212 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwPzz7m38MjYItNIokQ:-MwPzz7m38MjYItNIokR:b-rymgyq) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/configure#L2212)):*
> ```
>   fi
>   if test "$libpmem2" = "yes"; then
>       pmem2="yes"
> ```

`pmem2` does not depend on `libpmem` - revert this change and add a one below, please.



_Code quote:_
```
if test "$libpmem" = "yes" && test "$disable_pmem" = "no"; then
  devdax="yes"
  if test "$libpmem1_5" = "yes"; then
    pmem="yes"
  fi
  if test "$libpmem2" = "yes"; then
      pmem2="yes"
  fi
```
___
*[configure, line 2218 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwQ-QGJ7JChlF1RULVw:-MwQ-QGJ7JChlF1RULVx:b3k5r45) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/configure#L2218)):*
> ```
>   fi
> fi
> ```

```
# Choose libpmem2-based ioengines
if test "$libpmem2" = "yes" && test "$disable_pmem" = "no"; then
  pmem2="yes"
fi
```


<!-- Sent from Reviewable.io -->

2022-02-21 06:40 UTC, ldorau reviewed
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 35 unresolved discussions (waiting on @haichangsi and @lplewa)



<!-- Sent from Reviewable.io -->

2022-02-21 08:28 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 35 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[configure, line 2218 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwQ-QGJ7JChlF1RULVw:-MwQNvnt6kg_Xv1GgLPS:b-xwscq4) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/configure#L2218)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
# Choose libpmem2-based ioengines
if test "$libpmem2" = "yes" && test "$disable_pmem" = "no"; then
  pmem2="yes"
fi
```
</blockquote></details>

And the comment should be changed:
`# check if the pmem2 engine can be enabled`


<!-- Sent from Reviewable.io -->

2022-02-23 22:04 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 34 unresolved discussions (waiting on @ldorau and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MwBXg8G3XNVT2J457_9:-MwBf3CjC5o66UehwQbi:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
___
*[configure, line 2212 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwPzz7m38MjYItNIokQ:-MwbsC5FDp2u7QpzfUrC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/configure#L2212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`pmem2` does not depend on `libpmem` - revert this change and add a one below, please.
</blockquote></details>

Done.
___
*[configure, line 2218 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwQ-QGJ7JChlF1RULVw:-Mwbt5wdDhjvf8efLlMb:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/configure#L2218)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

And the comment should be changed:
`# check if the pmem2 engine can be enabled`
</blockquote></details>

Done.
___
*[Makefile, line 114 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCK4co8unUJhUN_UqV:-Mwbu3l_6WafYSHjkix_:bqi5vr3) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/Makefile#L114)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`-lpmem` can be removed now
</blockquote></details>

I wanted to do it after the second pr. Done
___
*[Makefile, line 120 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCKAMrCVuS2VTu03jf:-MwbuIow2omq8VoD4qlt:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/Makefile#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`-lpmem` can be removed now
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 77 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCJbKNA1du9VQcEOZe:-Mwc0Rou3F7eEZoOiXSs:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.h#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add a comment, please
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 208 at r1](https://reviewable.io/reviews/pmem/fio/269#-MvpNB6zCeSoJqa28ziB:-MwcAa3rArBimo8FJtdq:b-fo9ffl) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.c#L208)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What "new libpmem2 structures" have you added? What do you mean?
</blockquote></details>

I added 3 structures (pmem2_config, pmem2_map, pmem2_source structures inside the librpma_fio_mem structure definition) but this seems to be a good way to deal with this problem so it is all right 
___
*[engines/librpma_fio.c, line 119 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCHzjTClwI2I6PCdQ0:-MwcN6sw2Q7dQ523wSNY:b-y9meh4) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Redundant intermediate variables - see below.
</blockquote></details>

Same as below
___
*[engines/librpma_fio.c, line 140 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBkgcv11Mn6v7EZd-P:-Mwc0xDQ5OCML5plg8Va:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L140)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing empty line
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 146 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBlAa84HJP4orqllBX:-Mwc1_zj1xu4Dkhx_uU-:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L146)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`"fio: pmem2_source_from_fd() failed"`
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 147 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwC96zl1MHBNxVMjlTU:-Mwc1Ic81J4uQL6Rfpxw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L147)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`err_close`
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 151 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBla7o6r7AjCrElGeR:-Mwc28A6CWxw3XC1M0Z7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 152 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwC9Gvo4YhBy7ZxYji4:-Mwc2_xgEBbjdO1Nhq3r:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L152)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`err_source_delete`
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 157 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBppBv08wyCFQPQ11I:-Mwc2fInBL-SnHQoBPTY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 158 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwC9OsI12okcee6hNXa:-Mwc2o1C7vCz0IyJmBHa:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`err_config_delete`
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 162 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnLjP32IczZSsL6Bc:-Mwc3-vV0ge2IGZbEgXN:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`pmem2_map_new`
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 163 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnSbkCcNCOWo-Ig6u:-Mwc8GpL1Yav0jF8VAuI:b-f5o7fc) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Is it still true for `pmem2_map_new` ?
</blockquote></details>

it is not, td_verror needs errno as an argument, should I found an alternative ?
___
*[engines/librpma_fio.c, line 164 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnWox4e2zlwndit-o:-Mwc8Xbt61o8zMQazb2I:b3kqx) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`pmem2_map_new`
</blockquote></details>

.
___
*[engines/librpma_fio.c, line 165 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwCDpFF0TbX83u67yw9:-Mwc9Q964Jvnf7CuCyzP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L165)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`err_config_delete`
</blockquote></details>

Done.
___
*[engines/librpma_fio.c [...]

2022-02-28 09:11 UTC, ldorau requested changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[engines/librpma_fio.h, line 77 at r9](https://reviewable.io/reviews/pmem/fio/269#-MwzVc4k-VJceNw_R5cg:-MwzVc4l2jt-G2NJaztZ:bb71lgq) ([raw file](https://github.com/pmem/fio/blob/8358ed04bed5f8c3cab050c85fc300acbf8aab80/engines/librpma_fio.h#L77)):*
> ```objc
> 	size_t size_mmap;
> 
> 	/* libpmem2 structures used for mapping pmem */
> ```

PMem



_Code quote:_
```objc
pmem
```
___
*[engines/librpma_fio.c, line 208 at r1](https://reviewable.io/reviews/pmem/fio/269#-MvpNB6zCeSoJqa28ziB:-MwzaB5Z8zzbylSXz73w:b-hgm9xj) ([raw file](https://github.com/pmem/fio/blob/723ab6d9e9fd4638079f4e49cc6c9546c49743e6/engines/librpma_fio.c#L208)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I added 3 structures (pmem2_config, pmem2_map, pmem2_source structures inside the librpma_fio_mem structure definition) but this seems to be a good way to deal with this problem so it is all right 
</blockquote></details>

It is OK now, resolve this issue, please.
___
*[engines/librpma_fio.c, line 162 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnLjP32IczZSsL6Bc:-MwzVwpREN0vOxV_yQFT:beyn8lk) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L162)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, "2" is missing
___
*[engines/librpma_fio.c, line 163 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnSbkCcNCOWo-Ig6u:-Mwz_1pC00-yQrg6rOs9:b-rwhzu0) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L163)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

it is not, td_verror needs errno as an argument, should I found an alternative ?
</blockquote></details>

Removing is OK
___
*[engines/librpma_fio.c, line 118 at r9](https://reviewable.io/reviews/pmem/fio/269#-MwzaNA09yS1dm4q4SI-:-MwzaNA09yS1dm4q4SI0:bfqov37) ([raw file](https://github.com/pmem/fio/blob/8358ed04bed5f8c3cab050c85fc300acbf8aab80/engines/librpma_fio.c#L118)):*
> ```C
> 	struct pmem2_map *map = NULL;
> 	struct pmem2_source *src = NULL;
> 	size_t size_mmap = 0;
> ```

`size_t size_mmap;`



_Code quote:_
```C
size_t size_mmap = 0;
```


<!-- Sent from Reviewable.io -->

2022-02-28 11:12 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @ldorau and @lplewa)

___
*[engines/librpma_fio.h, line 77 at r9](https://reviewable.io/reviews/pmem/fio/269#-MwzVc4k-VJceNw_R5cg:-Mx-04uiE_T0KoTAQONz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8358ed04bed5f8c3cab050c85fc300acbf8aab80/engines/librpma_fio.h#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

PMem
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 162 at r8](https://reviewable.io/reviews/pmem/fio/269#-MwBnLjP32IczZSsL6Bc:-Mx-0b-R7svWkmVUuhjm:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1da905b6b7d4e67ec73423ac95a26b2ea4abae5c/engines/librpma_fio.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, "2" is missing
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 118 at r9](https://reviewable.io/reviews/pmem/fio/269#-MwzaNA09yS1dm4q4SI-:-Mx-0ARC4P6dzozLGsc7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8358ed04bed5f8c3cab050c85fc300acbf8aab80/engines/librpma_fio.c#L118)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`size_t size_mmap;`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-28 11:19 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @lplewa)



<!-- Sent from Reviewable.io -->

2022-03-01 11:20 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-Mx4CNCK70IN1fRMLibP:-Mx4CNCK70IN1fRMLibQ:b-rczdnh) (no related file):*
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , but we have to wait with merging this patch until libpmem2 is included (as a package) in most of popular Linux distributions, so that fio does not require building and installing whole PMDK from sources.

---


<!-- Sent from Reviewable.io -->

2022-03-01 11:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-Mx4DRN3EUy8vQugxoUt:-Mx4DRN3EUy8vQugxoUu:b-e0xsvq) (no related file):*
LGTM , but we have to wait with merging this patch until libpmem2 is included (as a package) in most of popular Linux distributions, so that fio does not require building and installing whole PMDK from sources (@lplewa @kilobyte).

---


<!-- Sent from Reviewable.io -->

2022-03-01 13:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @lplewa)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-Mx4DRN3EUy8vQugxoUt:-Mx4dAaO0qJSjylt8klc:bfugqxw) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

LGTM , but we have to wait with merging this patch until libpmem2 is included (as a package) in most of popular Linux distributions, so that fio does not require building and installing whole PMDK from sources (@lplewa @kilobyte).
</blockquote></details>

@haichangsi Another solution can be applied - please change this PR so that fio could use libpmem if libpmem2 is not available in OS.

---


<!-- Sent from Reviewable.io -->

2022-03-04 09:20 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[Makefile, line 120 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJDacM-333gfR0_P9O:-MxJDacM-333gfR0_P9P:b-q9ycvo) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/Makefile#L120)):*
> ```Makefile
>   librpma_gpspm_SRCS = engines/librpma_gpspm.c engines/librpma_gpspm_flush.pb-c.c
>   librpma_fio_SRCS = engines/librpma_fio.c
>   librpma_gpspm_LIBS = -lrpma -lpmem2 -lprotobuf-c
> ```

You should add `-lpmem` here too.



_Code quote:_
```Makefile
-lrpma -lpmem2 -lprotobuf-c
```


<!-- Sent from Reviewable.io -->

2022-03-04 12:15 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 7 files reviewed, 12 unresolved discussions (waiting on @haichangsi, @ldorau, and @lplewa)

___
*[configure, line 2961 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJqPFREcjrH7MhteXO:-MxJqPFREcjrH7MhteXP:buxxmmp) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L2961)):*
> ```
> # librpma is supported on the 'x86_64' architecture for now
> if test "$cpu" = "x86_64" -a "$libverbs" = "yes" -a "$rdmacm" = "yes" \
>     -a "$librpma" = "yes" -a "$libpmem" = "yes" ; then
> ```

I do not know if this syntax will work, but something like this has to be added here:
```
 -a ( "$libpmem" = "yes" -o "$libpmem2" = "yes" )
```



_Code quote:_
```
 -a "$libpmem" = "yes" 
```
___
*[configure, line 2965 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJqeqRA88f_XAJWFjB:-MxJqeqRA88f_XAJWFjC:b3kqx) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L2965)):*
> ```
> fi
> if test "$cpu" = "x86_64" -a "$libverbs" = "yes" -a "$rdmacm" = "yes" \
>     -a "$librpma" = "yes" -a "$libpmem" = "yes" -a "$libprotobuf_c" = "yes" ; then
> ```

.



_Code quote:_
```
 -a "$libpmem" = "yes"
```
___
*[engines/librpma_fio.c, line 128 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJfG-52E08H8ZnmuBE:-MxJfG-6B4OMIhItUGPn:b-5tm7zu) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/engines/librpma_fio.c#L128)):*
> ```C
> #endif
> 
> 	size_t size_mmap;
> ```

Now it has to be:
```c
size_t size_mmap = 0;
```



_Code quote:_
```C
size_t size_mmap;
```
___
*[engines/librpma_fio.c, line 253 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJfTT84vDX0VorUxRq:-MxJfTT84vDX0VorUxRr:b7ozvmp) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/engines/librpma_fio.c#L253)):*
> ```C
> void librpma_fio_free(struct librpma_fio_mem *mem)
> {
> 	if (mem->size_mmap) {
> ```

It has to be ifdefed too.



_Code quote:_
```C
	if (mem->size_mmap) {
		pmem2_map_delete(&mem->map);
		pmem2_config_delete(&mem->cfg);
		pmem2_source_delete(&mem->src);
	} else {
		free(mem->mem_ptr);
	}
```
___
*[engines/librpma_fio.c, line 260 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJfOqwABLJEtIziecG:-MxJfOqwABLJEtIziecH:b-nsqcu9) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/engines/librpma_fio.c#L260)):*
> ```C
> 		free(mem->mem_ptr);
> 	}
> 		
> ```

redundant empty line



_Code quote:_
```C
	··
```


<!-- Sent from Reviewable.io -->

2022-03-04 13:14 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[configure, line 2235 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJr2Sz1J6WPwJLrwx-:-MxJr2T-7FImT_GOSPO0:b3i2mvf) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L2235)):*
> ```
> fi
> 
> # Check if the pmem2 engine can be enabled
> ```

You are NOT adding the pmem2 engine so it should be removed.



_Code quote:_
```
# Check if the pmem2 engine can be enabled
if test "$libpmem2" = "yes" && test "$disable_pmem" = "no"; then
    pmem2="yes"
fi
```
___
*[configure, line 2253 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJrIa9BnjMoI2IsWYT:-MxJrIa9BnjMoI2IsWYU:b3i2mvf) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L2253)):*
> ```
> 
> ##########################################
> # Report whether libpmem2 engine is enabled
> ```

You are NOT adding the pmem2 engine so it should be removed.



_Code quote:_
```
##########################################
# Report whether libpmem2 engine is enabled
print_config "PMDK libpmem2 engine" "$pmem2"
```
___
*[configure, line 3110 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJrP667mLO1lV9TKsd:-MxJrP667mLO1lV9TKse:bulojl7) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L3110)):*
> ```
> fi
> if test "$pmem2" = "yes" ; then
>   output_sym "CONFIG_LIBPMEM2"
> ```

You are not adding the pmem2 engine so it should be removed.



_Code quote:_
```
if test "$pmem2" = "yes" ; then
  output_sym "CONFIG_LIBPMEM2"
fi
```
___
*[configure, line 3113 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJrWg97SULIf7bhsIO:-MxJrWg97SULIf7bhsIP:bxxm2z4) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L3113)):*
> ```
> fi
> if test "$libpmem2" = "yes" ; then
>   output_sym "LIBPMEM2_AVAILABLE"
> ```

Maybe `CONFIG_LIBPMEM2_INSTALLED` ? All variables should be prefixed with `CONFIG_` ...



_Code quote:_
```
LIBPMEM2_AVAILABLE
```


<!-- Sent from Reviewable.io -->

2022-03-07 07:32 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @lplewa)



<!-- Sent from Reviewable.io -->

2022-03-07 07:48 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[engines/librpma_fio.c, line 116 at r12](https://reviewable.io/reviews/pmem/fio/269#-MxYJRry-8YK403zfZQV:-MxYJRrz5GY_tl4bGdnU:bh4cksf) ([raw file](https://github.com/pmem/fio/blob/3b65fa3d0b956773c0ebba00c691212e93418516/engines/librpma_fio.c#L116)):*
> ```C
> 
> char *librpma_fio_allocate_pmem(struct thread_data *td, struct fio_file *f,
> 		size_t size, struct librpma_fio_mem *mem)
> ```

Since there is very little of common code I think it would be more clear and readable to 'idef' whole functions:
```c
char *librpma_fio_allocate_pmem(struct thread_data *td, struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem)
#ifdef CONFIG_LIBPMEM2_INSTALLED
{
    /* LIBPMEM2 version */
}
#else
{
    /* LIBPMEM version */
}
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```



_Code quote:_
```C
char *librpma_fio_allocate_pmem(struct thread_data *td, struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem)
{
#ifdef CONFIG_LIBPMEM2_INSTALLED
	int fd;
	struct pmem2_config *cfg = NULL;
	struct pmem2_map *map = NULL;
	struct pmem2_source *src = NULL;
#else
	char *mem_ptr = NULL;
	int is_pmem = 0;
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```
___
*[engines/librpma_fio.c, line 253 at r12](https://reviewable.io/reviews/pmem/fio/269#-MxYL3jw1fkroiH2v-GK:-MxYL3jw1fkroiH2v-GL:b-1a237q) ([raw file](https://github.com/pmem/fio/blob/3b65fa3d0b956773c0ebba00c691212e93418516/engines/librpma_fio.c#L253)):*
> ```C
> void librpma_fio_free(struct librpma_fio_mem *mem)
> {
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> ```

Please move curly brackets into ifdefs, so that it is clear that the whole function's body is ifdef'ed:
```c
void librpma_fio_free(struct librpma_fio_mem *mem)
#ifdef CONFIG_LIBPMEM2_INSTALLED
{
    /* LIBPMEM2 version */
}
#else
{
    /* LIBPMEM version */
}
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```



_Code quote:_
```C
void librpma_fio_free(struct librpma_fio_mem *mem)
{
#ifdef CONFIG_LIBPMEM2_INSTALLED
```


<!-- Sent from Reviewable.io -->

2022-03-07 12:42 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau and @lplewa)

___
*[configure, line 2961 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJqPFREcjrH7MhteXO:-MxOycEFDEHWee7mOCNc:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L2961)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not know if this syntax will work, but something like this has to be added here:
```
 -a ( "$libpmem" = "yes" -o "$libpmem2" = "yes" )
```
</blockquote></details>

Done.
___
*[configure, line 2965 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJqeqRA88f_XAJWFjB:-MxOychM5Yiw5V4qhc-j:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L2965)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[configure, line 3110 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJrP667mLO1lV9TKsd:-MxOyqgq0qppreBoXt2U:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L3110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You are not adding the pmem2 engine so it should be removed.
</blockquote></details>

Done.
___
*[configure, line 3113 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJrWg97SULIf7bhsIO:-MxOz15zBUzKI1GmBPoO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/configure#L3113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe `CONFIG_LIBPMEM2_INSTALLED` ? All variables should be prefixed with `CONFIG_` ...
</blockquote></details>

Done.
___
*[Makefile, line 120 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJDacM-333gfR0_P9O:-MxOz4YN9hNXwg0AoxtF:bpvq2zs) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/Makefile#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You should add `-lpmem` here too.
</blockquote></details>

I wanted  to do that in the pr including CONFIG_LIBRPMA_GPSPM changes. Done.
___
*[engines/librpma_fio.c, line 128 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJfG-52E08H8ZnmuBE:-MxOzdKM4q-wqq7i6Rz7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/engines/librpma_fio.c#L128)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Now it has to be:
```c
size_t size_mmap = 0;
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 260 at r11](https://reviewable.io/reviews/pmem/fio/269#-MxJfOqwABLJEtIziecG:-MxP0aws8I2XysuW2_sa:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b67bdab2ffcec86d57c312ae0a29563db163c5c6/engines/librpma_fio.c#L260)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 116 at r12](https://reviewable.io/reviews/pmem/fio/269#-MxYJRry-8YK403zfZQV:-MxZM9Td8QPHde9IFBwm:b8gd4cd) ([raw file](https://github.com/pmem/fio/blob/3b65fa3d0b956773c0ebba00c691212e93418516/engines/librpma_fio.c#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Since there is very little of common code I think it would be more clear and readable to 'idef' whole functions:
```c
char *librpma_fio_allocate_pmem(struct thread_data *td, struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem)
#ifdef CONFIG_LIBPMEM2_INSTALLED
{
    /* LIBPMEM2 version */
}
#else
{
    /* LIBPMEM version */
}
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```
</blockquote></details>

I thought about that. Done.
___
*[engines/librpma_fio.c, line 253 at r12](https://reviewable.io/reviews/pmem/fio/269#-MxYL3jw1fkroiH2v-GK:-MxZLVSz7wmuOf0vQcNc:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3b65fa3d0b956773c0ebba00c691212e93418516/engines/librpma_fio.c#L253)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move curly brackets into ifdefs, so that it is clear that the whole function's body is ifdef'ed:
```c
void librpma_fio_free(struct librpma_fio_mem *mem)
#ifdef CONFIG_LIBPMEM2_INSTALLED
{
    /* LIBPMEM2 version */
}
#else
{
    /* LIBPMEM version */
}
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 13:56 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[engines/librpma_fio.c, line 124 at r13](https://reviewable.io/reviews/pmem/fio/269#-MxZeQcT7HDtDFDODqgw:-MxZeQcT7HDtDFDODqgx:b-mbh6qp) ([raw file](https://github.com/pmem/fio/blob/b645b626d084589cad9f4562b5f3b38a7082d2d8/engines/librpma_fio.c#L124)):*
> ```C
> 	struct pmem2_source *src = NULL;
> 
> 	size_t size_mmap = 0;
> ```

`size_t size_mmap;` in case of libpmem2



_Code quote:_
```C
size_t size_mmap = 0;
```


<!-- Sent from Reviewable.io -->

2022-03-07 21:03 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau and @lplewa)

___
*[engines/librpma_fio.c, line 124 at r13](https://reviewable.io/reviews/pmem/fio/269#-MxZeQcT7HDtDFDODqgw:-MxaBM6O7pTeY3PbBAmM:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b645b626d084589cad9f4562b5f3b38a7082d2d8/engines/librpma_fio.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`size_t size_mmap;` in case of libpmem2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 21:05 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @lplewa)

___
*[engines/librpma_fio.c, line 146 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-146:-MxaBl70437p-1qzEb1K:b-qidcvb) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L146)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@lplewa issue fixed, please resolve
___
*[engines/librpma_fio.c, line 162 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-162:-MxaBpYsDVRA94bAHxmA:b-qidcvb) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L162)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@lplewa issue fixed, please resolve
___
*[engines/librpma_fio.c, line 174 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-174:-MxaBqcsD0shjzDjfv9C:b-qidcvb) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L174)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@lplewa issue fixed, please resolve
___
*[engines/librpma_fio.c, line 198 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-198:-MxaBrM23dLCmwGOiSjD:b-qidcvb) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L198)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@lplewa issue fixed, please resolve
___
*[engines/librpma_fio.c, line 216 at r2](https://reviewable.io/reviews/pmem/fio/269#-MvpM_0lqgNqQdE2lPLo-r2-216:-MxaBsANDF6MAqZfFHf7:b-qidcvb) ([raw file](https://github.com/pmem/fio/blob/f846d6075e4ce52e66a5f36282ade9d7f6643594/engines/librpma_fio.c#L216)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

is it better now? any suggestions?
</blockquote></details>

@lplewa issue fixed, please resolve


<!-- Sent from Reviewable.io -->

2022-03-07 21:05 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269#-:-MxaBxF57MbvFsALYFcR:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @lplewa)



<!-- Sent from Reviewable.io -->

2022-03-08 07:29 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[Makefile, line 114 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcMFLg8_tnrN4GY52D:-MxcMFLg8_tnrN4GY52E:b-xz857t) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/Makefile#L114)):*
> ```Makefile
>   librpma_apm_SRCS = engines/librpma_apm.c
>   librpma_fio_SRCS = engines/librpma_fio.c
>   librpma_apm_LIBS = -lrpma -lpmem -lpmem2
> ```

how does it work if we have only libpmem2 installed (I mean - no libpmem)?



_Code quote:_
```Makefile
  librpma_apm_LIBS = -lrpma -lpmem -lpmem2
```
___
*[options.c, line 2130 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcNQBf7KCXcnrPO8Kw:-MxcNQBf7KCXcnrPO8Kx:b-yvnre4) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/options.c#L2130)):*
> ```C
> 			  },
> #endif
> #ifdef CONFIG_LIBPMEM2
> ```

What is this part of code responsible for?



_Code quote:_
```C
#ifdef CONFIG_LIBPMEM2
			  { .ival = "libpmem2",
				  .help = "PMDK libpmem2 based IO engine",
			  },
#endif
```
___
*[engines/librpma_fio.c, line 276 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcOFraAkPuO65oCS_0:-MxcOFraAkPuO65oCS_1:bcmiuq5) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L276)):*
> ```C
> 	if (mem->size_mmap) {
> 		pmem2_map_delete(&mem->map);
> 		pmem2_config_delete(&mem->cfg);
> ```

@lplewa: do we need cfg all the time engine runs?



_Suggestion:_
```C
		pmem2_config_delete(&mem->cfg);
	
```


<!-- Sent from Reviewable.io -->

2022-03-08 07:37 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 10 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[engines/librpma_fio.c, line 277 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcRtSkBJqw1kctsfge:-MxcRtSkBJqw1kctsfgf:b-jpwzj7) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L277)):*
> ```C
> 		pmem2_map_delete(&mem->map);
> 		pmem2_config_delete(&mem->cfg);
> 		pmem2_source_delete(&mem->src);
> ```

@lplewa: do we need src all the time engine runs?



_Code quote:_
```C
pmem2_source_delete(&mem->src);
```
___
*[engines/librpma_fio.c, line 287 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcS7DU5IEH65fC5H_H:-MxcS7DU5IEH65fC5H_I:b4mb235) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L287)):*
> ```C
> 		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
> 	else
> 		free(mem->mem_ptr);
> ```

redundancy of code
can we use ```#ifdef CONFIG_LIBPMEM2_INSTALLED``` only for pmem related source code and DRAM part keep in one place?



_Code quote:_
```C
free(mem->mem_ptr);
```


<!-- Sent from Reviewable.io -->

2022-03-08 07:39 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[engines/librpma_fio.c, line 213 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcSiyi7kgNLOId7DTq:-MxcSiyi7kgNLOId7DTr:b-927luy) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L213)):*
> ```C
> 	size_t ws_offset;
> 
> 	if (size % page_size) {
> ```

redundant code shall be outside the scope of  ```#ifdef CONFIG_LIBPMEM2_INSTALLED```



_Code quote:_
```C
	if (size % page_size) {
		log_err("fio: size (%zu) is not aligned to page size (%zu)\n",
			size, page_size);
		return NULL;
	}

	if (f->filetype == FIO_TYPE_CHAR) {
		/* Each thread uses a separate offset within DeviceDAX. */
		ws_offset = (td->thread_number - 1) * size;
	} else {
		/* Each thread uses a separate FileSystemDAX file. No offset is needed. */
		ws_offset = 0;
	}

	if (!f->file_name) {
		log_err("fio: filename is not set\n");
		return NULL;
	}
```


<!-- Sent from Reviewable.io -->

2022-03-08 10:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[options.c, line 2130 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcNQBf7KCXcnrPO8Kw:-MxdABBOE-fTnFcFhmKR:b-5q89ra) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/options.c#L2130)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is this part of code responsible for?
</blockquote></details>

For libpmem2 engine - it is an overlooked part of another pull request.

@haichangsi it should be removed


<!-- Sent from Reviewable.io -->

2022-03-08 11:36 UTC, lplewa reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72, @haichangsi, and @lplewa)

___
*[engines/librpma_fio.c, line 163 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdEZxfAc6o_gCoYjSn:-MxdEZxfAc6o_gCoYjSo:buoqyof) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L163)):*
> ```C
> 	if (pmem2_config_set_required_store_granularity(cfg,
> 					 PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 		log_err("fio: pmem2_config_set_required_store_granularity() failed");
> ```

Please use pmem2_errormsg(), to log detailed error
___
*[engines/librpma_fio.c, line 168 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdEhYF1uQ5IK5wBoqA:-MxdEhYF1uQ5IK5wBoqB:buoqyof) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L168)):*
> ```C
> 
> 	if (pmem2_map_new(&map, cfg, src) != 0) {
> 		log_err("fio: pmem2_map_new(%s) failed\n", f->file_name);
> ```

Please use pmem2_errormsg(), to log detailed error
___
*[engines/librpma_fio.c, line 276 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcOFraAkPuO65oCS_0:-MxdJEYw4YqXKW8RKhRS:b-92v6dv) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L276)):*
> you don't need it
___
*[engines/librpma_fio.c, line 277 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcRtSkBJqw1kctsfge:-MxdJABsAF6CjpgZntM7:bnisc0v) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L277)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@lplewa: do we need src all the time engine runs?
</blockquote></details>

you don't need it


<!-- Sent from Reviewable.io -->

2022-03-08 11:47 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72, @haichangsi, and @lplewa)

___
*[Makefile, line 114 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcMFLg8_tnrN4GY52D:-MxdLXwC9XFf9QBgFPpg:b-8g3lvo) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/Makefile#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

how does it work if we have only libpmem2 installed (I mean - no libpmem)?
</blockquote></details>

Right, it will not work. It should be replaced with:

```
  ifdef CONFIG_LIBPMEM2_INSTALLED
    librpma_apm_LIBS = -lrpma -lpmem2
  else
    librpma_apm_LIBS = -lrpma -lpmem
  endif
```
___
*[Makefile, line 120 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdLdiS-aBLRzF5ZyWa:-MxdLdiS-aBLRzF5ZyWb:bkj2mug) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/Makefile#L120)):*
> ```Makefile
>   librpma_gpspm_SRCS = engines/librpma_gpspm.c engines/librpma_gpspm_flush.pb-c.c
>   librpma_fio_SRCS = engines/librpma_fio.c
>   librpma_gpspm_LIBS = -lrpma -lpmem -lpmem2 -lprotobuf-c
> ```

```
  ifdef CONFIG_LIBPMEM2_INSTALLED
    librpma_gpspm_LIBS = -lrpma -lpmem2 -lprotobuf-c
  else
    librpma_gpspm_LIBS = -lrpma -lpmem -lprotobuf-c
  endif
```



_Code quote:_
```Makefile
  librpma_gpspm_LIBS = -lrpma -lpmem -lpmem2 -lprotobuf-c
```


<!-- Sent from Reviewable.io -->

2022-03-08 11:57 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72, @haichangsi, and @lplewa)

___
*[engines/librpma_fio.c, line 213 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcSiyi7kgNLOId7DTq:-MxdNfWzCwGvFxtP5IWl:b3us9yg) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L213)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant code shall be outside the scope of  ```#ifdef CONFIG_LIBPMEM2_INSTALLED```
</blockquote></details>

1) Why do you think it is a redundant code?
2) It is scope of libpmem(1), not libpmem2.


<!-- Sent from Reviewable.io -->

2022-03-08 12:07 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)



<!-- Sent from Reviewable.io -->

2022-03-08 12:09 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_fio.c, line 276 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcOFraAkPuO65oCS_0:-MxdQWD8EuJGlC7u_ddQ:b-jg7nnv) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L276)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

> you don't need it
</blockquote></details>

@haichangsi please remove cfg from mem as it is needed only for short period of time


<!-- Sent from Reviewable.io -->

2022-03-08 12:09 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-08 12:10 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[options.c, line 2130 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcNQBf7KCXcnrPO8Kw:-MxdQtup4_b0TGinaZcb:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/options.c#L2130)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

For libpmem2 engine - it is an overlooked part of another pull request.

@haichangsi it should be removed

</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-03-08 12:26 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 213 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcSiyi7kgNLOId7DTq:-MxdUCe-07WR8Xcdv5U6:b-f4vzad) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L213)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but the same code is at the beginning of ```librpma_fio_allocate_pmem()``` just after ```#ifdef CONFIG_LIBPMEM2_INSTALLED```
</blockquote></details>

Yes, I have asked @haichangsi to do so: https://github.com/pmem/fio/pull/269#pullrequestreview-901331339

In my opinion it is more important to keep code clear and readable than removing such small redundancy.


<!-- Sent from Reviewable.io -->

2022-03-08 12:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 146 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdVJeHAAxXiSZIBvtP:-MxdVJeHAAxXiSZIBvtQ:b4xrp75) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L146)):*
> ```C
> 	}
> 
> 		if((fd = open(f->file_name, O_RDWR)) < 0) {
> ```

Wrong indentation



_Code quote:_
```C
		if((fd = open(f->file_name, O_RDWR)) < 0) {
		log_err("fio: cannot open fio file\n");
```
___
*[engines/librpma_fio.c, line 233 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdVP273z1nGDPszxFo:-MxdVP273z1nGDPszxFp:b4xrp75) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L233)):*
> ```C
> 
> 		/* map the file */
> 	mem_ptr = pmem_map_file(f->file_name, 0 /* len */, 0 /* flags */,
> ```

Wrong indentation



_Code quote:_
```C
		/* map the file */
	mem_ptr = pmem_map_file(f->file_name, 0 /* len */, 0 /* flags */,
```


<!-- Sent from Reviewable.io -->

2022-03-08 12:32 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.c, line 287 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcS7DU5IEH65fC5H_H:-MxdVtMcEjuVEjaawMag:b-q5vsua) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L287)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundancy of code
can we use ```#ifdef CONFIG_LIBPMEM2_INSTALLED``` only for pmem related source code and DRAM part keep in one place?
</blockquote></details>

Yes, we can do that in this way:

```c
void librpma_fio_free(struct librpma_fio_mem *mem)
{
	if (mem->size_mmap) {
#ifdef CONFIG_LIBPMEM2_INSTALLED
		pmem2_map_delete(&mem->map);
		pmem2_config_delete(&mem->cfg);
		pmem2_source_delete(&mem->src);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	} else {
		free(mem->mem_ptr);
	}
}

```


<!-- Sent from Reviewable.io -->

2022-03-08 12:37 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.h, line 23 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPUrrBoiVqpbka0jI:-MxdXCSP2JhpQYXJrIwt:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```#ifdef CONFIG_LIBPMEM2_INSTALLED``` is needed to avoid a compilation error.
</blockquote></details>

+1
___
*[engines/librpma_fio.h, line 78 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPyzB9z79_l0MLBeZ:-MxdXF-A5WnXHVyyGGBg:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L78)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```#ifdef CONFIG_LIBPMEM2_INSTALLED``` is needed to avoid a compilation error.
</blockquote></details>

+1
___
*[engines/librpma_fio.h, line 79 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPuwFAVj0q_7zhe5s:-MxdXGlRBGb1bQSHrRaV:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L79)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```#ifdef CONFIG_LIBPMEM2_INSTALLED``` is needed to avoid a compilation error.
</blockquote></details>

+1
___
*[engines/librpma_fio.h, line 80 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdQ-ad7qBzBtjpV9va:-MxdXHUtARIKkudQKhTW:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```#ifdef CONFIG_LIBPMEM2_INSTALLED``` is needed to avoid a compilation error.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-03-08 14:47 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.c, line 213 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcSiyi7kgNLOId7DTq:-MxdzsOj8Z7bWVLzKbtu:b-rndg5u) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, I have asked @haichangsi to do so: https://github.com/pmem/fio/pull/269#pullrequestreview-901331339

In my opinion it is more important to keep code clear and readable than removing such small redundancy.
</blockquote></details>

OK, let's try to do it as we have discussed offline.


<!-- Sent from Reviewable.io -->

2022-03-09 08:22 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.h, line 78 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPyzB9z79_l0MLBeZ:-Mxhk8wyEWfQMrtKQPRc:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

+1
___
*[engines/librpma_fio.h, line 79 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPuwFAVj0q_7zhe5s:-Mxhk9wPENZecMQdOkOx:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L79)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

+1
___
*[engines/librpma_fio.h, line 80 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdQ-ad7qBzBtjpV9va:-MxhkBN1DDRuPulYtVl8:b32v57) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

+1
___
*[engines/librpma_fio.c, line 213 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcSiyi7kgNLOId7DTq:-MxhkoKE6zYHPwlw9Q-U:b-d2o654) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, let's try to do it as we have discussed offline.
</blockquote></details>

```
static char* librpma_fio_pmem2_map_file(struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem, size_t ws_offset)
{
	size_t size_mmap;
	char *mem_ptr = NULL;

	int fd;
	struct pmem2_config *cfg = NULL;
	struct pmem2_map *map = NULL;
	struct pmem2_source *src = NULL;


	if((fd = open(f->file_name, O_RDWR)) < 0) {
		log_err("fio: cannot open fio file\n");
		return -1;
	}

	if (pmem2_source_from_fd(&src, fd) != 0) {
		log_err("fio: pmem2_source_from_fd() failed");
		goto err_close;
	}

	if (pmem2_config_new(&cfg) != 0) {
		log_err("fio: pmem2_config_new() failed");
		goto err_source_delete;
	}

	if (pmem2_config_set_required_store_granularity(cfg,
					 PMEM2_GRANULARITY_CACHE_LINE) != 0) {
		log_err("fio: pmem2_config_set_required_store_granularity() failed");
		goto err_config_delete;
	}

	if (pmem2_map_new(&map, cfg, src) != 0) {
		log_err("fio: pmem2_map_new(%s) failed\n", f->file_name);
		goto err_config_delete;
	}

	size_mmap = pmem2_map_get_size(map);

	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			f->file_name, size_mmap, ws_offset + size);
		goto err_map_delete;
	}

	log_info("fio: size of memory mapped from the file %s: %zu\n",
		f->file_name, size_mmap);

	mem->mem_ptr = pmem2_map_get_address(map);
	mem->size_mmap = size_mmap;
	mem->map = map;
//	mem->cfg = cfg;
//	mem->src = src;
	pmem2_config_delete(&cfg);
	pmem2_source_delete(&src);
	close(fd);

	return mem->mem_ptr;

err_map_delete:
	pmem2_map_delete(&map);
err_config_delete:
	pmem2_config_delete(&cfg);
err_source_delete:
	pmem2_source_delete(&src);
err_close:
	close(fd);

	return NULL;

}

static char* librpma_fio_pmem_map_file(struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem, size_t ws_offset)
{
	size_t size_mmap;
	char *mem_ptr = NULL;

	/* map the file */
	mem_ptr = pmem_map_file(f->file_name, 0 /* len */, 0 /* flags */,
			0 /* mode */, &size_mmap, &is_pmem);
	if (mem_ptr == NULL) {
		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
		/* pmem_map_file() sets errno on failure */
		td_verror(td, errno, "pmem_map_file");
		return NULL;
	}

	/* pmem is expected */
	if (!is_pmem) {
		log_err("fio: %s is not located in persistent memory\n",
			f->file_name);
		goto err_unmap;
	}

	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			f->file_name, size_mmap, ws_offset + size);
		goto err_unmap;
	}

	log_info("fio: size of memory mapped from the file %s: %zu\n",
		f->file_name, size_mmap);

	mem->mem_ptr = mem_ptr;
	mem->size_mmap = size_mmap;
	return mem_ptr;

err_unmap:
	(void) pmem_unmap(mem_ptr, size_mmap);
	return NULL;
}

char *librpma_fio_allocate_pmem(struct thread_data *td, struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem)
{
	size_t size_mmap;
	size_t ws_offset;
	char *mem_ptr = NULL;

	if (size % page_size) {
		log_err("fio: size (%zu) is not aligned to page size (%zu)\n",
			size, page_size);
		return NULL;
	}

	if (f->filetype == FIO_TYPE_CHAR) {
		/* Each thread uses a separate offset within DeviceDAX. */
		ws_offset = (td->thread_number - 1) * size;
	} else {
		/* Each thread uses a separate FileSystemDAX file. No offset is needed. */
		ws_offset = 0;
	}

	if (!f->file_name) {
		log_err("fio: filename is not set\n");
		return NULL;
	}

#ifdef CONFIG_LIBPMEM2_INSTALLED
	mem_ptr = librpma_fio_pmem2_map_file(f, size, mem, ws_offset);
#else
	mem_ptr = librpma_fio_pmem_map_file(f, size, mem, ws_offset);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	return mem_ptr!=NULL?mem_ptr + ws_offset:NULL;
}
```
___
*[engines/librpma_fio.c, line 287 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcS7DU5IEH65fC5H_H:-Mxhl4uLDmIGbXpLIiMT:bihfkqq) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L287)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, we can do that in this way:

```c
void librpma_fio_free(struct librpma_fio_mem *mem)
{
	if (mem->size_mmap) {
#ifdef CONFIG_LIBPMEM2_INSTALLED
		pmem2_map_delete(&mem->map);
		pmem2_config_delete(&mem->cfg);
		pmem2_source_delete(&mem->src);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	} else {
		free(mem->mem_ptr);
	}
}

```
</blockquote></details>

According to @lplewa both cfg and src can be removed just after mapping creation, so we have only these two lines here :
```
#ifdef CONFIG_LIBPMEM2_INSTALLED
		pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```


<!-- Sent from Reviewable.io -->

2022-03-09 13:13 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[Makefile, line 114 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcMFLg8_tnrN4GY52D:-MxidYphCnhiG8AZ2VEX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/Makefile#L114)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right, it will not work. It should be replaced with:

```
  ifdef CONFIG_LIBPMEM2_INSTALLED
    librpma_apm_LIBS = -lrpma -lpmem2
  else
    librpma_apm_LIBS = -lrpma -lpmem
  endif
```
</blockquote></details>

Done.
___
*[Makefile, line 120 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdLdiS-aBLRzF5ZyWa:-MxidcwnDZPuS6gUnGvQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/Makefile#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
  ifdef CONFIG_LIBPMEM2_INSTALLED
    librpma_gpspm_LIBS = -lrpma -lpmem2 -lprotobuf-c
  else
    librpma_gpspm_LIBS = -lrpma -lpmem -lprotobuf-c
  endif
```

</blockquote></details>

Done.
___
*[options.c, line 2130 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcNQBf7KCXcnrPO8Kw:-Mxidmge3JL5YGkvbgkX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/options.c#L2130)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 23 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPUrrBoiVqpbka0jI:-MxieuFW30Js-mBxYV1k:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 78 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdMCs_6Xst30dSGMVM:-Mxiew2z7c0txVJv3EjQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L78)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this all the time?
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 78 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPyzB9z79_l0MLBeZ:-Mxif29fAw6oFgn2Qa8i:bb9tff5) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L78)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

It is not needed all the time, I removed it. Done.
___
*[engines/librpma_fio.h, line 79 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdPuwFAVj0q_7zhe5s:-MxifFlD3vMJ87oCADNv:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L79)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 80 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdQ-ad7qBzBtjpV9va:-MxifGg_-_bhE1mkGoXb:b68cb9n) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.h#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

.
Done.
___
*[engines/librpma_fio.c, line 168 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdEhYF1uQ5IK5wBoqA:-MxilrO173X1aFI2aBrL:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L168)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Please use pmem2_errormsg(), to log detailed error
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 213 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcSiyi7kgNLOId7DTq:-MxilxlP2PnDVm86o5Xu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L213)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
static char* librpma_fio_pmem2_map_file(struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem, size_t ws_offset)
{
	size_t size_mmap;
	char *mem_ptr = NULL;

	int fd;
	struct pmem2_config *cfg = NULL;
	struct pmem2_map *map = NULL;
	struct pmem2_source *src = NULL;


	if((fd = open(f->file_name, O_RDWR)) < 0) {
		log_err("fio: cannot open fio file\n");
		return -1;
	}

	if (pmem2_source_from_fd(&src, fd) != 0) {
		log_err("fio: pmem2_source_from_fd() failed");
		goto err_close;
	}

	if (pmem2_config_new(&cfg) != 0) {
		log_err("fio: pmem2_config_new() failed");
		goto err_source_delete;
	}

	if (pmem2_config_set_required_store_granularity(cfg,
					 PMEM2_GRANULARITY_CACHE_LINE) != 0) {
		log_err("fio: pmem2_config_set_required_store_granularity() failed");
		goto err_config_delete;
	}

	if (pmem2_map_new(&map, cfg, src) != 0) {
		log_err("fio: pmem2_map_new(%s) failed\n", f->file_name);
		goto err_config_delete;
	}

	size_mmap = pmem2_map_get_size(map);

	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			f->file_name, size_mmap, ws_offset + size);
		goto err_map_delete;
	}

	log_info("fio: size of memory mapped from the file %s: %zu\n",
		f->file_name, size_mmap);

	mem->mem_ptr = pmem2_map_get_address(map);
	mem->size_mmap = size_mmap;
	mem->map = map;
//	mem->cfg = cfg;
//	mem->src = src;
	pmem2_config_delete(&cfg);
	pmem2_source_delete(&src);
	close(fd);

	return mem->mem_ptr;

err_map_delete:
	pmem2_map_delete(&map);
err_config_delete:
	pmem2_config_delete(&cfg);
err_source_delete:
	pmem2_source_delete(&src);
err_close:
	close(fd);

	return NULL;

}

static char* librpma_fio_pmem_map_file(struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem, size_t ws_offset)
{
	size_t size_mmap;
	char *mem_ptr = NULL;

	/* map the file */
	mem_ptr = pmem_map_file(f->file_name, 0 /* len */, 0 /* flags */,
			0 /* mode */, &size_mmap, &is_pmem);
	if (mem_ptr == NULL) {
		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
		/* pmem_map_file() sets errno on failure */
		td_verror(td, errno, "pmem_map_file");
		return NULL;
	}

	/* pmem is expected */
	if (!is_pmem) {
		log_err("fio: %s is not located in persistent memory\n",
			f->file_name);
		goto err_unmap;
	}

	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			f->file_name, size_mmap, ws_offset + size);
		goto err_unmap;
	}

	log_info("fio: size of memory mapped from the file %s: %zu\n",
		f->file_name, size_mmap);

	mem->mem_ptr = mem_ptr;
	mem->size_mmap = size_mmap;
	return mem_ptr;

err_unmap:
	(void) pmem_unmap(mem_ptr, size_mmap);
	return NULL;
}

char *librpma_fio_allocate_pmem(struct thread_data *td, struct fio_file *f,
		size_t size, struct librpma_fio_mem *mem)
{
	size_t size_mmap;
	size_t ws_offset;
	char *mem_ptr = NULL;

	if (size % page_size) {
		log_err("fio: size (%zu) is not aligned to page size (%zu)\n",
			size, page_size);
		return NULL;
	}

	if (f->filetype == FIO_TYPE_CHAR) {
		/* Each thread uses a separate offset within DeviceDAX. */
		ws_offset = (td->thread_number - 1) * size;
	} else {
		/* Each thread uses a separate FileSystemDAX file. No offset is needed. */
		ws_offset = 0;
	}

	if (!f->file_name) {
		log_err("fio: filename is not set\n");
		return NULL;
	}

#ifdef CONFIG_LIBPMEM2_INSTALLED
	mem_ptr = librpma_fio_pmem2_map_file(f, size, mem, ws_offset);
#else
	mem_ptr = librpma_fio_pmem_map_file(f, size, mem, ws_offset);
#endif /* CONFIG_LIBPMEM2_INSTALLED [...]

2022-03-09 13:13 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 3 of 7 files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 146 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdVJeHAAxXiSZIBvtP:-Mxio5244vborK7zRNe_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L146)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wrong indentation
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 163 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdEZxfAc6o_gCoYjSn:-Mxio6Q65fzEEQw-Lb2M:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L163)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Please use pmem2_errormsg(), to log detailed error
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-09 13:35 UTC, grom72 reviewed
> Reviewed 2 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 5 of 7 files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.h, line 90 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxisreK66_3TW-cbNxi:-MxisreK66_3TW-cbNxj:b-sfh4ef) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.h#L90)):*
> ```objc
> 		struct librpma_fio_mem *mem);
> 
> static char* librpma_fio_pmem2_map_file(struct fio_file *f, size_t size,
> ```

we should not put static function declaration in *.h file



_Code quote:_
```objc
static char* librpma_fio_pmem2_map_file(struct fio_file *f, size_t size,
		struct librpma_fio_mem *mem, size_t ws_offset);

static char* librpma_fio_pmem_map_file(struct thread_data *td,
		struct fio_file *f, size_t size, struct librpma_fio_mem *mem,
		size_t ws_offset);
```


<!-- Sent from Reviewable.io -->

2022-03-09 13:43 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 5 of 7 files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 140 at r15](https://reviewable.io/reviews/pmem/fio/269#-Mxit7C52YIX-Z6VggUG:-Mxit7C52YIX-Z6VggUH:b-604rjn) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L140)):*
> ```C
> 	if (pmem2_config_set_required_store_granularity(cfg,
> 					PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 		log_err("fio: pmem2_config_set_required_store_granularity() failed: %s", pmem2_errormsg());
> ```

do we need ````\n```` at the end of the error message?
___
*[engines/librpma_fio.c, line 271 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiteKx0nwBt7SZevy3:-MxiteKx0nwBt7SZevy4:b7ln91s) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L271)):*
> ```C
> 		pmem2_map_delete(&mem->map);
> 	} else {
> 		free(mem->mem_ptr);
> ```

```
{
	if (mem->size_mmap)
#ifdef CONFIG_LIBPMEM2_INSTALLED
		pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	else
		free(mem->mem_ptr);
}
```



_Suggestion:_
```C
#ifdef CONFIG_LIBPMEM2_INSTALLED
{
	if (mem->size_mmap) {
		pmem2_map_delete(&mem->map);


	} else {
		free(mem->mem_ptr);
	}
}
#else
{
	if (mem->size_mmap)
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
	else
		free(mem->mem_ptr);
}
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```


<!-- Sent from Reviewable.io -->

2022-03-09 13:52 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 7 files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-MxivH9AB4LBVg-0z8T2:b-gwnvd1) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
> ```C
> }
> 
> static char* librpma_fio_pmem2_map_file(struct fio_file *f, size_t size,
> ```

```
#ifdef CONFIG_LIBPMEM2_INSTALLED
static char* librpma_fio_pmem2_map_file
...
#else
...
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```




_Code quote:_
```C
static char* librpma_fio_pmem2_map_file
```
___
*[engines/librpma_fio.c, line 159 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiwFPO5CNgL8x6XITS:-MxiwFPO5CNgL8x6XITT:b-ksbjf3) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L159)):*
> ```C
> 	}
> 
> 	log_info("fio: size of memory mapped from the file %s: %zu\n",
> ```

please move this to ```librpma_fio_allocate_pmem``` and also remove similar code from ```librpma_fio_pmem_map_file```



_Code quote:_
```C
	log_info("fio: size of memory mapped from the file %s: %zu\n",
		f->file_name, size_mmap);
```
___
*[engines/librpma_fio.c, line 183 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivU_S2c5D48SEP6gw:-MxivU_S2c5D48SEP6gx:btvzfl1) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L183)):*
> ```C
> }
> 
> static char* librpma_fio_pmem_map_file(struct thread_data *td, 
> ```

.
see above - this should only be included if no pmem2



_Code quote:_
```C
static char* librpma_fio_pmem_map_file
```
___
*[engines/librpma_fio.c, line 183 at r15](https://reviewable.io/reviews/pmem/fio/269#-Mxivlgv5xUlsljV_gp2:-Mxivlgv5xUlsljV_gp3:b-kv5cr9) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L183)):*
> ```C
> }
> 
> static char* librpma_fio_pmem_map_file(struct thread_data *td, 
> ```

Is td needed?



_Code quote:_
```C
struct thread_data *td
```
___
*[engines/librpma_fio.c, line 187 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiwiZQCpDTs8ykZf1Y:-MxiwiZQCpDTs8ykZf1Z:b-4wjo6n) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L187)):*
> ```C
> 		size_t ws_offset)
> {
> 	char *mem_ptr = NULL;
> ```

we do not need such variable in ```librpma_fio_pmem2_map_file``` please unify in either direction.



_Code quote:_
```C
char *mem_ptr = NULL;
```


<!-- Sent from Reviewable.io -->

2022-03-09 15:59 UTC, lplewa reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-MxjJIPm2gHRLe2GoWVz:bxvpcvz) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
#ifdef CONFIG_LIBPMEM2_INSTALLED
static char* librpma_fio_pmem2_map_file
...
#else
...
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```

</blockquote></details>

+1 

buuuuuuut this is ugly. 

A better idea is to move libpmem and libpmem2 implementation to separate files and conditionally add one of those files to compilation.                                                                          
___
*[engines/librpma_fio.c, line 140 at r15](https://reviewable.io/reviews/pmem/fio/269#-Mxit7C52YIX-Z6VggUG:-MxjHbAn-Q6j7m1HdAFN:b6ym4ve) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L140)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we need ````\n```` at the end of the error message?
</blockquote></details>

imho yes. pmem2_errormsg() returns \0 terminated string


<!-- Sent from Reviewable.io -->

2022-03-09 17:31 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @lplewa)

___
*[engines/librpma_fio.h, line 90 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxisreK66_3TW-cbNxi:-MxjiSlUD9kuwsinm7sK:b2ni8o8) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.h#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Are they necessary at all ?
</blockquote></details>

no.
___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-MxjigZT7CHTmwN6R3tk:b-4v2qs4) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

+1 

buuuuuuut this is ugly. 

A better idea is to move libpmem and libpmem2 implementation to separate files and conditionally add one of those files to compilation.                                                                          
</blockquote></details>

good idea to have common function name but different implementation depends on libpmem2
___
*[options.c, line 2130 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcNQBf7KCXcnrPO8Kw:-Mxjj159-cVUKp6hWA6s:b32wtd) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/options.c#L2130)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-03-09 21:32 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi and @lplewa)

___
*[engines/librpma_fio.h, line 90 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxisreK66_3TW-cbNxi:-MxkZZF9D71TFp9zBgA-:b-wd1kr7) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.h#L90)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

no.
</blockquote></details>

I think so, @haichangsi please remove them.
___
*[engines/librpma_fio.c, line 287 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxcS7DU5IEH65fC5H_H:-Mxk_cp-4DnrGjbb_lFu:behr82w) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L287)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet:
```c
{
	if (mem->size_mmap)
#ifdef CONFIG_LIBPMEM2_INSTALLED
		pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	else
		free(mem->mem_ptr);
}
```
___
*[engines/librpma_fio.c, line 22 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxkZ4cS8bFLnWfjgIIe:-MxkZ4cS8bFLnWfjgIIf:b-pp4w9n) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L22)):*
> ```C
> #include <libpmem.h>
> #endif /* CONFIG_LIBPMEM2_INSTALLED */
> struct fio_option librpma_fio_options[] = {
> ```

one empty line in between, please



_Code quote:_
```C
#endif /* CONFIG_LIBPMEM2_INSTALLED */


struct fio_option librpma_fio_options[] = {
```


<!-- Sent from Reviewable.io -->

2022-03-10 09:29 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_fio.h, line 90 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxisreK66_3TW-cbNxi:-MxmvlYj2JpTAZppVGC_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.h#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think so, @haichangsi please remove them.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 233 at r14](https://reviewable.io/reviews/pmem/fio/269#-MxdVP273z1nGDPszxFo:-Mxn3GrX6DNu0fuVwhj_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f0711d72fc756c1ee77a697b8282407be1bc51df/engines/librpma_fio.c#L233)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 22 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxkZ4cS8bFLnWfjgIIe:-MxmvxXI0TYySKW90ZYX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one empty line in between, please
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-Mxn6ibcDTCdEHCvW9G2:b-9swi09) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

good idea to have common function name but different implementation depends on libpmem2
</blockquote></details>

So one common function librpma_fio_X_map_file() with ifdef, right?
___
*[engines/librpma_fio.c, line 159 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiwFPO5CNgL8x6XITS:-Mxn1z1P2fI1j2bRV5VE:bfixjap) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L159)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

please move this to ```librpma_fio_allocate_pmem``` and also remove similar code from ```librpma_fio_pmem_map_file```
</blockquote></details>

I have to move it after ifdef because size_mmap is set during maping. Done.
___
*[engines/librpma_fio.c, line 183 at r15](https://reviewable.io/reviews/pmem/fio/269#-Mxivlgv5xUlsljV_gp2:-Mxn3m1V1y_2WZClzui0:b-z357z4) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L183)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is td needed?
</blockquote></details>

It is (for td_verror())
___
*[engines/librpma_fio.c, line 183 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivU_S2c5D48SEP6gw:-Mxn6ugw7afi0MHSdXCN:b-jrjab1) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L183)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
see above - this should only be included if no pmem2
</blockquote></details>

So one common function librpma_fio_X_map_file() with ifdef, right?
___
*[engines/librpma_fio.c, line 187 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiwiZQCpDTs8ykZf1Y:-Mxn3Hys5i7ZvZdrG6v5:b-ky0zl5) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L187)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we do not need such variable in ```librpma_fio_pmem2_map_file``` please unify in either direction.
</blockquote></details>

There is no such a variable in librpma_fio_pmem2_map_file. I don't understand what do you mean
___
*[engines/librpma_fio.c, line 271 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiteKx0nwBt7SZevy3:-Mxn7dGG7fWnLvQNKDNE:blnro1h) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L271)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
{
	if (mem->size_mmap)
#ifdef CONFIG_LIBPMEM2_INSTALLED
		pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	else
		free(mem->mem_ptr);
}
```
</blockquote></details>

Done. @ldorau ?


<!-- Sent from Reviewable.io -->

2022-03-10 10:17 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-10 10:17 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_fio.c, line 187 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiwiZQCpDTs8ykZf1Y:-MxnH34LCzveKZW3c1V8:b-1934jd) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L187)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

There is no such a variable in librpma_fio_pmem2_map_file. I don't understand what do you mean
</blockquote></details>

mem->mem_ptr is used in librpma_fio_pmem2_map_file which is equivalent to mem_ptr here
there are some differences between pmem and pmem2 but the final logic is the same. So let's try to implement the same things the same way.
___
*[engines/librpma_fio.c, line 267 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnHcjQEVE9V-E8m8nR:-MxnHcjQEVE9V-E8m8nS:bfmrmr8) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L267)):*
> ```C
> void librpma_fio_free(struct librpma_fio_mem *mem)
> {
> 	if (mem->size_mmap) {
> ```

```	if (mem->size_mmap)```
without ```{```



_Code quote:_
```C
	if (mem->size_mmap) {
```
___
*[engines/librpma_fio.c, line 273 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnHh3OAYHQ1q19aU7X:-MxnHh3OAYHQ1q19aU7Y:b-a8l5ne) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L273)):*
> ```C
> 	(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
> #endif /* CONFIG_LIBPMEM2_INSTALLED */
> }
> ```

without ```}```



_Code quote:_
```C
}
```


<!-- Sent from Reviewable.io -->

2022-03-10 10:57 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 271 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiteKx0nwBt7SZevy3:-MxnTX0v0EQ3DxOsWzh9:b-8dy1ey) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L271)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done. @ldorau ?
</blockquote></details>

See my new comments
___
*[engines/librpma_fio.c, line 267 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnTNxMEFlXTzvkWWlw:-MxnTNxNBMwXsS4ZMX0J:b-lsi64q) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L267)):*
> ```C
> void librpma_fio_free(struct librpma_fio_mem *mem)
> {
> 	if (mem->size_mmap) {
> ```

```c
{
	if (mem->size_mmap)
#ifdef CONFIG_LIBPMEM2_INSTALLED
		(void) pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	else
		free(mem->mem_ptr);
}
```



_Code quote:_
```C

	if (mem->size_mmap) {
#ifdef CONFIG_LIBPMEM2_INSTALLED
	pmem2_map_delete(&mem->map);




#else


	(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
}
	else
		free(mem->mem_ptr);
}
```
___
*[engines/librpma_fio.c, line 269 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnSLt85zknaZ5gVUcc:-MxnSLt85zknaZ5gVUcd:batv3ox) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L269)):*
> ```C
> 	if (mem->size_mmap) {
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> 	pmem2_map_delete(&mem->map);
> ```

wrong indentation



_Code quote:_
```C
	pmem2_map_delete(&mem->map);
```
___
*[engines/librpma_fio.c, line 269 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnT0Hd3Y27PxQvFsze:-MxnT0Hd3Y27PxQvFszf:b-2slf0z) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L269)):*
> ```C
> 	if (mem->size_mmap) {
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> 	pmem2_map_delete(&mem->map);
> ```

```c
(void) pmem2_map_delete(&mem->map);
```



_Code quote:_
```C
pmem2_map_delete(&mem->map);
```
___
*[engines/librpma_fio.c, line 271 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnSWdH8D5pYZQAngHw:-MxnSWdH8D5pYZQAngHx:batv3ox) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L271)):*
> ```C
> 	pmem2_map_delete(&mem->map);
> #else
> 	(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
> ```

wrong indentation



_Code quote:_
```C
	(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
```


<!-- Sent from Reviewable.io -->

2022-03-10 16:57 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[engines/librpma_fio.c, line 267 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnTNxMEFlXTzvkWWlw:-MxoiKDI75ZuQPCBZ252:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L267)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
{
	if (mem->size_mmap)
#ifdef CONFIG_LIBPMEM2_INSTALLED
		(void) pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
	else
		free(mem->mem_ptr);
}
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 269 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnSLt85zknaZ5gVUcc:-Mxohzuu8hQbz4bzIoJI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L269)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 269 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnT0Hd3Y27PxQvFsze:-Mxoi-PX7xGsbhphFyAQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L269)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
(void) pmem2_map_delete(&mem->map);
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 271 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnSWdH8D5pYZQAngHw:-Mxoi0zsA01BVUVjysnK:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L271)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 273 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnHh3OAYHQ1q19aU7X:-Mxoi1j_BQtTBK12N4ri:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L273)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

without ```}```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-10 17:05 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_fio.c, line 187 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxiwiZQCpDTs8ykZf1Y:-Mxomapz7C4aaLaHUtzU:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L187)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

mem->mem_ptr is used in librpma_fio_pmem2_map_file which is equivalent to mem_ptr here
there are some differences between pmem and pmem2 but the final logic is the same. So let's try to implement the same things the same way.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 267 at r16](https://reviewable.io/reviews/pmem/fio/269#-MxnHcjQEVE9V-E8m8nR:-Mxoma9P9EcEm7fUNyeZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cf93a3b4bc04cef9fa9b21fbb3da07dd02ce3a90/engines/librpma_fio.c#L267)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```	if (mem->size_mmap)```
without ```{```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-11 07:51 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-MxrwhjA3dW6soNe84gX:b2r4920) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

IMHO one function to map, second to clean up. Instead of ifdef put them in separate files and add only one to compilation based if libpmem, . 
And have a common header for those c files. 
Doing so you have a cleaner code (multiple #ifdefs in the code is not a "clean" code). 

```
librpma_fio_common.h
struct librpma_map {
        void *addr;
        size_t size;
        int is_pmem;
        char reserved[LIBRPMA_reserved];/* extra space to keep implementation specific meta data, like pmem2_map structure, can be here expisite defined*/
}


struct librpma_map *librpma_fio_map_file(...)
void librpmem_fio *librpma_fio_unmap(struct librpma_map *map); 
```

(btw this is only my proposal, consult with @ldorau and @grom72 before implementing this idea)
</blockquote></details>

I do not want to define additional files as this is not our project and rpma fio engine has already introduced several files instead of 1-2 like it is in the case of other engines.
___
*[engines/librpma_fio.c, line 269 at r18](https://reviewable.io/reviews/pmem/fio/269#-Mxrx9Vl2nr6vDz2LfSx:-Mxrx9Vl2nr6vDz2LfSy:b-dofcql) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/engines/librpma_fio.c#L269)):*
> ```C
> void librpma_fio_free(struct librpma_fio_mem *mem)
> {
> 	if (mem->size_mmap) 
> ```

remove white characters ```  ``` at the end of the line



_Code quote:_
```C
if (mem->size_mmap)··
```


<!-- Sent from Reviewable.io -->

2022-03-11 08:03 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-MxrxlcF7gLtIvj5NUy9:bdzab6u) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I do not want to define additional files as this is not our project and rpma fio engine has already introduced several files instead of 1-2 like it is in the case of other engines.
</blockquote></details>

so finally let's do as @ldorau proposed:
```
static char* librpma_fio_pmem_map_file(struct thread_data *td,
		struct fio_file *f, size_t size, struct librpma_fio_mem *mem,
		size_t ws_offset)
{
// any common part is here
mem->mem_ptr = NULL;
#ifdef CONFIG_LIBPMEM2_INSTALLED
...
#else
...
#endif /* CONFIG_LIBPMEM2_INSTALLED */
}
```
___
*[engines/librpma_fio.c, line 197 at r18](https://reviewable.io/reviews/pmem/fio/269#-Mxs-2PV5QciX3hB-eZ7:-Mxs-2PV5QciX3hB-eZ8:b-1t1sj4) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/engines/librpma_fio.c#L197)):*
> ```C
> 		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
> 		/* pmem_map_file() sets errno on failure */
> 		td_verror(td, errno, "pmem_map_file");
> ```

do we know what is an added value of using ```td_verror()``` together with ```log_err()```?



_Code quote:_
```C
td_verror(td, errno, "pmem_map_file");
```


<!-- Sent from Reviewable.io -->

2022-03-11 10:10 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MxsSLCa0-hKdAn1bTlO:-MxsSLCbD6ywfZ6cDLb0:b-ski482) (no related file):*
The rpma code is not being built:
https://github.com/ldorau/fio/runs/5509204961?check_suite_focus=true

---


<!-- Sent from Reviewable.io -->

2022-03-11 10:43 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[configure, line 2953 at r18](https://reviewable.io/reviews/pmem/fio/269#-MxsZjf_4e-7N7xNgQ4X:-MxsZjf_4e-7N7xNgQ4Y:b-b6p0mj) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/configure#L2953)):*
> ```
> if test "$cpu" = "x86_64" -a "$libverbs" = "yes" -a "$rdmacm" = "yes" \
>     -a "$librpma" = "yes" \
>     -a ["$libpmem" = "yes" -o "$libpmem2" = "yes"] ; then
> ```

`&& test "$libpmem" = "yes" -o "$libpmem2" = "yes" ; then`



_Code quote:_
```
 -a ["$libpmem" = "yes" -o "$libpmem2" = "yes"] ; then
```
___
*[configure, line 2958 at r18](https://reviewable.io/reviews/pmem/fio/269#-MxsZv39B_w88Qj5Ngax:-MxsZv39B_w88Qj5Ngay:bxcy6sa) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/configure#L2958)):*
> ```
> if test "$cpu" = "x86_64" -a "$libverbs" = "yes" -a "$rdmacm" = "yes" \
>     -a "$librpma" = "yes" -a ["$libpmem" = "yes" -o "$libpmem2" = "yes"] \
>     -a "$libprotobuf_c" = "yes" ; then
> ```

```
    -a "$librpma" = "yes" -a "$libprotobuf_c" = "yes" \
    && test "$libpmem" = "yes" -o "$libpmem2" = "yes" ; then
```



_Code quote:_
```
    -a "$librpma" = "yes" -a ["$libpmem" = "yes" -o "$libpmem2" = "yes"] \
    -a "$libprotobuf_c" = "yes" ; then
```


<!-- Sent from Reviewable.io -->

2022-03-11 10:45 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MxsSLCa0-hKdAn1bTlO:-Mxs_Cxg8bysOG6BNlte:b-cue7q3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The rpma code is not being built:
https://github.com/ldorau/fio/runs/5509204961?check_suite_focus=true
</blockquote></details>

This PR requires https://github.com/pmem/fio/pull/284 to be merged before - please review ;-)

---


<!-- Sent from Reviewable.io -->

2022-03-11 11:03 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-Mxscjw54uJ6_lfHBcP5:b-2gjhxq) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

so finally let's do as @ldorau proposed:
```
static char* librpma_fio_pmem_map_file(struct thread_data *td,
		struct fio_file *f, size_t size, struct librpma_fio_mem *mem,
		size_t ws_offset)
{
// any common part is here
mem->mem_ptr = NULL;
#ifdef CONFIG_LIBPMEM2_INSTALLED
...
#else
...
#endif /* CONFIG_LIBPMEM2_INSTALLED */
}
```
</blockquote></details>

Add two separate header files: 
- librpma_fio_pmem1.h
- librpma_fio_pmem2.h
with libpmem and  libpmem2 static functions.


<!-- Sent from Reviewable.io -->

2022-03-11 12:58 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-Mxt2ecz1djGAM6ReTyF:bnb81mb) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add two separate header files: 
- librpma_fio_pmem1.h
- librpma_fio_pmem2.h
with libpmem and  libpmem2 static functions.
</blockquote></details>

@ldorau I propose librpma_fio_pmem.h instead of librpma_fio_pmem1.h


<!-- Sent from Reviewable.io -->

2022-03-11 13:35 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 113 at r15](https://reviewable.io/reviews/pmem/fio/269#-MxivH9AB4LBVg-0z8T1:-MxtBGEH-YcOZTGjGtH-:b32w0x) ([raw file](https://github.com/pmem/fio/blob/0928ef038af75e2e86b53fc14a9a87f15ad46826/engines/librpma_fio.c#L113)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau I propose librpma_fio_pmem.h instead of librpma_fio_pmem1.h
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2022-03-11 13:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MxsSLCa0-hKdAn1bTlO:-MxtBJGC9sJ8jox0qTxJ:bvxdmky) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This PR requires https://github.com/pmem/fio/pull/284 to be merged before - please review ;-)
</blockquote></details>

#284 has been merged, please rebase.

---


<!-- Sent from Reviewable.io -->

2022-03-11 20:16 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 197 at r18](https://reviewable.io/reviews/pmem/fio/269#-Mxs-2PV5QciX3hB-eZ7:-MxubGt559f_az8ztAzk:bskw9w9) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/engines/librpma_fio.c#L197)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we know what is an added value of using ```td_verror()``` together with ```log_err()```?
</blockquote></details>

td_verror is expanded to something similar to debug message:
"file:%s:%d, func=%s, error=%s", __FILE__, __LINE__, (func), (msg))
I do not see a point to use it here.
Q: Why do we use td_verror only in case of error indicated by  ```errno``` 
What is the difference between this type of error and other errors? 


<!-- Sent from Reviewable.io -->

2022-03-13 21:33 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MxsSLCa0-hKdAn1bTlO:-My4BB3qDN4SRjfjp4FT:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

#284 has been merged, please rebase.
</blockquote></details>

Done.

---
___
*[configure, line 2953 at r18](https://reviewable.io/reviews/pmem/fio/269#-MxsZjf_4e-7N7xNgQ4X:-My2KyE2DGbX2mVtzXby:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/configure#L2953)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`&& test "$libpmem" = "yes" -o "$libpmem2" = "yes" ; then`
</blockquote></details>

Done.
___
*[configure, line 2958 at r18](https://reviewable.io/reviews/pmem/fio/269#-MxsZv39B_w88Qj5Ngax:-My2LWFtCdVLAIybcih5:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/configure#L2958)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
    -a "$librpma" = "yes" -a "$libprotobuf_c" = "yes" \
    && test "$libpmem" = "yes" -o "$libpmem2" = "yes" ; then
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 197 at r18](https://reviewable.io/reviews/pmem/fio/269#-Mxs-2PV5QciX3hB-eZ7:-My4BKeh7E7QuGx9fYfl:bha26zf) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/engines/librpma_fio.c#L197)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

td_verror is expanded to something similar to debug message:
"file:%s:%d, func=%s, error=%s", __FILE__, __LINE__, (func), (msg))
I do not see a point to use it here.
Q: Why do we use td_verror only in case of error indicated by  ```errno``` 
What is the difference between this type of error and other errors? 


</blockquote></details>

@ldorau wanted to leave it the way it is rn and so I did. Do you want me to change it?
___
*[engines/librpma_fio.c, line 269 at r18](https://reviewable.io/reviews/pmem/fio/269#-Mxrx9Vl2nr6vDz2LfSx:-My2MK7p-IsoXCV-0wZI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/engines/librpma_fio.c#L269)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

remove white characters ```  ``` at the end of the line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-14 07:03 UTC, grom72 reviewed
> Reviewed 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_fio.c, line 141 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CxHc9aLmndCxooOt:-My6CxHc9aLmndCxooOu:bandwvj) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio.c#L141)):*
> ```C
> 	}
> 
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> ```

No #ifdef here - use the same function name in both cases. 
```mem->mem_ptr = librpma_fio_pmem_map_file(td, f, size, mem, ws_offset);```



_Code quote:_
```C
#ifdef CONFIG_LIBPMEM2_INSTALLED
	mem->mem_ptr = librpma_fio_pmem2_map_file(f, size, mem, ws_offset);
#else
	mem->mem_ptr = librpma_fio_pmem_map_file(td, f, size, mem, ws_offset);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```
___
*[engines/librpma_fio_pmem.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6Bph2-C6tKdb4Y6a1:-My6Bph2-C6tKdb4Y6a2:b-y8b3a5) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem.h#L21)):*
> ```objc
> #include <libpmem.h>
> 
> static char* librpma_fio_pmem_map_file(struct thread_data *td, 
> ```

```
static int librpma_fio_pmem_map_file(...
```
let's use ```-1``` as an error code and ```0``` as OK to avoid ```return mem->mem_ptr;```inside function 
and ```mem->mem_ptr = librpma_fio_pmem_map_file(td, f, size, mem, ws_offset);``` outside function.



_Code quote:_
```objc
static char* librpma_fio_pmem_map_file(
```
___
*[engines/librpma_fio_pmem.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6DyNBC6gxclXiZ7pr:-My6DyNBC6gxclXiZ7ps:b-5wmbbk) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem.h#L21)):*
> ```objc
> #include <libpmem.h>
> 
> static char* librpma_fio_pmem_map_file(struct thread_data *td, 
> ```

remove white chars at the end



_Code quote:_
```objc
static char* librpma_fio_pmem_map_file(struct thread_data *td,··
```
___
*[engines/librpma_fio_pmem2.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CdUf85pV-ju7CVjZ:-My6CdUf85pV-ju7CVj_:b-bbs0dg) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem2.h#L21)):*
> ```objc
> #include <libpmem2.h>
> 
> static char* librpma_fio_pmem2_map_file(struct fio_file *f, size_t size,
> ```

```librpma_fio_pmem_map_file``` common function name for both libpmem2 and libpmem.



_Code quote:_
```objc
librpma_fio_pmem2_map_file
```
___
*[engines/librpma_fio_pmem2.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6DVSo4nzXrCRT4BlP:-My6DVSo4nzXrCRT4BlQ:b9y8sdo) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem2.h#L21)):*
> ```objc
> #include <libpmem2.h>
> 
> static char* librpma_fio_pmem2_map_file(struct fio_file *f, size_t size,
> ```

```int librpma_fio_pmem_map_file(struct thread_data *td, struct fio_file *f, size_t size,....```
Same API for both cases.



_Code quote:_
```objc
static char* librpma_fio_pmem2_map_file(struct fio_file *f, size_t size,
```


<!-- Sent from Reviewable.io -->

2022-03-14 07:33 UTC, ldorau reviewed
> Reviewed 2 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.c, line 141 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CxHc9aLmndCxooOt:-My6L4bh64M_3iocLRJC:b32v57) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio.c#L141)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

No #ifdef here - use the same function name in both cases. 
```mem->mem_ptr = librpma_fio_pmem_map_file(td, f, size, mem, ws_offset);```

</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-03-14 11:30 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.c, line 197 at r18](https://reviewable.io/reviews/pmem/fio/269#-Mxs-2PV5QciX3hB-eZ7:-My7BLfY0xcrVW2rg5lP:b-iir02b) ([raw file](https://github.com/pmem/fio/blob/fe4c9711a8178be6c7f186dd496e5e91e7d9da40/engines/librpma_fio.c#L197)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

@ldorau wanted to leave it the way it is rn and so I did. Do you want me to change it?
</blockquote></details>

OK, let's remove `td_verror`:
```c
	if (mem->mem_ptr == NULL) {
		/* pmem_map_file() sets errno on failure */
		log_err("fio: pmem_map_file(%s) failed: %s (errno %i)\n",
			f->file_name, strerror(errno), errno);
		return NULL;
	}
```



_Code quote:_
```C
	if (mem->mem_ptr == NULL) {
		log_err("fio: pmem_map_file(%s) failed\n", f->file_name);
		/* pmem_map_file() sets errno on failure */
		td_verror(td, errno, "pmem_map_file");
		return NULL;
	}
```


<!-- Sent from Reviewable.io -->

2022-03-14 11:35 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.c, line 141 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CxHc9aLmndCxooOt:-My7CYaY-BK7wdC65RiJ:b-5p2rev) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

No `td`:
```c
	mem->mem_ptr = librpma_fio_pmem_map_file(f, size, mem, ws_offset);
```


<!-- Sent from Reviewable.io -->

2022-03-14 11:39 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.c, line 141 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CxHc9aLmndCxooOt:-My7CsbI5HAqdAtd5ozw:be2gdci) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No `td`:
```c
	mem->mem_ptr = librpma_fio_pmem_map_file(f, size, mem, ws_offset);
```

</blockquote></details>

Actually:
```c
	if (librpma_fio_pmem_map_file(f, size, mem, ws_offset)) {
		log_err("fio: librpma_fio_pmem_map_file(%s) failed\n",
			f->file_name);
		return NULL;
	}
```


<!-- Sent from Reviewable.io -->

2022-03-14 11:40 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_fio_pmem.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6Bph2-C6tKdb4Y6a1:-My7DXNeBHnoZSluzU7t:b32v57) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
static int librpma_fio_pmem_map_file(...
```
let's use ```-1``` as an error code and ```0``` as OK to avoid ```return mem->mem_ptr;```inside function 
and ```mem->mem_ptr = librpma_fio_pmem_map_file(td, f, size, mem, ws_offset);``` outside function.


</blockquote></details>

+1
___
*[engines/librpma_fio_pmem.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6DyNBC6gxclXiZ7pr:-My7DZ2tEekfuwfkVVZE:b32v57) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

remove white chars at the end
</blockquote></details>

+1
___
*[engines/librpma_fio_pmem2.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CdUf85pV-ju7CVjZ:-My7DaDH0JEl0ev4PwQy:b32v57) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem2.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```librpma_fio_pmem_map_file``` common function name for both libpmem2 and libpmem.
</blockquote></details>

+1
___
*[engines/librpma_fio_pmem2.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6DVSo4nzXrCRT4BlP:-My7Dbl69Bes-oSXDBsl:b32v57) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem2.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```int librpma_fio_pmem_map_file(struct thread_data *td, struct fio_file *f, size_t size,....```
Same API for both cases.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-03-14 11:41 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-03-14 11:54 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_fio.c, line 141 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CxHc9aLmndCxooOt:-My7GxPPBbqeNGgsQbxD:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Actually:
```c
	if (librpma_fio_pmem_map_file(f, size, mem, ws_offset)) {
		log_err("fio: librpma_fio_pmem_map_file(%s) failed\n",
			f->file_name);
		return NULL;
	}
```

</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6DyNBC6gxclXiZ7pr:-My7BwuH8yz3W4-vrpy1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

remove white chars at the end
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6Bph2-C6tKdb4Y6a1:-My7Gsav64gIQ31sD7_D:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem.h#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem2.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6CdUf85pV-ju7CVjZ:-My7BwH_BiRy-0AvWrR2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem2.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```librpma_fio_pmem_map_file``` common function name for both libpmem2 and libpmem.
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem2.h, line 21 at r19](https://reviewable.io/reviews/pmem/fio/269#-My6DVSo4nzXrCRT4BlP:-My7Bw5U7uGRzY0PK2d8:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0fb4e3f15ae2561e848d4ec2263b5cc3107f95ae/engines/librpma_fio_pmem2.h#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```int librpma_fio_pmem_map_file(struct thread_data *td, struct fio_file *f, size_t size,....```
Same API for both cases.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-14 12:20 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[engines/librpma_fio.h, line 82 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7Jdv26Hjbn59cDcoV:-My7Jdv368aBrAADQ6Ft:b-uns9ow) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio.h#L82)):*
> ```objc
> 
> 	/* libpmem2 structure used for mapping PMem */
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> ```

The comment inside ifdef:

```c
#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 structure used for mapping PMem */
	struct pmem2_map *map;
#endif
```



_Code quote:_
```objc
	/* libpmem2 structure used for mapping PMem */
#ifdef CONFIG_LIBPMEM2_INSTALLED
	struct pmem2_map *map;
#endif
```
___
*[engines/librpma_fio.c, line 18 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7KYYvDEAaAanqF24z:-My7KYYvDEAaAanqF25-:b-t62vnl) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio.c#L18)):*
> ```C
> #include "librpma_fio.h"
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> #include <libpmem2.h>
> ```

not needed, please remove



_Code quote:_
```C
#include <libpmem2.h>
```
___
*[engines/librpma_fio.c, line 21 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7Kf-M7OkH-9l3hiPQ:-My7Kf-N9n0vEy-oO2PR:b-t62vnl) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio.c#L21)):*
> ```C
> #include "librpma_fio_pmem2.h"
> #else
> #include <libpmem.h>
> ```

not needed, please remove



_Code quote:_
```C
#include <libpmem.h>
```
___
*[engines/librpma_fio_pmem.h, line 16 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7MktG2UJARQWiU8b-:-My7MktG2UJARQWiU8b0:b-t62vnl) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio_pmem.h#L16)):*
> ```objc
>  */
> 
> #include "../fio.h"
> ```

not needed, please remove



_Code quote:_
```objc
#include "../fio.h"

#include <librpma.h>
```
___
*[engines/librpma_fio_pmem2.h, line 18 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7MoKk0JbFVRy1BrVA:-My7MoKk0JbFVRy1BrVB:b-t62vnl) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio_pmem2.h#L18)):*
> ```objc
> #include "../fio.h"
> 
> #include <librpma.h>
> ```

not needed, please remove



_Code quote:_
```objc
#include "../fio.h"

#include <librpma.h>
```


<!-- Sent from Reviewable.io -->

2022-03-15 09:48 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-15 09:53 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-16 05:31 UTC, grom72 reviewed
> Reviewed 3 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-16 05:37 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MyGDbpb00_D-nknnzBR:-MyGDbpcDYb4aOpYUOj5:bha8rnn) (no related file):*
@ldorau Shall we add any message during  compilation or/and engine start saying what pmem version is used?

---
___
*[engines/librpma_fio.h, line 26 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGCoN5DxuOQbREj7Td:-MyGCoN5DxuOQbREj7Te:bxtub52) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L26)):*
> ```objc
> #include <libpmem2.h>
> #else
> #include <libpmem.h>
> ```

Is it needed?



_Code quote:_
```objc
#include <libpmem.h>
```
___
*[engines/librpma_fio.h, line 81 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGCugPEbch6sODqZ-x:-MyGCugPEbch6sODqZ-y:btt8wg0) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L81)):*
> ```objc
> 	size_t size_mmap;
> 
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> ```

@ldorau, what if we use a generic ```void *```` pointer here and map it to ```struct pmem2_map *``` inside ```librpma_fio_pmem2.h```?



_Code quote:_
```objc
#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 structure used for mapping PMem */
	struct pmem2_map *map;
#endif
```


<!-- Sent from Reviewable.io -->

2022-03-16 08:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MyGDbpb00_D-nknnzBR:-MyG_WiI3amgMigM2Ncg:bb9ojvv) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau Shall we add any message during  compilation or/and engine start saying what pmem version is used?
</blockquote></details>

We can.

---
___
*[engines/librpma_fio.h, line 26 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGCoN5DxuOQbREj7Td:-MyGX2r_6S0w7w80nleV:bufpkhp) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L26)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Right, it is not.

@haichangsi please remove it
___
*[engines/librpma_fio.h, line 81 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGCugPEbch6sODqZ-x:-MyGZqNRA2hVYF7h44rc:b9svqkh) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L81)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau, what if we use a generic ```void *```` pointer here and map it to ```struct pmem2_map *``` inside ```librpma_fio_pmem2.h```?
</blockquote></details>

It could be done, but what for? To avoid one ifdef? 
IMHO it is better to have more clear than more compact code.



_Code quote:_
```objc
CONFIG_LIBPMEM2_INSTALLED
```
___
*[engines/librpma_fio.c, line 144 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGkRUA90U9ZeoIcuJd:-MyGkRUA90U9ZeoIcuJe:bvtxmlf) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.c#L144)):*
> ```C
> 		return NULL;
> 	}
> ```

Please add here:
```c
	log_info("fio: library used to map PMem from file: %s\n", RPMA_PMEM_USED);
```
___
*[engines/librpma_fio.c, line 146 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGkM5b4wJHQhU0zFmR:-MyGkM5c3BcWr0QwLD7Y:batv3ox) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.c#L146)):*
> ```C
> 
> 	log_info("fio: size of memory mapped from the file %s: %zu\n",
> 	f->file_name, mem->size_mmap);
> ```

wrong indentation



_Code quote:_
```C
	f->file_name, mem->size_mmap);
```
___
*[engines/librpma_fio_pmem.h, line 17 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGjHbC2MEILz7e4vXM:-MyGjHbC2MEILz7e4vXN:b-2yh4x1) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio_pmem.h#L17)):*
> ```objc
> 
> #include <libpmem.h>
> ```

Please add info about the library used:

```c
#define RPMA_PMEM_USED "libpmem"
```
___
*[engines/librpma_fio_pmem2.h, line 17 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGk6518N9XsTclFe2j:-MyGk6518N9XsTclFe2k:bb55vob) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio_pmem2.h#L17)):*
> ```objc
> 
> #include <libpmem2.h>
> ```

Please add info about the library used:

```c
#define RPMA_PMEM_USED "libpmem2"
```


<!-- Sent from Reviewable.io -->

2022-03-16 08:12 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MyGDbpb00_D-nknnzBR:-MyGm6NpCaXeJ2hPxNYF:b-n3q0tl) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We can.
</blockquote></details>

I have added an issue for it in the code.

---


<!-- Sent from Reviewable.io -->

2022-03-16 11:45 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/269#-MyGDbpb00_D-nknnzBR:-MyHXWcZBOAFTQrZScx5:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have added an issue for it in the code.
</blockquote></details>

Done.

---
___
*[engines/librpma_fio.h, line 82 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7Jdv26Hjbn59cDcoV:-My7kMA8CpGmbTEBViJ_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio.h#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The comment inside ifdef:

```c
#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 structure used for mapping PMem */
	struct pmem2_map *map;
#endif
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 26 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGCoN5DxuOQbREj7Td:-MyHUkHd4rI7vfpOzQGX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right, it is not.

@haichangsi please remove it
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 18 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7KYYvDEAaAanqF24z:-My7k6q2BUrt0HESrXXb:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio.c#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed, please remove
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 21 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7Kf-M7OkH-9l3hiPQ:-My7k6dUBvaURBbgW8DU:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio.c#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed, please remove
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 144 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGkRUA90U9ZeoIcuJd:-MyHXToHEFOXVay0lzCi:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.c#L144)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add here:
```c
	log_info("fio: library used to map PMem from file: %s\n", RPMA_PMEM_USED);
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 146 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGkM5b4wJHQhU0zFmR:-MyHXL89BA5r5KNfLXg2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.c#L146)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem.h, line 16 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7MktG2UJARQWiU8b-:-My7k-ADD4m5r0z-1-RJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio_pmem.h#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed, please remove
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem.h, line 55 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7jFEX6pn7fjKv3nd8:-My7k58S69FbIjTv7Op-:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio_pmem.h#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

not needed as it is assigned already
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem.h, line 17 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGjHbC2MEILz7e4vXM:-MyHXEXC56TC910V5ggE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio_pmem.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add info about the library used:

```c
#define RPMA_PMEM_USED "libpmem"
```

</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem2.h, line 18 at r20](https://reviewable.io/reviews/pmem/fio/269#-My7MoKk0JbFVRy1BrVA:-MyBqFdDBrP3SACGFe7m:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22dabf2e441cbbda9c43f4b69dad32dc9850b8fb/engines/librpma_fio_pmem2.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed, please remove
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem2.h, line 17 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGk6518N9XsTclFe2j:-MyHXDgg1GXDiL8HN0oR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio_pmem2.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add info about the library used:

```c
#define RPMA_PMEM_USED "libpmem2"
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 10:45 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[engines/librpma_fio.h, line 24 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyMTHA-6VSECNeiROmz:-MyMTHA-6VSECNeiROn-:b-z20h5r) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L24)):*
> ```objc
> #include <librpma.h>
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> #include <libpmem2.h>
> ```

how can it be removed if we use ```struct pmem2_map *map;``` below?



_Code quote:_
```objc
#include <libpmem2.h>
```
___
*[engines/librpma_fio.h, line 81 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyGCugPEbch6sODqZ-x:-MyMThhbDA9EcV0v_9th:baumdle) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It could be done, but what for? To avoid one ifdef? 
IMHO it is better to have more clear than more compact code.
</blockquote></details>

we need at least two ifdef
one here and one for ```#include <libpmem2.h>```


<!-- Sent from Reviewable.io -->

2022-03-17 10:46 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-17 11:03 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r23.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269#-:-MyMWu3L9j_QcnxY9-Lu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[engines/librpma_fio.h, line 24 at r22](https://reviewable.io/reviews/pmem/fio/269#-MyMTHA-6VSECNeiROmz:-MyMWT5c1FjseFlh0NCu:bs7rv2w) ([raw file](https://github.com/pmem/fio/blob/6ad7aca9e493b5ebc77ac33fc3dd5ce94513febc/engines/librpma_fio.h#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

how can it be removed if we use ```struct pmem2_map *map;``` below?
</blockquote></details>

I do not like this but if it works let's leave it as it is.
___
*[engines/librpma_fio.c, line 156 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyMXdcz94hQuQMZeSoD:-MyMXdcz94hQuQMZeSoE:bskvu63) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio.c#L156)):*
> ```C
> {
> 	if (mem->size_mmap)
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> ```

why do not we move this under a common name to librpma_fio_pmem.h and librpma_fio_pmem2.h



_Code quote:_
```C
#ifdef CONFIG_LIBPMEM2_INSTALLED
		(void) pmem2_map_delete(&mem->map);
#else
		(void) pmem_unmap(mem->mem_ptr, mem->size_mmap);
#endif /* CONFIG_LIBPMEM2_INSTALLED */
```


<!-- Sent from Reviewable.io -->

2022-03-17 11:17 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_fio.c, line 16 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyM_k-Z64snvkUy9ntZ:-MyM_k-Z64snvkUy9nt_:b-z49l3u) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio.c#L16)):*
> ```C
>  */
> 
> #include "librpma_fio.h"
> ```

Please move it to to `librpma_fio_pmem.h` and `librpma_fio_pmem2.h`.



_Code quote:_
```C
#include "librpma_fio.h"
```
___
*[engines/librpma_fio.c, line 156 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyMXdcz94hQuQMZeSoD:-MyM_Ek64c-30zRBuS32:b-88n3ba) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio.c#L156)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why do not we move this under a common name to librpma_fio_pmem.h and librpma_fio_pmem2.h
</blockquote></details>

We can do that.
@haichangsi  please move this function to `librpma_fio_pmem.h` and `librpma_fio_pmem2.h` (without ifdef of course).
___
*[engines/librpma_fio_pmem.h, line 16 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyM_xR52HUB__sPuHQy:-MyM_xR67QpJWuuaeJ5X:b-abddyq) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio_pmem.h#L16)):*
> ```objc
>  */
> 
> #include <libpmem.h>
> ```

```c
#include <libpmem.h>
#include "librpma_fio.h"
```



_Code quote:_
```objc
#include <libpmem.h>
```
___
*[engines/librpma_fio_pmem2.h, line 16 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyMa4l6D2p7EDHJfKOZ:-MyMa4l6D2p7EDHJfKO_:b-ioj8j2) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio_pmem2.h#L16)):*
> ```objc
>  */
> 
> #include <libpmem2.h>
> ```

```c
#include <libpmem2.h>
#include "librpma_fio.h"
```



_Code quote:_
```objc
#include <libpmem2.h>
```


<!-- Sent from Reviewable.io -->

2022-03-17 12:20 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_fio.c, line 16 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyM_k-Z64snvkUy9ntZ:-MyMgMWCDq88fkek_ZLd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio.c#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move it to to `librpma_fio_pmem.h` and `librpma_fio_pmem2.h`.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 156 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyMXdcz94hQuQMZeSoD:-MyMnVL54IKH4lrETlZu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio.c#L156)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We can do that.
@haichangsi  please move this function to `librpma_fio_pmem.h` and `librpma_fio_pmem2.h` (without ifdef of course).
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem.h, line 16 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyM_xR52HUB__sPuHQy:-MyMgpYOCajoCbii2sC4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio_pmem.h#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
#include <libpmem.h>
#include "librpma_fio.h"
```
</blockquote></details>

Done.
___
*[engines/librpma_fio_pmem2.h, line 16 at r23](https://reviewable.io/reviews/pmem/fio/269#-MyMa4l6D2p7EDHJfKOZ:-MyMgq9sDXBiY_XPaT4n:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79ae9c5a0ec9a8fe3b27d9fca9238a6584edf2b1/engines/librpma_fio_pmem2.h#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
#include <libpmem2.h>
#include "librpma_fio.h"
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 12:43 UTC, ldorau approved these changes
> Reviewed 3 of 3 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-17 12:43 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/269#-:-MyMtxFU2RH5Hq3P9SSC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-17 12:45 UTC, merged