rpma: make gpspm server use seperate RCQ
pmem/fio pull request #272
Opened 2022-02-16 15:53 UTC by yangx-jy

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

2022-02-17 08:52 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-17 11:17 UTC, grom72 reviewed
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 636 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6Jkz-Es6LvfRE5I5I:-Mw6Jkz-Es6LvfRE5I5J:b-rr8w6a) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L636)):*
> ```C
> }
> 
> static int server_cmpl_process(struct thread_data *td, struct ibv_wc *wc, bool use_rcq)
> ```

```
static int server_cmpl_process(struct thread_data *td, bool use_rcq, struct ibv_wc *wc)
```

result in the last argument



_Code quote:_
```C
static int server_cmpl_process(struct thread_data *td, struct ibv_wc *wc, bool use_rcq)
```
___
*[engines/librpma_gpspm.c, line 636 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6K2tS2PRgDh6dVIPI:-Mw6K2tS2PRgDh6dVIPJ:b-u6dlw7) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L636)):*
> ```C
> }
> 
> static int server_cmpl_process(struct thread_data *td, struct ibv_wc *wc, bool use_rcq)
> ```

```
struct rpma_cq *cq
```
Would it be better to keep ```server_cmpl_process``` simple/universal and move all Recv/Send specific handling to ```server_queue_process```



_Code quote:_
```C
bool use_rcq
```
___
*[engines/librpma_gpspm.c, line 700 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw672heA__5chVQL9gE:-Mw672heA__5chVQL9gF:b-99gtkf) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L700)):*
> ```C
> 		return ret;
> 
> 	if (wc.opcode == IBV_WC_RECV) {
> ```

It is possible that wc will be initiated with random values and will not be modified by server_cmpl_process() if we do not have any RCQ entry.
Shall we find another way to check that wc is a valid one?
i.e.
```
wc.status = IBV_WC_GENERAL_ERR
ret = server_cmpl_process(td, &wc, 1);
if (ret)
	return ret;
if ( wc.status == IBV_WC_SUCCESS && wc.opcode == IBV_WC_RECV) {
```
or let server_cmpl_process() return 1 if there is something to process.



_Suggestion:_
```C
	ret = server_cmpl_process(td, &wc, 1);
	if (ret)
		return ret;

	if (wc.opcode == IBV_WC_RECV) {
```
___
*[engines/librpma_gpspm.c, line 707 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6Knz8BcSwFpc_mMg_:-Mw6Knz8BcSwFpc_mMga:bqnsco9) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L707)):*
> ```C
> 
> 	/* process the send completion */
> 	ret = server_cmpl_process(td, &wc, 0);
> ```

```NULL```?
As we do not need this value at all.
or we use ```wc``` for additional validation



_Code quote:_
```C
&wc
```


<!-- Sent from Reviewable.io -->

2022-02-17 11:22 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[engines/librpma_fio.h, line 256 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6PeTt0u2_N-oSExj0:-Mw6PeTt0u2_N-oSExj1:b2lc0zs) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_fio.h#L256)):*
> ```objc
> 	struct rpma_conn *conn;
> 	struct rpma_cq *cq;
> 	struct rpma_cq *rcq;
> ```

Should this be moved to ```struct server_data { ...}``` of GPSPM server?



_Code quote:_
```objc
struct rpma_cq *rcq;
```
___
*[engines/librpma_fio.c, line 1044 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6PB0mAF_W0mQNOeaZ:-Mw6PB0mAF_W0mQNOea_:btmuaaj) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_fio.c#L1044)):*
> ```C
> 	}
> 
> 	/* get the connection's receive CQ */
> ```

This is GPSPM specyfic code
Shall this be moved to server_open_file() in gpspm engine?



_Code quote:_
```C
	/* get the connection's receive CQ */
	if ((ret = rpma_conn_get_rcq(csd->conn, &csd->rcq))) {
		librpma_td_verror(td, ret, "rpma_conn_get_rcq");
		goto err_conn_delete;
	}
```


<!-- Sent from Reviewable.io -->

2022-02-17 11:23 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-02-17 11:23 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-02-18 10:53 UTC, osalyk requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwBSdLi-JuSGdcGZcbN:b-rmrxil) (no related file):*
Unfortunately, this implementation does not work.
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/am4OrQJwYS5vu8VANV_tgjJi/image.png)

---


<!-- Sent from Reviewable.io -->

2022-02-21 08:49 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwQS052-agsf79WfXnZ:b-uo9ta9) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Unfortunately, this implementation does not work.
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/am4OrQJwYS5vu8VANV_tgjJi/image.png)

</blockquote></details>

@osalyk 

Sorry, I didn't reproduce the issue.
Could you test my new PR?

Thanks a lot

---
___
*[engines/librpma_gpspm.c, line 636 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6Jkz-Es6LvfRE5I5I:-MwQSH-_8vrMbapyFEXh:bi04qlb) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L636)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
static int server_cmpl_process(struct thread_data *td, bool use_rcq, struct ibv_wc *wc)
```

result in the last argument
</blockquote></details>

Done. Deleted `bool use_rcq` argument.
___
*[engines/librpma_gpspm.c, line 636 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6K2tS2PRgDh6dVIPI:-MwQSRn5-tU49sZSOm3c:b-896fix) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L636)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
struct rpma_cq *cq
```
Would it be better to keep ```server_cmpl_process``` simple/universal and move all Recv/Send specific handling to ```server_queue_process```
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 700 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw672heA__5chVQL9gE:-MwQSZ-DAao96ybgU_D3:b-v3ohsr) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L700)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It is possible that wc will be initiated with random values and will not be modified by server_cmpl_process() if we do not have any RCQ entry.
Shall we find another way to check that wc is a valid one?
i.e.
```
wc.status = IBV_WC_GENERAL_ERR
ret = server_cmpl_process(td, &wc, 1);
if (ret)
	return ret;
if ( wc.status == IBV_WC_SUCCESS && wc.opcode == IBV_WC_RECV) {
```
or let server_cmpl_process() return 1 if there is something to process.
</blockquote></details>

Done.  I call `memset(wc, 0, sizeof(struct ibv_wc))` in server_cmpl_process(). In this case, I think `wc.opcode == IBV_WC_RECV` means a receive completion.
___
*[engines/librpma_gpspm.c, line 707 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6Knz8BcSwFpc_mMg_:-MwQSYeV4sLZz_mX5pcI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L707)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```NULL```?
As we do not need this value at all.
or we use ```wc``` for additional validation
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 256 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6PeTt0u2_N-oSExj0:-MwQSVVi8AlnqGkCKVOJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_fio.h#L256)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Should this be moved to ```struct server_data { ...}``` of GPSPM server?
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 1044 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw6PB0mAF_W0mQNOeaZ:-MwQSW1CAv0vPjFqL1VS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_fio.c#L1044)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This is GPSPM specyfic code
Shall this be moved to server_open_file() in gpspm engine?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 14:22 UTC, grom72 reviewed
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-21 14:44 UTC, osalyk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwRjEFo9n2gJn6NtD-3:b1gky55) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@osalyk 

Sorry, I didn't reproduce the issue.
Could you test my new PR?

Thanks a lot
</blockquote></details>

Still not working. 

---


<!-- Sent from Reviewable.io -->

2022-02-21 15:12 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-02-21 15:22 UTC, yangx-jy commented
*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwRs-vC39IGr4LqS_qh:b-4iur18) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Still not working. 
</blockquote></details>

@osalyk 

Is there any output? 

---


<!-- Sent from Reviewable.io -->

2022-02-21 23:30 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 520 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTPuMN1KK7bX98RZSv:-MwTPuMO5ae1AqVffgpR:b1n19xo) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L520)):*
> ```C
> 
> 	/*
> 	 * Calculate the required queue sizes where:
> ```

Without any mathematical symbol, it is not a calculation anymore. xD

My recommendation:

```
The required queue sizes are:
```
___
*[engines/librpma_gpspm.c, line 542 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTQet1C2X0UhdTfTjd:-MwTQet1C2X0UhdTfTje:b-akmukk) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L542)):*
> ```C
> 		goto err_cfg_delete;
> 	}
> ```

No newlines so far among these if statements. I think you might consider these four as a group. ;-)
___
*[engines/librpma_gpspm.c, line 658 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwT_ger81t8q2ANlEni:-MwT_gesESKwN-ZAKH1M:b-bjky7y) ([raw file](https://github.com/pmem/fio/blob/89659b560a1ccf32ace81d8b91719a918f7b2f13/engines/librpma_gpspm.c#L658)):*
> ```C
> 	uint32_t qes_to_process = min(sd->msg_queued_nr, sd->msg_sqe_available);
> 	if (qes_to_process == 0)
> 		return 0;
> ```

The new implementation lacks security checks.

**Note**:

- the `server_cmpl_process()` does not wait for a completion if `o->busy_wait_polling != 0`

So, you can easily end up in a situation where you have collected none of the SEND completions. On the other hand, appearing RECV completions forces you to put yet another SEND request to the SQ. Where you have no other guarantee that SQ can accept the next item except collecting CQEs from CQ.


**Bottom Line**

You have to be sure SQ can accept the next item before you will process another RECV request.
___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwTVtPf8026QQDVS6OV:btox0p) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
> ```C
> 
> 	return 0;
> }
> ```

What is the reason behind changing the order of:

- `server_queue_process()` and
- `server_cmpl_process()`?

It makes the review harder.


<!-- Sent from Reviewable.io -->

2022-02-22 03:12 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[engines/librpma_gpspm.c, line 658 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwT_ger81t8q2ANlEni:-MwUNvyl4rZU1i_lzs_j:bi04rm7) ([raw file](https://github.com/pmem/fio/blob/89659b560a1ccf32ace81d8b91719a918f7b2f13/engines/librpma_gpspm.c#L658)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The new implementation lacks security checks.

**Note**:

- the `server_cmpl_process()` does not wait for a completion if `o->busy_wait_polling != 0`

So, you can easily end up in a situation where you have collected none of the SEND completions. On the other hand, appearing RECV completions forces you to put yet another SEND request to the SQ. Where you have no other guarantee that SQ can accept the next item except collecting CQEs from CQ.


**Bottom Line**

You have to be sure SQ can accept the next item before you will process another RECV request.
</blockquote></details>

Done.  Ensure at least one SQ slot is available by original `sd->msg_sqe_available`.
___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwUEuVx5TuDfot-KS6l:b8hcuiq) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is the reason behind changing the order of:

- `server_queue_process()` and
- `server_cmpl_process()`?

It makes the review harder.
</blockquote></details>

We have to call `server_cmpl_process(csd->cq)` after `server_qe_process()`. If not, `server_cmpl_process(csd->cq)` will be blocked when busy_wait_polling is set to 0.

@janekmi I' m glad to see you. ^_^


<!-- Sent from Reviewable.io -->

2022-02-22 07:40 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwVMj9X5hdFrZ14QDEF:-MwVMj9X5hdFrZ14QDEG:b-7c8yim) (no related file):*
@yangx-jy I'm glad to see you too. :-)
I hope I won't slow down too much your review.

I'm here for sentimental reasons. I have created this software queue some time ago and at that time we came up with the idea to simplify this implementation with the introduction of SRQ. So, for me, it is a kind of closure.

---


<!-- Sent from Reviewable.io -->

2022-02-22 07:46 UTC, janekmi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwVN9z6CmyB0wKqhcyE:by461i6) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

We have to call `server_cmpl_process(csd->cq)` after `server_qe_process()`. If not, `server_cmpl_process(csd->cq)` will be blocked when busy_wait_polling is set to 0.

@janekmi I' m glad to see you. ^_^

</blockquote></details>

@yangx-jy I'm glad to see you too. :-)

I understand the reason. Would you mind solving this technical issue differently so it will be easier to follow the bigger architectural changes going on here? e.g.:

```c
/* XXX to be removed when server_cmpl_process() and server_queue_process() will change places */
server_cmpl_process(); /* declaration only */

server_queue_process()
{
    /* ... */
    server_cmpl_process(); /* the problematic use */
    /* ... */
}

server_cmpl_process()
{
    /* ... */
}
```


<!-- Sent from Reviewable.io -->

2022-02-22 08:48 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwVMj9X5hdFrZ14QDEF:-MwVaRsh6H2zYV1tXLCC:b-3g0gu3) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@yangx-jy I'm glad to see you too. :-)
I hope I won't slow down too much your review.

I'm here for sentimental reasons. I have created this software queue some time ago and at that time we came up with the idea to simplify this implementation with the introduction of SRQ. So, for me, it is a kind of closure.
</blockquote></details>

RCQ or SRQ?

---
___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwV_zrx1vaeT4OjloE1:b-b1bqpu) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@yangx-jy I'm glad to see you too. :-)

I understand the reason. Would you mind solving this technical issue differently so it will be easier to follow the bigger architectural changes going on here? e.g.:

```c
/* XXX to be removed when server_cmpl_process() and server_queue_process() will change places */
server_cmpl_process(); /* declaration only */

server_queue_process()
{
    /* ... */
    server_cmpl_process(); /* the problematic use */
    /* ... */
}

server_cmpl_process()
{
    /* ... */
}
```
</blockquote></details>

Done.  It's my fault.


<!-- Sent from Reviewable.io -->

2022-02-22 13:42 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-22 13:48 UTC, yangx-jy commented
*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwWehkI4gJslGJV8Ss4:bpiwwnp) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@osalyk 

Is there any output? 
</blockquote></details>

@ldorau @grom72 @osalyk 

After reading the logic of gpspm client, it seems that a lot of common code are used by both gpspm client and apm client.
If gpspm client wants to use RCQ, I think we have to refactor a lot of common code and split them into librpma_gpspm.c and librpma_apm.c.  Do you think so?

---


<!-- Sent from Reviewable.io -->

2022-02-22 15:05 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwWwYNH2I6ua8hgZLei:bl5jnf) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau @grom72 @osalyk 

After reading the logic of gpspm client, it seems that a lot of common code are used by both gpspm client and apm client.
If gpspm client wants to use RCQ, I think we have to refactor a lot of common code and split them into librpma_gpspm.c and librpma_apm.c.  Do you think so?
</blockquote></details>

@yangx-jy Decreasing amount of duplicated code without complicating it is always a good idea ;-) So feel free to submit a separate pull request for that (please do not do it in the current one).

---


<!-- Sent from Reviewable.io -->

2022-02-22 15:24 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 65 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWxwSJ3IpfAG-lDkl1:-MwWxwSJ3IpfAG-lDkl2:b-lie40l) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L65)):*
> ```C
> static int client_get_io_u_index(struct ibv_wc *wc, unsigned int *io_u_index);
> 
> static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq,
> ```

Could you reverse the order of `server_queue_process()` and `server_cmpl_process` and remove this forward declaration?



_Code quote:_
```C
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq,
		struct ibv_wc *wc);
```
___
*[engines/librpma_gpspm.c, line 657 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWycWaEQcTqo-uisgS:-MwWycWaEQcTqo-uisgT:b2twdri) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L657)):*
> ```C
> 	struct librpma_fio_server_data *csd = td->io_ops_data;
> 	struct server_data *sd = csd->server_data;
> 	struct ibv_wc wc[2];
> ```

Is there any reason to use an array here?
It is a bit misleading for me, because - as far as I can see - it is not used as an array anywhere.

In my opinion, it would be more clear to use separate variables: `wc_cq` instead of `wc[0]` and `wc_rcq` instead of `wc[1]`:

```c
	struct ibv_wc wc_cq;
	struct ibv_wc wc_rcq;
	int num_entries_got;
```



_Code quote:_
```C
	struct ibv_wc wc[2];
```
___
*[engines/librpma_gpspm.c, line 661 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWzofq8l8bArOdAApg:-MwWzofq8l8bArOdAAph:b-ouhiqt) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L661)):*
> ```C
> 
> 	/* process the receive completion */
> 	ret = server_cmpl_process(td, sd->rcq, &wc[0]);
> ```

Please use an additional argument `num_entries_got` to make sure that a completion has been received:
```c
	/* process the receive completion */
	ret = server_cmpl_process(td, sd->rcq, &wc_rcq, &num_entries_got);
	if (ret)
		return ret;

	if (num_entries_got && wc_rcq.opcode == IBV_WC_RECV) {
```



_Code quote:_
```C
	ret = server_cmpl_process(td, sd->rcq, &wc[0]);
	if (ret)
		return ret;

	if (wc[0].opcode == IBV_WC_RECV) {
```
___
*[engines/librpma_gpspm.c, line 668 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-HOz1IGGuhtvs6vE:-MwX-HOz1IGGuhtvs6vF:b1gxcjr) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L668)):*
> ```C
> 		while (!sd->msg_sqe_available) {
> 			/* ensure that at least one SQ slot is available */
> 			ret = server_cmpl_process(td, csd->cq, &wc[1]);
> ```

```c
ret = server_cmpl_process(td, csd->cq, &wc_cq, NULL);
```



_Code quote:_
```C
			ret = server_cmpl_process(td, csd->cq, &wc[1]);
```
___
*[engines/librpma_gpspm.c, line 678 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-Ulz8OwNGs71ZXER:-MwX-Ulz8OwNGs71ZXES:b1gxcjr) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L678)):*
> ```C
> 
> 		/* process the send completion */
> 		ret = server_cmpl_process(td, csd->cq, &wc[1]);
> ```

```c
ret = server_cmpl_process(td, csd->cq, &wc_cq, NULL);
```



_Code quote:_
```C
ret = server_cmpl_process(td, csd->cq, &wc[1]);
```
___
*[engines/librpma_gpspm.c, line 686 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX0W4uDnFK5TH6Jcit:-MwX0W4uDnFK5TH6Jciu:bjh1fod) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L686)):*
> ```C
> }
> 
> static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq, struct ibv_wc *wc)
> ```

Please add the `num_entries_got` argument to make sure a completion has been received:

```c
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq,
		struct ibv_wc *wc, int *num_entries_got)
```



_Code quote:_
```C
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq, struct ibv_wc *wc)
```
___
*[engines/librpma_gpspm.c, line 695 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-u5gC_ahJL2Y4osQ:-MwX-u5gC_ahJL2Y4osR:b-n010v4) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L695)):*
> ```C
> 	memset(wc, 0, sizeof(struct ibv_wc));
> 
> 	ret = rpma_cq_get_wc(cq, 1, wc, NULL);
> ```

It can be too expensive to call `memset()` in the critical path, so please remove it and and use `rpma_cq_get_wc()` with the `num_entries_got` argument  (we already have the right mechanism in place):

```c
	ret = rpma_cq_get_wc(cq, 1, wc, num_entries_got);
```



_Code quote:_
```C
	memset(wc, 0, sizeof(struct ibv_wc));

	ret = rpma_cq_get_wc(cq, 1, wc, NULL);
```
___
*[engines/librpma_gpspm.c, line 707 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX0P12C1jNDyzztpHb:-MwX0P12C1jNDyzztpHc:bpzlqmp) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L707)):*
> ```C
> 			}
> 
> 			ret = rpma_cq_get_wc(cq, 1, wc, NULL);
> ```

`..., wc, num_entries_got);`



_Code quote:_
```C
rpma_cq_get_wc(cq, 1, wc, NULL);
```


<!-- Sent from Reviewable.io -->

2022-02-22 15:26 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 700 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw672heA__5chVQL9gE:-MwX1NVyBl07BMCPCk9h:bs4pu9m) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L700)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.  I call `memset(wc, 0, sizeof(struct ibv_wc))` in server_cmpl_process(). In this case, I think `wc.opcode == IBV_WC_RECV` means a receive completion.
</blockquote></details>

It can be too expensive to call `memset()` in the critical path, so please remove it and and use `rpma_cq_get_wc()` with the `num_entries_got` argument (we already have the right mechanism in place).


<!-- Sent from Reviewable.io -->

2022-02-22 15:26 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwX1bQcCs9ghEhA8DRR:b-rp8xaw) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.  It's my fault.
</blockquote></details>

Please reverse the order of `server_queue_process()` and `server_cmpl_process()` and remove the forward declaration.


<!-- Sent from Reviewable.io -->

2022-02-22 23:13 UTC, janekmi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi, @ldorau, @osalyk, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwVMj9X5hdFrZ14QDEF:-MwYffUvEuFXc1GNbf6o:bpwypi) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

RCQ or SRQ?
</blockquote></details>

RCQ obviously. ;-)

---
___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwYgdXl4JJ7wAoRvXEO:b-q8gjp5) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please reverse the order of `server_queue_process()` and `server_cmpl_process()` and remove the forward declaration.
</blockquote></details>

Sure it can be either way. Obviously, in the end, the forward declaration is not necessary. I assume you do not agree with my argumentation and want to skip directly to the final implementation with a single PR.

But it is just me guessing, maybe you can elaborate on what is your rationale so we can argue nicely, how about that? :wink:


<!-- Sent from Reviewable.io -->

2022-02-22 23:35 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 12 unresolved discussions (waiting on @ldorau, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 65 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWxwSJ3IpfAG-lDkl1:-MwYhfUr8GUVXCbk3Ex5:bn8a1sa) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you reverse the order of `server_queue_process()` and `server_cmpl_process` and remove this forward declaration?
</blockquote></details>

. (in this case, it is a dot of disagreement :wink:)
___
*[engines/librpma_gpspm.c, line 554 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYiSRL-3l_cO-jX3eZ:-MwYiSRL-3l_cO-jX3e_:b6qoftg) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L554)):*
> ```C
> 
> 	if ((ret = librpma_fio_server_open_file(td, f, cfg))) {
> 		librpma_td_verror(td, ret, "librpma_fio_server_open_file");
> ```

It is not an API call. `librpma_fio_server_open_file()` will log its exact reason of failure by itself.
Please remove the line.
___
*[engines/librpma_gpspm.c, line 695 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-u5gC_ahJL2Y4osQ:-MwYjU5R-wHT2OQKL7AY:b-8fx2u7) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L695)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It can be too expensive to call `memset()` in the critical path, so please remove it and and use `rpma_cq_get_wc()` with the `num_entries_got` argument  (we already have the right mechanism in place):

```c
	ret = rpma_cq_get_wc(cq, 1, wc, num_entries_got);
```
</blockquote></details>

:+1: 
___
*[engines/librpma_gpspm.c, line 707 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX0P12C1jNDyzztpHb:-MwYjYbnAvQWrZFnAAAE:b-8fx2u7) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L707)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`..., wc, num_entries_got);`
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-02-22 23:38 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 13 unresolved discussions (waiting on @ldorau, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwYmfWxECEW2rB60DNE:b-4n4s7) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
> ```C
> 	if (ret == RPMA_E_NO_COMPLETION) {
> 		if (o->busy_wait_polling == 0) {
> 			ret = rpma_cq_wait(cq);
> ```

To me, the greatest weakness of the current implementation, and maybe even a performance bottleneck, is that in non-busy_wait_polling mode you will block on either CQ or RCQ whereas you may wait on both queues at the same time (e.g. epoll) and process whatever comes first.


<!-- Sent from Reviewable.io -->

2022-02-22 23:54 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 18 unresolved discussions (waiting on @ldorau, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 657 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWycWaEQcTqo-uisgS:-MwYoNsDB3LGBQQeDJZ0:b-8fx2u7) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L657)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Is there any reason to use an array here?
It is a bit misleading for me, because - as far as I can see - it is not used as an array anywhere.

In my opinion, it would be more clear to use separate variables: `wc_cq` instead of `wc[0]` and `wc_rcq` instead of `wc[1]`:

```c
	struct ibv_wc wc_cq;
	struct ibv_wc wc_rcq;
	int num_entries_got;
```
</blockquote></details>

:+1: 
___
*[engines/librpma_gpspm.c, line 663 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYopapClr6BUTItexp:-MwYopapClr6BUTItexq:bb6q1xj) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L663)):*
> ```C
> 	ret = server_cmpl_process(td, sd->rcq, &wc[0]);
> 	if (ret)
> 		return ret;
> ```

```c
if ((ret = server_cmpl_process(/* ... */))
   return ret;
```
___
*[engines/librpma_gpspm.c, line 666 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYpRL-7vU5ZMv8Yvtq:-MwYpRL-7vU5ZMv8Yvtr:bow4w6i) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L666)):*
> ```C
> 
> 	if (wc[0].opcode == IBV_WC_RECV) {
> 		while (!sd->msg_sqe_available) {
> ```

I don't like wrapping mathematical formulas into logic magic.
I think what did you mean is that you want to have more than or equal to 1 sd->msg_sqe_available.
So, for the readability sake, `while (sd->msg_sqe_available < 1)`.
___
*[engines/librpma_gpspm.c, line 670 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYqN4O8IjUl4pi4Ubo:-MwYqN4O8IjUl4pi4Ubp:b-3pirrb) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L670)):*
> ```C
> 			ret = server_cmpl_process(td, csd->cq, &wc[1]);
> 			if (ret)
> 				return ret;
> ```

```c
if ((ret = server_cmpl_process(/* ... */))
    return ret;
```
___
*[engines/librpma_gpspm.c, line 675 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYqfdI6WEwEY61wh6T:-MwYqfdI6WEwEY61wh6U:b3kqx) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L675)):*
> ```C
> 		ret = server_qe_process(td, &wc[0]);
> 		if (ret)
> 			return ret;
> ```

.
___
*[engines/librpma_gpspm.c, line 675 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYqgJjAiZY5nFm0G9e:-MwYqgJjAiZY5nFm0G9f:bq5wl68) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L675)):*
> ```C
> 		ret = server_qe_process(td, &wc[0]);
> 		if (ret)
> 			return ret;
> ```

It almost seems redundant given the while loop above.
___
*[engines/librpma_gpspm.c, line 686 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX0W4uDnFK5TH6Jcit:-MwYnTN46HAQwrvM2nlL:bcnfb5) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L686)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the `num_entries_got` argument to make sure a completion has been received:

```c
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq,
		struct ibv_wc *wc, int *num_entries_got)
```
</blockquote></details>

Alternatively, you can introduce a return code informing about the lack of WC to process e.g.

```c
		if (ret == RPMA_E_NO_COMPLETION) {
			/* lack of completion is not an error */
			return NO_COMPLETION_WARNING;
```

`num_entries_got` is great when you can have more than one completion. In this case, it will be always either 0 or 1.


<!-- Sent from Reviewable.io -->

2022-02-23 04:07 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 16 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwZhhJ9AcIBDnsOOxIs:b-80tlqk) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy Decreasing amount of duplicated code without complicating it is always a good idea ;-) So feel free to submit a separate pull request for that (please do not do it in the current one).
</blockquote></details>

Sure.

---
___
*[engines/librpma_gpspm.c, line 700 at r1](https://reviewable.io/reviews/pmem/fio/272#-Mw672heA__5chVQL9gE:-MwZkcJ1EFRtDsYUIukM:b-896fix) ([raw file](https://github.com/pmem/fio/blob/68f32af8922aa77f4302d034dc0053ae84cbed9a/engines/librpma_gpspm.c#L700)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It can be too expensive to call `memset()` in the critical path, so please remove it and and use `rpma_cq_get_wc()` with the `num_entries_got` argument (we already have the right mechanism in place).
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-MwZki5l73nwXQwQMkIt:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sure it can be either way. Obviously, in the end, the forward declaration is not necessary. I assume you do not agree with my argumentation and want to skip directly to the final implementation with a single PR.

But it is just me guessing, maybe you can elaborate on what is your rationale so we can argue nicely, how about that? :wink:
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 65 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWxwSJ3IpfAG-lDkl1:-MwZhnpV586QUj-TA_hr:bgz3lxn) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

. (in this case, it is a dot of disagreement :wink:)
</blockquote></details>

Jan just wants to make the patch review easier by this change. 
I have reversed the order.
___
*[engines/librpma_gpspm.c, line 554 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYiSRL-3l_cO-jX3eZ:-MwZj3xQ3gxgJLv8flFL:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L554)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not an API call. `librpma_fio_server_open_file()` will log its exact reason of failure by itself.
Please remove the line.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 657 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWycWaEQcTqo-uisgS:-MwZj89H7gjUY7AOvsXx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L657)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 661 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWzofq8l8bArOdAApg:-MwZjA7x5wSyl7Jfk4VV:blf47qa) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L661)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please use an additional argument `num_entries_got` to make sure that a completion has been received:
```c
	/* process the receive completion */
	ret = server_cmpl_process(td, sd->rcq, &wc_rcq, &num_entries_got);
	if (ret)
		return ret;

	if (num_entries_got && wc_rcq.opcode == IBV_WC_RECV) {
```
</blockquote></details>

Done. I don't think we need to introduce `num_entries_got`.
I set the return value of `server_cmpl_process` to 0 (no completion) or 1 (one completion). 
___
*[engines/librpma_gpspm.c, line 663 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYopapClr6BUTItexp:-MwZjjFh2v7bYZkGREUT:b7z7r8i) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L663)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
if ((ret = server_cmpl_process(/* ... */))
   return ret;
```
</blockquote></details>

Don't change the code because `ret` may be 0, 1 or -1.
___
*[engines/librpma_gpspm.c, line 666 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYpRL-7vU5ZMv8Yvtq:-MwZjj214mEQXFbFCUpT:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L666)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like wrapping mathematical formulas into logic magic.
I think what did you mean is that you want to have more than or equal to 1 sd->msg_sqe_available.
So, for the readability sake, `while (sd->msg_sqe_available < 1)`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 668 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-HOz1IGGuhtvs6vE:-MwZjzaH2mRTIiY59NF9:b-cbnd06) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L668)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
ret = server_cmpl_process(td, csd->cq, &wc_cq, NULL);
```
</blockquote></details>

Done.  Check ret instead.
___
*[engines/librpma_gpspm.c, line 670 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYqN4O8IjUl4pi4Ubo:-MwZk6VjAYtComO1m4YH:b7z7r8i) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L670)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
if ((ret = server_cmpl_process(/* ... */))
    return ret;
```
</blockquote></details>

Don't change the code because `ret` may be 0, 1 or -1.
___
*[engines/librpma_gpspm.c, line 678 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-Ulz8OwNGs71ZXER:-MwZk8F29dudhMdudGTJ:b-cbnd06) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L678)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
ret = server_cmpl_process(td, csd->cq, &wc_cq, NULL);
```
</blockquote></details>

Done.  Check ret instead.
___
*[engines/librpma_gpspm.c, line 686 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX0W4uDnFK5TH6Jcit:-MwZk9qXBdomFleh2zNY:b-spycgq) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L686)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Alternatively, you can introduce a return code informing about the lack of WC to process e.g.

```c
		if (ret == RPMA_E_NO_COMPLETION) {
			/* lack of completion is not an error */
			return NO_COMPLETION_WARNING;
```

`num_entries_got` is great when you can have more than one completion. In this case, it will be always either 0 or 1.
</blockquote></details>

Done. Agreed. Check ret instead.
___
*[engines/librpma_gpspm.c, line 695 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX-u5gC_ahJL2Y4osQ:-MwZkGgm6_j8nClwKfQC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L695)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwZkJmrEknBsbK3jQxV:b4oleyo) ([raw file](https://github.co [...]

2022-02-23 07:58 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-23 08:34 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-Mw_fEdwDUFc4dUfUISU:bkotic8) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, Now I see :-) I haven't seen and reviewed the previous version and I didn't get the idea of @janekmi .
That's true that the current version is more difficult to be reviewed. 

Excuse me @yangx-jy for bothering you. Could you reverse the order of functions as @janekmi asked to make the changes introduced by this patch more clear and easier for review?
___
*[engines/librpma_gpspm.c, line 65 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWxwSJ3IpfAG-lDkl1:-Mw_h1cVDbHuUbumd-_1:b-yfomwy) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L65)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Jan just wants to make the patch review easier by this change. 
I have reversed the order.
</blockquote></details>

I didn't understand @janekmi .  That's true that the current version is more difficult to be reviewed. 

Excuse me @yangx-jy for bothering you. Could you revert this change?
___
*[engines/librpma_gpspm.c, line 661 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWzofq8l8bArOdAApg:-Mw_dm2S5Vp2PXNgBRaS:b32w0x) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L661)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done. I don't think we need to introduce `num_entries_got`.
I set the return value of `server_cmpl_process` to 0 (no completion) or 1 (one completion). 
</blockquote></details>

OK
___
*[engines/librpma_gpspm.c, line 686 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwX0W4uDnFK5TH6Jcit:-Mw_axrC0WNhaPonqB-b:bqk2cel) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L686)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done. Agreed. Check ret instead.
</blockquote></details>

OK, that's even simpler, but the possible return values have to be documented.
___
*[engines/librpma_gpspm.c, line 648 at r5](https://reviewable.io/reviews/pmem/fio/272#-Mw_cxQx1fN7hvHedtqx:-Mw_cxQy11PTjrWzQAGY:b50wxup) ([raw file](https://github.com/pmem/fio/blob/53a48b64aafe1a5a752c597c4e980946e44373bc/engines/librpma_gpspm.c#L648)):*
> ```C
> }
> 
> static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq, struct ibv_wc *wc)
> ```

```c
/*
 * server_cmpl_process - get and process a completion
 *
 * Return value:
 *    0 or 1  - number of received completions
 *    -1      - in case of an error
 */
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq, struct ibv_wc *wc)
```



_Code quote:_
```C
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq, struct ibv_wc *wc)
```


<!-- Sent from Reviewable.io -->

2022-02-23 08:38 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mw_i3sJ6RrYyg30cF2a:bnll1wt) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Perhaps, we need to evaluate the performance by a lot of tests.
</blockquote></details>

Yes, @janekmi is right. We will have to carefully benchmark this patch before merging it to make sure it does not degrade the performance.


<!-- Sent from Reviewable.io -->

2022-02-23 08:42 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mw_jRQL5zB6a1bVPPdc:b-xe5ox3) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, @janekmi is right. We will have to carefully benchmark this patch before merging it to make sure it does not degrade the performance.
</blockquote></details>

@yangx-jy Maybe you could think about a solution with epoll in meantime?


<!-- Sent from Reviewable.io -->

2022-02-23 10:18 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 722 at r2](https://reviewable.io/reviews/pmem/fio/272#-MwTVtPf8026QQDVS6OU:-Mwa4iiy2ytqsxeAGHE-:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06afeaca2121f9f976969960bbf95337b64415bb/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, Now I see :-) I haven't seen and reviewed the previous version and I didn't get the idea of @janekmi .
That's true that the current version is more difficult to be reviewed. 

Excuse me @yangx-jy for bothering you. Could you reverse the order of functions as @janekmi asked to make the changes introduced by this patch more clear and easier for review?
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 65 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwWxwSJ3IpfAG-lDkl1:-Mwa4j_oBs3ptTBs0OVV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I didn't understand @janekmi .  That's true that the current version is more difficult to be reviewed. 

Excuse me @yangx-jy for bothering you. Could you revert this change?


</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mwa4ZWW3wq8Of20HTxY:b-hbwu6o) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy Maybe you could think about a solution with epoll in meantime?
</blockquote></details>

I will think about a solution with epoll.  For now, just update a new version without epoll.
___
*[engines/librpma_gpspm.c, line 648 at r5](https://reviewable.io/reviews/pmem/fio/272#-Mw_cxQx1fN7hvHedtqx:-Mwa4UahDR-BKnZhvOXu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/53a48b64aafe1a5a752c597c4e980946e44373bc/engines/librpma_gpspm.c#L648)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
/*
 * server_cmpl_process - get and process a completion
 *
 * Return value:
 *    0 or 1  - number of received completions
 *    -1      - in case of an error
 */
static int server_cmpl_process(struct thread_data *td, struct rpma_cq *cq, struct ibv_wc *wc)
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-23 12:36 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mwa_9Wy3NgBbJB-_vWi:b-ucfknh) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I will think about a solution with epoll.  For now, just update a new version without epoll.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-02-23 16:49 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwbR-xz5D51YdaJWa30:bs4vbx0) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Do we need to wait for CQ?
In my opinion, it is enough to wait for RCQ as it is the real trigger to do something.
As soon as we receive something we should consume all available send completion to ensure that we have space for yet another send completion.
So the complete solution would be:
- wait for RCQ
- consume all available CQ if available
- wait for CQ if we have no space because of ```sd->msg_sqe_available```
- consume all available CQ
- consume RCQ


<!-- Sent from Reviewable.io -->

2022-02-23 16:51 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-23 16:51 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-25 07:38 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwjaVPB-47xwl_t9FZB:bpjf3qm) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need to wait for CQ?
In my opinion, it is enough to wait for RCQ as it is the real trigger to do something.
As soon as we receive something we should consume all available send completion to ensure that we have space for yet another send completion.
So the complete solution would be:
- wait for RCQ
- consume all available CQ if available
- wait for CQ if we have no space because of ```sd->msg_sqe_available```
- consume all available CQ
- consume RCQ

</blockquote></details>

Hi @grom72 @ldorau @janekmi 

Current code with my patch is the following logic:
1) consume all Receive CQE and all Send CQE are available
2) wait for an available Receive CQE                                                                                       --> It will be blocked when busy_wait_polling is 0
3) wait for an available Send CQE if we have no space (`sd->msg_sqe_available < 1`)    --> It will be blocked when busy_wait_polling is 0
4) consume a Receive CQE and a Send CQE in pairs(all available Send CQE will be consumed in loops)

According to the logic, we have to do step2 and step3 in order.
I think jan suggest doing step2 and step3 at the same time by epoll. (I'm not sure if this method is better)

@grom72 What do you mean? Do we make step3 not check busy_wait_polling and call `rpma_cq_wait()`?

Best Regards,
Xiao Yang 


<!-- Sent from Reviewable.io -->

2022-02-25 08:04 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwjpXCS7ZwBjep-AK_G:b-hfqff2) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 @ldorau @janekmi 

Current code with my patch is the following logic:
1) consume all Receive CQE and all Send CQE are available
2) wait for an available Receive CQE                                                                                       --> It will be blocked when busy_wait_polling is 0
3) wait for an available Send CQE if we have no space (`sd->msg_sqe_available < 1`)    --> It will be blocked when busy_wait_polling is 0
4) consume a Receive CQE and a Send CQE in pairs(all available Send CQE will be consumed in loops)

According to the logic, we have to do step2 and step3 in order.
I think jan suggest doing step2 and step3 at the same time by epoll. (I'm not sure if this method is better)

@grom72 What do you mean? Do we make step3 not check busy_wait_polling and call `rpma_cq_wait()`?

Best Regards,
Xiao Yang 
</blockquote></details>

Hi  @yangx-jy,
I mean that we have to implement ```busy-wait-polling=0``` partially separately as different logic is required.
```busy-wait-polling=1``` works well according to our performance tests but in the case of ```busy-wait-polling=0``` latency is 2x bigger with your patch.
I think the main problem is with 
```while (sd->msg_sqe_available < 1) ``` condition.
We will not check the Send CQ until we run out of space. So Send CQ will always be full of not consumed completions.

In case of ```busy-wait-poling=0``` after receiving RCQ we should consume all Send CQ (without waiting) and only in case we still do not have space: ```sd->msg_sqe_available == 0``` we should wait for Sende CQ
___
*[engines/librpma_gpspm.c, line 665 at r6](https://reviewable.io/reviews/pmem/fio/272#-MwjslinBKdDXWh_Iudk:-Mwjslio6BvXR8n2BbI8:b3973ys) ([raw file](https://github.com/pmem/fio/blob/3ef6a08fb89191654a66262cb8bad9384647e0f5/engines/librpma_gpspm.c#L665)):*
> ```C
> 	if (ret == 1 && rcq_wc.opcode == IBV_WC_RECV) {
> 		/* ensure that at least one SQ slot is available */
> 		while (sd->msg_sqe_available < 1) {
> ```

```while (sd->msg_sqe_available == 0)```



_Code quote:_
```C
		while (sd->msg_sqe_available < 1) 
```


<!-- Sent from Reviewable.io -->

2022-02-25 11:57 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwkfXxJErYcWO10wxK4:b-ybqq52) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Hi  @yangx-jy,
I mean that we have to implement ```busy-wait-polling=0``` partially separately as different logic is required.
```busy-wait-polling=1``` works well according to our performance tests but in the case of ```busy-wait-polling=0``` latency is 2x bigger with your patch.
I think the main problem is with 
```while (sd->msg_sqe_available < 1) ``` condition.
We will not check the Send CQ until we run out of space. So Send CQ will always be full of not consumed completions.

In case of ```busy-wait-poling=0``` after receiving RCQ we should consume all Send CQ (without waiting) and only in case we still do not have space: ```sd->msg_sqe_available == 0``` we should wait for Sende CQ


</blockquote></details>

Sorry, I didn't understand it fully.

Do you mean the following logic?
1) With `busy-wait-polling=0`, we need to make CQ have a free slot before calling `rpma_cq_wait()`?
2) With `busy-wait-polling=1`, we need to make SQ have a free slot (by freeing a slot on CQ) before calling `rpma_send()`?
___
*[engines/librpma_gpspm.c, line 665 at r6](https://reviewable.io/reviews/pmem/fio/272#-MwjslinBKdDXWh_Iudk:-Mwke8xL8wohDLFqoHa9:b-ycjb8) ([raw file](https://github.com/pmem/fio/blob/3ef6a08fb89191654a66262cb8bad9384647e0f5/engines/librpma_gpspm.c#L665)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```while (sd->msg_sqe_available == 0)```
</blockquote></details>

`sd->msg_sqe_available == 0` is equal to `sd->msg_sqe_available < 1`, right?


<!-- Sent from Reviewable.io -->

2022-02-27 21:39 UTC, janekmi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-27 21:53 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mwx7yL-6FK27J1QSqfU:b-6diuwg) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Sorry, I didn't understand it fully.

Do you mean the following logic?
1) With `busy-wait-polling=0`, we need to make CQ have a free slot before calling `rpma_cq_wait()`?
2) With `busy-wait-polling=1`, we need to make SQ have a free slot (by freeing a slot on CQ) before calling `rpma_send()`?

</blockquote></details>

I think my comment has reached the effect. You are thinking about the dependency between these two queues and how to wait for them. I think I do not have an answer to the question of which waiting and processing scheme is optimal in this case.

**Maybe we should implement first the scheme which most closely resembles what was here done using a single CQ?** (Which in my opinion is the one using epoll) My assumption is that implementing a similar scheme should yield also similar performance results.

Where later on somebody can try to take this implementation and try other schemes e.g. the one proposed by @grom72 and check if it is any better.

**My bottom line is**: I recommend going for the implementation with no worse performance than the current one. For me, it is the final test before accepting the new solution.

At the same time, I think I will leave this pull request to all of you. I believe it is in good hands. Thanks!


<!-- Sent from Reviewable.io -->

2022-02-28 09:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mwzc_-F2Gw5JFQ7EML3:b-qxr8kv) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think my comment has reached the effect. You are thinking about the dependency between these two queues and how to wait for them. I think I do not have an answer to the question of which waiting and processing scheme is optimal in this case.

**Maybe we should implement first the scheme which most closely resembles what was here done using a single CQ?** (Which in my opinion is the one using epoll) My assumption is that implementing a similar scheme should yield also similar performance results.

Where later on somebody can try to take this implementation and try other schemes e.g. the one proposed by @grom72 and check if it is any better.

**My bottom line is**: I recommend going for the implementation with no worse performance than the current one. For me, it is the final test before accepting the new solution.

At the same time, I think I will leave this pull request to all of you. I believe it is in good hands. Thanks!
</blockquote></details>

Yes, exactly, as I wrote before: performance must not degrade.


<!-- Sent from Reviewable.io -->

2022-02-28 09:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 665 at r6](https://reviewable.io/reviews/pmem/fio/272#-MwjslinBKdDXWh_Iudk:-MwzdUkbE9BG9BiD2nxB:b72kmf9) ([raw file](https://github.com/pmem/fio/blob/3ef6a08fb89191654a66262cb8bad9384647e0f5/engines/librpma_gpspm.c#L665)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

`sd->msg_sqe_available == 0` is equal to `sd->msg_sqe_available < 1`, right?
</blockquote></details>

The condition `(sd->msg_sqe_available < 1)` could be used if there would be many (more than one) good values satisfying the condition, but if there is only one good value, then this one should be used explicitly `(sd->msg_sqe_available == 0)` to not cause the confusion.


<!-- Sent from Reviewable.io -->

2022-02-28 09:47 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MwyixPeBQibUCHZdBih:bf04fze) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, exactly, as I wrote before: performance must not degrade.
</blockquote></details>

@grom72 @janekmi @ldorau
 
1) Could you provide the setting about your performance test?
2) About Jan's suggestion, is `epoll()` only used for `busy-wait-polling=0` mode?
3) About Tomasz's suggestion, is there any detailed logic?


<!-- Sent from Reviewable.io -->

2022-02-28 10:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwBSdLi-JuSGdcGZcbM:-MwzqVoY-AAFmuV6kXVm:bo8dl6a) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

It works

---


<!-- Sent from Reviewable.io -->

2022-02-28 10:34 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwzrHJ-7UtK4pjjGaz9:-MwzrHJ-7UtK4pjjGazA:by8pjbq) (no related file):*
The current solution degrades performance - the average latency has increased by about 60%:

![lat_avg.png](https://files.reviewableusercontent.io/images/reviewable/8492895/vCp56M6yOIIEEewU4UMKft_G/lat_avg.png)

---


<!-- Sent from Reviewable.io -->

2022-02-28 14:33 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx-j3fHDmnZpdC3M-mb:b5hmdti) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 @janekmi @ldorau
 
1) Could you provide the setting about your performance test?
2) About Jan's suggestion, is `epoll()` only used for `busy-wait-polling=0` mode?
3) About Tomasz's suggestion, is there any detailed logic?

</blockquote></details>

Ad 1. All settings can be found in:
a) https://pmem.io/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf
b) https://github.com/pmem/rpma/tree/master/tools/perf/figures

Ad 2. `epoll()` should be used only when `busy_wait_polling == 0`

Ad 3. Only Tomasz can answer this question (he is OoO today).


<!-- Sent from Reviewable.io -->

2022-02-28 14:57 UTC, ldorau reviewed
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-01 14:03 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx4he0mBKdfpgBkU9k1:b-aizm4f) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ad 1. All settings can be found in:
a) https://pmem.io/rpma/reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf
b) https://github.com/pmem/rpma/tree/master/tools/perf/figures

Ad 2. `epoll()` should be used only when `busy_wait_polling == 0`

Ad 3. Only Tomasz can answer this question (he is OoO today).
</blockquote></details>

We need a free slot in (s)CQ before processing received data in both cases
We use wait_cq only when ```busy-wait-polling=0``` in two cases:
-  we are waiting for RCQ event (default situation)
- we are waiting for CQ event because ```sd->msg_sqe_available == 0 ```


<!-- Sent from Reviewable.io -->

2022-03-02 04:01 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx7fC6l4E1WBsN7wlb4:bi8jpzc) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We need a free slot in (s)CQ before processing received data in both cases
We use wait_cq only when ```busy-wait-polling=0``` in two cases:
-  we are waiting for RCQ event (default situation)
- we are waiting for CQ event because ```sd->msg_sqe_available == 0 ```


</blockquote></details>

Hi @grom72 @ldorau 

It's fine to replace `sd->msg_sqe_available < 1` with `sd->msg_sqe_available == 0`, but I think current logic follows Tomasz's rule.
I have another idea from Tomasz's rule: how about only waiting for RCQ event?
- always wait for RCQ event
- only poll CQ when `sd->msg_sqe_available == 0`
I have updated this PR based on the idea, could you test if the new PR can improve the performance. 
 
By the way, I am trying to use epoll for this PR as Jan suggested.


<!-- Sent from Reviewable.io -->

2022-03-02 10:00 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx92bPi0AiAHUqmDmco:b-uk04z2) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 @ldorau 

It's fine to replace `sd->msg_sqe_available < 1` with `sd->msg_sqe_available == 0`, but I think current logic follows Tomasz's rule.
I have another idea from Tomasz's rule: how about only waiting for RCQ event?
- always wait for RCQ event
- only poll CQ when `sd->msg_sqe_available == 0`
I have updated this PR based on the idea, could you test if the new PR can improve the performance. 
 
By the way, I am trying to use epoll for this PR as Jan suggested.
</blockquote></details>

we have to wait for (S)CQ event only when  ```sd->msg_sqe_available == 0``` and ```busy-wait-polling=0```


<!-- Sent from Reviewable.io -->

2022-03-02 10:07 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-Mx94Fng11Gxm6AZ0Rhb:b-urzb0g) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
> ```C
> 			return ret;
> 	}
> ```

we should try to consume here as many sCQ completion as possible:
```
while( ret = server_cmpl_process(td, csd->cq, &cq_wc))
{
 if ret < 0 return ret;
 }
```



<!-- Sent from Reviewable.io -->

2022-03-02 10:08 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-02 13:22 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx9jP7c5pSaC4GKhrSd:btrbd7f) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we have to wait for (S)CQ event only when  ```sd->msg_sqe_available == 0``` and ```busy-wait-polling=0```
</blockquote></details>

Hi @grom72 

Did you see that the `previous server_cmpl_process()` or `current server_cmpl_wait()`calls `rpma_cq_get_wc()` twice? it calls `rpma_cq_wait()` only when the first`rpma_cq_get_wc()` gets no completion. In other words, the first `rpma_cq_get_wc()` consumes as many completions as possible and then gets no completion before calling `rpma_cq_wait()`.


<!-- Sent from Reviewable.io -->

2022-03-02 13:45 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx9s2Pz8XDnwATF5z6C:bvceo3t) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

Did you see that the `previous server_cmpl_process()` or `current server_cmpl_wait()`calls `rpma_cq_get_wc()` twice? it calls `rpma_cq_wait()` only when the first`rpma_cq_get_wc()` gets no completion. In other words, the first `rpma_cq_get_wc()` consumes as many completions as possible and then gets no completion before calling `rpma_cq_wait()`.
</blockquote></details>

Each rpma_cq_get_wc() consumes only one completion.


<!-- Sent from Reviewable.io -->

2022-03-02 13:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx9sGrR5e2poNo_DMu-:beeetvx) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Each rpma_cq_get_wc() consumes only one completion.
</blockquote></details>

`rpma_cq_get_wc(cq, 1, wc, NULL);` consumes one or zero completions.


<!-- Sent from Reviewable.io -->

2022-03-02 13:50 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx9st3IBfoaN8n9OkQQ:b-ivnpa) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_cq_get_wc(cq, 1, wc, NULL);` consumes one or zero completions.
</blockquote></details>

@ldorau 

Yes, `rpma_cq_get_wc()` itself consumes only one completion but it is called in loops.


<!-- Sent from Reviewable.io -->

2022-03-02 13:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mx9uxhu-EqgzPMQANIi:bbnovcn) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

Yes, `rpma_cq_get_wc()` itself consumes only one completion but it is called in loops.
</blockquote></details>

Yes, and @grom72 meant to consume all, not only one.


<!-- Sent from Reviewable.io -->

2022-03-02 13:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-Mx9vTse62ygwsmQLPyt:b-revi3r) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we should try to consume here as many sCQ completion as possible:
```
while( ret = server_cmpl_process(td, csd->cq, &cq_wc))
{
 if ret < 0 return ret;
 }
```

</blockquote></details>

@yangx-jy like here


<!-- Sent from Reviewable.io -->

2022-03-02 14:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MxA1MIfEHv4duq8pd-J:b-aqei0e) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, and @grom72 meant to consume all, not only one.
</blockquote></details>

@yangx-jy we will benchmark the @grom72 's proposal.
___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxA1BOeBOvBlkufZZnW:b-aqei0e) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy like here
</blockquote></details>

@yangx-jy we will benchmark the @grom72 's proposal.


<!-- Sent from Reviewable.io -->

2022-03-02 14:44 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxA4Z3N8vxTbTx8s2G4:bprso18) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy we will benchmark the @grom72 's proposal.
</blockquote></details>

Do you want this change?
```
[root@Fedora-32-workstation fio]# git diff
diff --git a/engines/librpma_gpspm.c b/engines/librpma_gpspm.c
index a8007723..07b17973 100644
--- a/engines/librpma_gpspm.c
+++ b/engines/librpma_gpspm.c
@@ -697,13 +697,18 @@ static inline int server_queue_process(struct thread_data *td)
                /* ensure that at least one SQ slot is available */
                while (sd->msg_sqe_available == 0) {
                        /* process the send completion */
-                       ret = server_cmpl_process(td, csd->cq, &cq_wc);
+                       ret = server_cmpl_wait(td, csd->cq, &cq_wc);
                        if (ret < 0)
                                return ret;
                }
 
                if ((ret = server_qe_process(td, &rcq_wc)))
                        return ret;
+
+               while ((ret = server_cmpl_process(td, csd->cq, &cq_wc))) {
+                       if (ret < 0)
+                               return ret;
+               }
        }
```


<!-- Sent from Reviewable.io -->

2022-03-02 15:20 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-03 07:28 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxDfBF29iq9DKbhQgjZ:b2nign6) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Do you want this change?
```
[root@Fedora-32-workstation fio]# git diff
diff --git a/engines/librpma_gpspm.c b/engines/librpma_gpspm.c
index a8007723..07b17973 100644
--- a/engines/librpma_gpspm.c
+++ b/engines/librpma_gpspm.c
@@ -697,13 +697,18 @@ static inline int server_queue_process(struct thread_data *td)
                /* ensure that at least one SQ slot is available */
                while (sd->msg_sqe_available == 0) {
                        /* process the send completion */
-                       ret = server_cmpl_process(td, csd->cq, &cq_wc);
+                       ret = server_cmpl_wait(td, csd->cq, &cq_wc);
                        if (ret < 0)
                                return ret;
                }
 
                if ((ret = server_qe_process(td, &rcq_wc)))
                        return ret;
+
+               while ((ret = server_cmpl_process(td, csd->cq, &cq_wc))) {
+                       if (ret < 0)
+                               return ret;
+               }
        }
```

</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2022-03-03 07:29 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-03 08:47 UTC, yangx-jy reviewed
Hi @grom72 @janekmi @ldorau @osalyk 

I made another method with `epoll` on rcq_with_epoll branch from my fio repo[1].
[1] https://github.com/yangx-jy/fio

I have a question about the method with `epoll`:
Is it necessary to call `rpma_cq_wait()` when `epoll_wait()` got an I/O event.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxDwMyn-oCeYawHbSCI:b-h7qdvz)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MwzrHJ-7UtK4pjjGaz9:-MxDwH_c66TH77xQlVEh:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The current solution degrades performance - the average latency has increased by about 60%:

![lat_avg.png](https://files.reviewableusercontent.io/images/reviewable/8492895/vCp56M6yOIIEEewU4UMKft_G/lat_avg.png)

</blockquote></details>

Done.

---
___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MxDwG6ECKp3DOi0Isdq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy we will benchmark the @grom72 's proposal.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxDwLuSAdzJV9L3ots6:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-03 12:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-MxEq2yC9LaqDrNOsXgg:b9as8v8) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It turns out that the second solution also degrades performance:

![lat_avg_2.png](https://files.reviewableusercontent.io/images/reviewable/8492895/MwEX8q-lkLMdpp2XzbYIBe36/lat_avg_2.png)
___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxEqIbF2_o3YlSOxpvG:b-k4pqlq) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This solution also degrades performance.


<!-- Sent from Reviewable.io -->

2022-03-03 14:07 UTC, ldorau reviewed
It seems to me that it should not be necessary to call `rpma_cq_wait()` when `epoll_wait()` got an I/O event, but to my surprise it is called in our example: 
https://github.com/pmem/rpma/blob/master/examples/06-multiple-connections/server.c#L212
so I have to verify that.

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxF519g7uGzTD-aA4n1:b-g0bvrc)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2022-03-03 14:30 UTC, ldorau reviewed
@yangx-jy The 06 example works without `rpma_cq_wait()` so please try do it in this way.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxFArBd0Kdozfb7jDsc:b-incdr4)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2022-03-03 15:11 UTC, yangx-jy commented
Yes, I also saw example-06 still calls `rpma_cq_wait()` when `epoll_wait()` got an I/O event.
Sure, I will update my `epoll` method without `rpma_cq_wait()`.





<!-- Sent from Reviewable.io -->

2022-03-03 15:54 UTC, yangx-jy commented
I create another PR about the latest `epoll` method, I think it may not degrade the performance.
https://github.com/pmem/fio/pull/282





<!-- Sent from Reviewable.io -->

2022-03-04 11:50 UTC, ldorau reviewed
@yangx-jy Thanks for the new pull request! We will benchmark it during this weekend.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxJkxHx6FvApTBWyl9p:b-tdwpqo)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2022-03-07 10:11 UTC, grom72 reviewed
```rpma_cq_wait()``` is needed to ack event in an event channel and to trigger CQ to create a new event on new completion arrival

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxYqtOQ0OZCI9dBhyaa:bs57261)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2022-03-07 10:18 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxYsEZs-RCY_e12cs7M:b-kg4ooz) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This solution also degrades performance.
</blockquote></details>

It seems that inside ```server_queue_wait()``` we are waiting for rcq while we could consume some CQ completions.


<!-- Sent from Reviewable.io -->

2022-03-07 10:21 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-08 09:29 UTC, yangx-jy reviewed
I will add `rpma_cq_wait()` for #282 if @ldorau  also agree with it.  The update is:
```
# git diff
diff --git a/engines/librpma_gpspm.c b/engines/librpma_gpspm.c
index 807d3c66..e4f80300 100644
--- a/engines/librpma_gpspm.c
+++ b/engines/librpma_gpspm.c
@@ -786,27 +786,18 @@ static int server_cmpl_wait(struct thread_data 
*td, struct rpma_cq *cq,
  {
         int ret;

-       ret = server_cmpl_poll(td, cq, wc);
-       if (ret < 0)
-               return ret;
-
-       /* lack of completion */
-       if (ret == 0) {
-               ret = rpma_cq_wait(cq);
-               if (ret == RPMA_E_NO_COMPLETION) {
-                       /* lack of completion is not an error */
-                       return 0;
-               } else if (ret) {
-                       librpma_td_verror(td, ret, "rpma_cq_wait");
-                       td->terminate = true;
-                       return -1;
-               }
-
-               ret = server_cmpl_poll(td, cq, wc);
-               if (ret < 0)
-                       return ret;
+       ret = rpma_cq_wait(cq);
+       if (ret == RPMA_E_NO_COMPLETION) {
+               /* lack of completion is not an error */
+               return 0;
+       } else if (ret) {
+               librpma_td_verror(td, ret, "rpma_cq_wait");
+               td->terminate = true;
+               return -1;
         }

+       ret = server_cmpl_poll(td, cq, wc);
+
         return ret;
  }

@@ -824,7 +815,7 @@ static int server_queue_wait(struct thread_data *td)

         if (ret == 1 && event.data.fd == sd->rcq_fd) {
                 /* process the receive completion */
-               rv = server_cmpl_poll(td, sd->rcq, &rcq_wc);
+               rv = server_cmpl_wait(td, sd->rcq, &rcq_wc);
                 if (rv < 0)
                         return rv;

@@ -832,7 +823,7 @@ static int server_queue_wait(struct thread_data *td)
                         /* ensure that at least one SQ slot is available */
                         while (sd->msg_sqe_available == 0) {
                                 /* process the send completion */
-                               rv = server_cmpl_wait(td, csd->cq, &cq_wc);
+                               rv = server_cmpl_poll(td, csd->cq, &cq_wc);
                                 if (rv < 0)
                                         return rv;
                         }
@@ -844,7 +835,7 @@ static int server_queue_wait(struct thread_data *td)

         if (ret == 1 && event.data.fd == sd->cq_fd) {
                 /* process the send completion */
-               rv = server_cmpl_poll(td, csd->cq, &cq_wc);
+               rv = server_cmpl_wait(td, csd->cq, &cq_wc);
                 if (rv < 0)
                         return rv;
         }
```

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxcoemeEBVf2HCHZXFL:b-b8jwfy)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MxDwFFi9_HdivtwMuwp:b-51yp6h) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It seems that inside ```server_queue_wait()``` we are waiting for rcq while we could consume some CQ completions.
</blockquote></details>

@grom72 

Do you think how to implement it?
I think `epoll()` is introduced to consume send completions and receive completions in parallel.


<!-- Sent from Reviewable.io -->

2022-03-09 08:15 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-Mxhjb75BsyaOwMzYlss:btc0f4o) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It turns out that the second solution also degrades performance:

![lat_avg_2.png](https://files.reviewableusercontent.io/images/reviewable/8492895/MwEX8q-lkLMdpp2XzbYIBe36/lat_avg_2.png)

</blockquote></details>

but only for busy-wait-polling==0
___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-Mxhg_6L9ONM8x2lEOCL:b-dtvk8v) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 

Do you think how to implement it?
I think `epoll()` is introduced to consume send completions and receive completions in parallel.
</blockquote></details>

epoll() seems to be a valid option but brings us some complexity.
I could adjust my initial design proposal with one more step:
I suggested waiting for rcq (as we do not have anything to do if we do not receive anything) but ...
before that, we should
a) consume as many as possible elements from CQ 
b) wait for the CQ event if sd->msg_sqe_available == 0
___
*[engines/librpma_gpspm.c, line 729 at r10](https://reviewable.io/reviews/pmem/fio/272#-Mxhj0CpDumtKw6k1IyM:-Mxhj0CpDumtKw6k1IyN:brfbmfn) ([raw file](https://github.com/pmem/fio/blob/a32436963ce910567d3b618d870fa9ec0b6e2fc8/engines/librpma_gpspm.c#L729)):*
> ```C
> 	int ret;
> 
> 	/* process the receive completion */
> ```

If we do not have space for next send queue element then first wait for CQ.

```
while (sd->msg_sqe_available == 0) {
	/* process the send completion */
	ret = server_cmpl_wait(td, csd->cq, &cq_wc);
	if (ret < 0)
		return ret;
}
/* process the receive completion */
ret = server_cmpl_wait(td, sd->rcq, &rcq_wc);
```



_Code quote:_
```C
	/* process the receive completion */
	ret = server_cmpl_wait(td, sd->rcq, &rcq_wc);
```


<!-- Sent from Reviewable.io -->

2022-03-09 08:39 UTC, ldorau reviewed
@yangx-jy Yes, please add `rpma_cq_wait()` for #282, we have agreed it is needed.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MxhpDWS4UyEs7_sbavA:bilf9gq)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-14 07:09 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-14 13:01 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 698 at r4](https://reviewable.io/reviews/pmem/fio/272#-MwYmfWxECEW2rB60DND:-My7Vr3R4gbAyvvvv2oI:b-sbevu6) ([raw file](https://github.com/pmem/fio/blob/0a9c2688a9794dc056312e3547cac6ab8c6aa485/engines/librpma_gpspm.c#L698)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but only for busy-wait-polling==0
</blockquote></details>

Yes,  only for busy-wait-polling==0
___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-My7W-ln0I2Y3xI47LTB:b-x1ulh7) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

epoll() seems to be a valid option but brings us some complexity.
I could adjust my initial design proposal with one more step:
I suggested waiting for rcq (as we do not have anything to do if we do not receive anything) but ...
before that, we should
a) consume as many as possible elements from CQ 
b) wait for the CQ event if sd->msg_sqe_available == 0


</blockquote></details>

@yangx-jy Have you implemented it already?


<!-- Sent from Reviewable.io -->

2022-03-15 02:23 UTC, yangx-jy reviewed
I have added `rpma_cq_wait()` for #282  

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MyA4PhGCRoMY6e12zCu:bl5btq)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MyA4hymC1Tq95jK_b-K:b-bsabi5) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy Have you implemented it already?
</blockquote></details>

Done.

Yes, I called `a)` and `b)` before waiting for RCQ. (In other words, I moved `a)` and `b)` out of `ret == 1 && rcq_wc.opcode == IBV_WC_RECV`)
___
*[engines/librpma_gpspm.c, line 729 at r10](https://reviewable.io/reviews/pmem/fio/272#-Mxhj0CpDumtKw6k1IyM:-MyA4Zu-Btm2D_zlhYh-:bmfxpif) ([raw file](https://github.com/pmem/fio/blob/a32436963ce910567d3b618d870fa9ec0b6e2fc8/engines/librpma_gpspm.c#L729)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

If we do not have space for next send queue element then first wait for CQ.

```
while (sd->msg_sqe_available == 0) {
	/* process the send completion */
	ret = server_cmpl_wait(td, csd->cq, &cq_wc);
	if (ret < 0)
		return ret;
}
/* process the receive completion */
ret = server_cmpl_wait(td, sd->rcq, &rcq_wc);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-15 11:57 UTC, ldorau requested changes
OK, thanks!

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MyCQrqoEDl5zI36qBQy:brujzsz)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MyCR-ci-vjC-FKZ6vCT:bu5vgpn) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.

Yes, I called `a)` and `b)` before waiting for RCQ. (In other words, I moved `a)` and `b)` out of `ret == 1 && rcq_wc.opcode == IBV_WC_RECV`)

</blockquote></details>

Thanks! I will benchmark it after having finished benchmarking the epoll version,
___
*[engines/librpma_gpspm.c, line 667 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyC6mSl8uYepEz5Ihjh:-MyC6mSl8uYepEz5Ihji:bg99v6z) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L667)):*
> ```C
> 		return 0;
> 	} else if (ret) {
> 		librpma_td_verror(td, ret, "rpma_cq_get_wc");
> ```

No `else` after `return`:
```c
	if (ret == RPMA_E_NO_COMPLETION)
		return 0; /* lack of completion is not an error */
	if (ret) {
		librpma_td_verror(td, ret, "rpma_cq_get_wc");
		goto err_terminate;
	}
```



_Code quote:_
```C
	if (ret == RPMA_E_NO_COMPLETION) {
		/* lack of completion is not an error */
		return 0;
	} else if (ret) {
		librpma_td_verror(td, ret, "rpma_cq_get_wc");
		goto err_terminate;
	}
```
___
*[engines/librpma_gpspm.c, line 693 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyCKm9s4SRZtp3-pkgw:-MyCKm9s4SRZtp3-pkgx:bdwoww7) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L693)):*
> ```C
>  *   -1      - in case of an error
>  */
> static int server_cmpl_wait(struct thread_data *td, struct rpma_cq *cq,
> ```

`server_cmpl_wait_and_poll`



_Code quote:_
```C
server_cmpl_wait
```
___
*[engines/librpma_gpspm.c, line 709 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyCMIjU-rMak9eLAmIq:-MyCMIjU-rMak9eLAmIr:bxwik0d) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L709)):*
> ```C
> 			return 0;
> 		} else if (ret) {
> 			librpma_td_verror(td, ret, "rpma_cq_wait");
> ```

It is much simpler and does exactly the same:
```c
	ret = server_cmpl_poll(td, cq, wc);
	if (ret)
		return ret;

	/* lack of completion (ret == 0) */
	ret = rpma_cq_wait(cq);
	if (ret == RPMA_E_NO_COMPLETION)
		return 0; /* lack of completion is not an error */
	if (ret) {
		librpma_td_verror(td, ret, "rpma_cq_wait");
		td->terminate = true;
		return -1;
	}

	return server_cmpl_poll(td, cq, wc);
```



_Code quote:_
```C
	ret = server_cmpl_poll(td, cq, wc);
	if (ret < 0)
		return ret;

	/* lack of completion */
	if (ret == 0) {
		ret = rpma_cq_wait(cq);
		if (ret == RPMA_E_NO_COMPLETION) {
			/* lack of completion is not an error */
			return 0;
		} else if (ret) {
			librpma_td_verror(td, ret, "rpma_cq_wait");
			td->terminate = true;
			return -1;
		}

		ret = server_cmpl_poll(td, cq, wc);
		if (ret < 0)


			return ret;
	}

	return ret;
```
___
*[engines/librpma_gpspm.c, line 722 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyCKdSs9sTFd82rv7dQ:-MyCKdSs9sTFd82rv7dR:b-efahlu) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L722)):*
> ```C
> }
> 
> static int server_queue_wait(struct thread_data *td)
> ```

`server_queue_wait_and_poll`



_Code quote:_
```C
server_queue_wait
```
___
*[engines/librpma_gpspm.c, line 729 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyBjXRR14HfkXxGXtGZ:-MyBjXRR14HfkXxGXtG_:b-9h0xg9) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L729)):*
> ```C
> 	int ret;
> 
> 	/* process send completions as many as possible */
> ```

`/* process as many send completions as possible */`



_Code quote:_
```C
/* process send completions as many as possible */
```


<!-- Sent from Reviewable.io -->

2022-03-16 05:34 UTC, yangx-jy reviewed
@grom72 @ldorau

For the non-epoll solution, I unified the logic of `busy_wait_polling=0` and `busy_wait_polling=1` by  a function pointer, like this

```
server_cmpl_process_func = o->busy_wait_polling ? server_cmpl_poll :
		server_cmpl_wait_and_poll;
		
static inline int server_queue_process(struct thread_data *td)
{
        struct librpma_fio_server_data *csd = td->io_ops_data;
        struct server_data *sd = csd->server_data;
        struct ibv_wc cq_wc, rcq_wc;
        int ret;

        /* process as many send completions as possible */
        while ((ret = server_cmpl_poll(td, csd->cq, &cq_wc))) {
                if (ret < 0)
                        return ret;
        }

        /* process the receive completion */
        ret = server_cmpl_process_func(td, sd->rcq, &rcq_wc);
        if (ret < 0)
                return ret;

        if (ret == 1 && rcq_wc.opcode == IBV_WC_RECV) {
                /* ensure that at least one SQ slot is available */
                while (sd->msg_sqe_available == 0) {
                        /* process the send completion */
                        ret = server_cmpl_process_func(td, csd->cq, &cq_wc);
                        if (ret < 0)
                                return ret;
                }

                if ((ret = server_qe_process(td, &rcq_wc)))
                        return ret;
        }

        return 0;
}
```

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MyGBGHK7ylepMtUBUV2:b-mpc3zk)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 708 at r8](https://reviewable.io/reviews/pmem/fio/272#-Mx94Fng11Gxm6AZ0Rha:-MyGCxc-4iONVkHzqmne:b2nhktp) ([raw file](https://github.com/pmem/fio/blob/2a58f301f97085c45221a5cba0a08cfa580d5c92/engines/librpma_gpspm.c#L708)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Thanks! I will benchmark it after having finished benchmarking the epoll version,
</blockquote></details>

OK.
___
*[engines/librpma_gpspm.c, line 667 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyC6mSl8uYepEz5Ihjh:-MyGCbKr7ZwriQeijT4V:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L667)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No `else` after `return`:
```c
	if (ret == RPMA_E_NO_COMPLETION)
		return 0; /* lack of completion is not an error */
	if (ret) {
		librpma_td_verror(td, ret, "rpma_cq_get_wc");
		goto err_terminate;
	}
```

</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 693 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyCKm9s4SRZtp3-pkgw:-MyGCmuzEbUibbJGnBKE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L693)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`server_cmpl_wait_and_poll`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 709 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyCMIjU-rMak9eLAmIq:-MyGCpog-WJrJxl4H6Ed:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L709)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is much simpler and does exactly the same:
```c
	ret = server_cmpl_poll(td, cq, wc);
	if (ret)
		return ret;

	/* lack of completion (ret == 0) */
	ret = rpma_cq_wait(cq);
	if (ret == RPMA_E_NO_COMPLETION)
		return 0; /* lack of completion is not an error */
	if (ret) {
		librpma_td_verror(td, ret, "rpma_cq_wait");
		td->terminate = true;
		return -1;
	}

	return server_cmpl_poll(td, cq, wc);
```
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 722 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyCKdSs9sTFd82rv7dQ:-MyGCqzg76TvqZYCK-k-:b-h4gunn) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L722)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`server_queue_wait_and_poll`
</blockquote></details>

Done.  I have removed the function.
___
*[engines/librpma_gpspm.c, line 729 at r11](https://reviewable.io/reviews/pmem/fio/272#-MyBjXRR14HfkXxGXtGZ:-MyGCwXpDzX7jQHQW5U3:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79901fbaf30cb12b52f5ea4c03215779c7a9e5d6/engines/librpma_gpspm.c#L729)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`/* process as many send completions as possible */`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-16 05:47 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 747 at r12](https://reviewable.io/reviews/pmem/fio/272#-MyGEgJX5QiniCtpkWIR:-MyGEgJX5QiniCtpkWIS:bhmlwbi) ([raw file](https://github.com/pmem/fio/blob/ca6472fa7ae6718419032154fca2f0df3ca085ba/engines/librpma_gpspm.c#L747)):*
> ```C
> 		return ret;
> 
> 	if (ret == 1 && rcq_wc.opcode == IBV_WC_RECV) {
> ```

Can ```rcq_wc.opcode``` be something else than  ```IBV_WC_RECV```



_Code quote:_
```C
&& rcq_wc.opcode == IBV_WC_RECV
```


<!-- Sent from Reviewable.io -->

2022-03-16 06:25 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 747 at r12](https://reviewable.io/reviews/pmem/fio/272#-MyGEgJX5QiniCtpkWIR:-MyGOSZ--_qoKJcNsF3i:buk1edm) ([raw file](https://github.com/pmem/fio/blob/ca6472fa7ae6718419032154fca2f0df3ca085ba/engines/librpma_gpspm.c#L747)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can ```rcq_wc.opcode``` be something else than  ```IBV_WC_RECV```
</blockquote></details>

For separate RCQ, `ret == 1` means `rcq_wc.opcode == IBV_WC_RECV`.
I think we can just use one condition `ret == 1`.


<!-- Sent from Reviewable.io -->

2022-03-16 06:47 UTC, yangx-jy commented
___
*[engines/librpma_gpspm.c, line 747 at r12](https://reviewable.io/reviews/pmem/fio/272#-MyGEgJX5QiniCtpkWIR:-MyGTgRp8KJiOsGvtZ6e:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ca6472fa7ae6718419032154fca2f0df3ca085ba/engines/librpma_gpspm.c#L747)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

For separate RCQ, `ret == 1` means `rcq_wc.opcode == IBV_WC_RECV`.
I think we can just use one condition `ret == 1`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-16 09:47 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-03-16 11:27 UTC, ldorau requested changes
Clever and elegant :-)

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-MyHTgvWBcbcv5nin6Mg:b1d1myf)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 744 at r13](https://reviewable.io/reviews/pmem/fio/272#-MyHSYqWE0-Q4Br269fT:-MyHSYqWE0-Q4Br269fU:b-ll2nb5) ([raw file](https://github.com/pmem/fio/blob/4e16373b6e2dfcd48a28416c46f58f3d3523af0d/engines/librpma_gpspm.c#L744)):*
> ```C
> 	/* process the receive completion */
> 	ret = server_cmpl_process_func(td, sd->rcq, &rcq_wc);
> 	if (ret < 0)
> ```

Simpler and shorter:
```c
	if (ret <= 0)
		return ret;

	/* ret == 1 means rcq_wc.opcode == IBV_WC_RECV */

	/* ensure that at least one SQ slot is available */
	while (sd->msg_sqe_available == 0) {
		/* process the send completion */
		ret = server_cmpl_process_func(td, csd->cq, &cq_wc);
		if (ret < 0)
			return ret;
	}

	return server_qe_process(td, &rcq_wc);
```



_Code quote:_
```C
	if (ret < 0)
		return ret;

	/* ret == 1 means rcq_wc.opcode == IBV_WC_RECV */
	if (ret == 1) {
		/* ensure that at least one SQ slot is available */
		while (sd->msg_sqe_available == 0) {
			/* process the send completion */
			ret = server_cmpl_process_func(td, csd->cq, &cq_wc);
			if (ret < 0)
				return ret;
		}

		if ((ret = server_qe_process(td, &rcq_wc)))
			return ret;
	}

	return 0;
```


<!-- Sent from Reviewable.io -->

2022-03-16 11:27 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-16 11:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 744 at r13](https://reviewable.io/reviews/pmem/fio/272#-MyHSYqWE0-Q4Br269fT:-MyHU6Rd9bAL0O-ZuVOL:b-3x4cmb) ([raw file](https://github.com/pmem/fio/blob/4e16373b6e2dfcd48a28416c46f58f3d3523af0d/engines/librpma_gpspm.c#L744)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Simpler and shorter:
```c
	if (ret <= 0)
		return ret;

	/* ret == 1 means rcq_wc.opcode == IBV_WC_RECV */

	/* ensure that at least one SQ slot is available */
	while (sd->msg_sqe_available == 0) {
		/* process the send completion */
		ret = server_cmpl_process_func(td, csd->cq, &cq_wc);
		if (ret < 0)
			return ret;
	}

	return server_qe_process(td, &rcq_wc);
```

</blockquote></details>

Or even:
```c
	if (ret != 1)
		return ret;
```
at the beginning.


<!-- Sent from Reviewable.io -->

2022-03-16 11:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[engines/librpma_gpspm.c, line 747 at r12](https://reviewable.io/reviews/pmem/fio/272#-MyGEgJX5QiniCtpkWIR:-MyHUNuI9RjUKSa38qHJ:bo9sh23) ([raw file](https://github.com/pmem/fio/blob/ca6472fa7ae6718419032154fca2f0df3ca085ba/engines/librpma_gpspm.c#L747)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, that's OK.


<!-- Sent from Reviewable.io -->

2022-03-16 13:19 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 747 at r12](https://reviewable.io/reviews/pmem/fio/272#-MyGEgJX5QiniCtpkWIR:-MyHsbJBEILyF9B6vCW2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ca6472fa7ae6718419032154fca2f0df3ca085ba/engines/librpma_gpspm.c#L747)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, that's OK.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 744 at r13](https://reviewable.io/reviews/pmem/fio/272#-MyHSYqWE0-Q4Br269fT:-MyHs_gx-sfB7HpViS8_:b-qzirv8) ([raw file](https://github.com/pmem/fio/blob/4e16373b6e2dfcd48a28416c46f58f3d3523af0d/engines/librpma_gpspm.c#L744)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or even:
```c
	if (ret != 1)
		return ret;
```
at the beginning.

</blockquote></details>

Done. Cool.


<!-- Sent from Reviewable.io -->

2022-03-16 14:09 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-03-17 11:56 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MyMixIZ2ByRMcyv7na9:-MyMixIZ2ByRMcyv7naA:b-4a71x) (no related file):*
I do not have anything to add. So it is time for solution benchmarking now.

---


<!-- Sent from Reviewable.io -->

2022-03-17 12:09 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-03-17 12:10 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MyMixIZ2ByRMcyv7na9:-MyMmO0GCsj0IBsNXQ4i:bs2uh7y) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I do not have anything to add. So it is time for solution benchmarking now.
</blockquote></details>

I will benchmark it.

---


<!-- Sent from Reviewable.io -->

2022-03-17 12:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MyMvW6e98yv1EUf3Hcx:-MyMvW6e98yv1EUf3Hcy:bv7cbn8) (no related file):*
Waiting for results of benchmarks ...

---


<!-- Sent from Reviewable.io -->

2022-03-17 21:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MyMvW6e98yv1EUf3Hcx:-MyOnb4u64kZl9JDZz7y:b-pyp6xp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Waiting for results of benchmarks ...
</blockquote></details>

The results are following:

![image.png](https://files.reviewableusercontent.io/images/reviewable/8492895/nNOSVBjJmUsmdGpkXrL86qbY/image.png)

---


<!-- Sent from Reviewable.io -->

2022-05-03 16:35 UTC, yangx-jy commented
Hi @ldorau @grom72

I have updated this PR based on shared completion channel (i.e. devel branch on rpma).
I hope you can test if the latest PR doesn't downgrade the performance and give me feedback.

2022-05-04 14:04 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-05-04 18:45 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[`engines/librpma_gpspm.c` line 755 at r15](https://reviewable.io/reviews/pmem/fio/272#-N1EJZuLBDtbBZLNpBFa:-N1EJZuLBDtbBZLNpBFb:bq0lydm) ([raw file](https://github.com/pmem/fio/blob/fbfe66d2024b2f2216fa192bfb6bb8dde6eb49b2/engines/librpma_gpspm.c#L755)):*
> ```C
> 		while (sd->msg_sqe_available == 0) {
> 			/* process the send completion */
> 			ret = server_cmpl_poll(td, csd->cq, &cq_wc);
> ```

let's use rpma_conn_wait to wait for cq event and ignore rcq events if we need to get space for at least one send completion



_Suggestion:_
```C
			ret = server_cmpl_poll(td, csd->cq, &cq_wc);
			if (ret < 0)
				return ret;
			} else if (ret == 0 ) {
				do {
					ret = rpma_conn_wait(csd->conn, &cq1, &is_rcq);
						if (ret) {
							librpma_td_verror(td, ret, "rpma_conn_wait");
							td->terminate = true;
							return ret;
						}
					}
				} while(is_rcq);
				server_cmpl_poll(td, cq1, &cq_wc1)
			}
```


<!-- Sent from Reviewable.io -->

2022-05-05 06:52 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-05-06 08:49 UTC, yangx-jy commented
*[`engines/librpma_gpspm.c` line 755 at r15](https://reviewable.io/reviews/pmem/fio/272#-N1EJZuLBDtbBZLNpBFa:-N1NXpfO7NGfHluXFiPb:b-eujulg) ([raw file](https://github.com/pmem/fio/blob/fbfe66d2024b2f2216fa192bfb6bb8dde6eb49b2/engines/librpma_gpspm.c#L755)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

let's use rpma_conn_wait to wait for cq event and ignore rcq events if we need to get space for at least one send completion
</blockquote></details>

Done.

I also updated the rest in `server_queue_wait_poll()`.

Note this PR is based on the devel branch on rpma repo.


<!-- Sent from Reviewable.io -->

2022-05-06 11:33 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-05-06 11:34 UTC, grom72 reviewed
@yangx-jy  it seems to be OK - now it is time for benchmarking. @osalyk can you do this?

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272#-:-N1O8HFy4Ypz5dwU1st4:b-pwi6a9)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-05-11 14:03 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-N1nO8Ae87vJMfO9bSMN:-N1nO8Ae87vJMfO9bSMO:b7t86wc) (no related file):*
We get new performance results but numbers are still much below expectation.
Let's make one more change to be more proactive in reading send completion.
See proposed changes below.

___
___
*[`engines/librpma_gpspm.c` line 714 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nK-dC1qhPwodPsWvc:-N1nK-dC1qhPwodPsWvd:undefined) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L714)):*
> ```C
> 	ret = server_cmpl_poll(td, sd->rcq, &rcq_wc);
> 	if (ret != 1)
> 		return ret;
> ```





_Suggestion:_
```C
	/* process the receive completion */
	ret = server_cmpl_poll(td, sd->rcq, &rcq_wc);
	if (ret != 1) {
		if (ret == 0) {
			/* process the SEND completion if nothing to be done with RCQ*/
			ret = server_cmpl_poll(td, sd->cq, &cq_wc);
		}
		return ret;
	}
```
___
*[`engines/librpma_gpspm.c` line 744 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nNA5H-NpWI-Y6x82V:-N1nNA5I6X6MlC9t5VT_:undefined) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L744)):*
> ```C
> 
> 	if (ret == 0) {
> 		do {
> ```





_Suggestion:_
```C
	if (ret == 0) {
		/* process all available send completions before wait for receive */
		do {
			ret = server_cmpl_poll(td, sd->cq, &cq_wc);
			if (ret < 0)
				return ret;
		} while (ret);
		do {
```
___
*[`engines/librpma_gpspm.c` line 753 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nMjouDOfVJaxLjcy1:-N1nMjouDOfVJaxLjcy2:undefined) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L753)):*
> ```C
> 
> 			/* process the receive or send completion */
> 			ret = server_cmpl_poll(td, cq, is_rcq ? &rcq_wc :
> ```





_Suggestion:_
```C
			/* process ALL available receive or send completions */
			do {
				ret = server_cmpl_poll(td, cq, is_rcq ? &rcq_wc :
						&cq_wc);
				if (ret < 0)
					return ret;
			} while (ret);
```


<!-- Sent from Reviewable.io -->

2022-05-12 04:31 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`engines/librpma_gpspm.c` line 714 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nK-dC1qhPwodPsWvc:-N1qVP7E1rucfAp2NpCS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L714)):*
> ```C
> 	ret = server_cmpl_poll(td, sd->rcq, &rcq_wc);
> 	if (ret != 1)
> 		return ret;
> ```

Done.
___
*[`engines/librpma_gpspm.c` line 744 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nNA5H-NpWI-Y6x82V:-N1qVSF08mEYnumrWTj1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L744)):*
> ```C
> 
> 	if (ret == 0) {
> 		do {
> ```

Done.
___
*[`engines/librpma_gpspm.c` line 753 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nMjouDOfVJaxLjcy1:-N1qVT2mDV7gIk0xLZyt:b-4skc6b) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L753)):*
> ```C
> 
> 			/* process the receive or send completion */
> 			ret = server_cmpl_poll(td, cq, is_rcq ? &rcq_wc :
> ```

This change will make rpma_conn_wait() blocking in the next loop (server_queue_wait_poll). So I didn't apply the change.

By the way, I wonder if the previous buffered queue also can improve the performance.  Previous buffered queue can buffer several completions and processes them together later. 


<!-- Sent from Reviewable.io -->

2022-05-12 12:08 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

___
*[`engines/librpma_gpspm.c` line 753 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nMjouDOfVJaxLjcy1:-N1s71J32JuhFt55TRYt:bl0ni0l) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L753)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

This change will make rpma_conn_wait() blocking in the next loop (server_queue_wait_poll). So I didn't apply the change.

By the way, I wonder if the previous buffered queue also can improve the performance.  Previous buffered queue can buffer several completions and processes them together later. 
</blockquote></details>

The sequence below shows an optimal algorithm for a queue with event channel processing.
1) we wait for an event
2) we process as many completions as possible
3) we set up the next event to be reported
4) we process completions that was received to HW between step 2 and 3
```
	while (1) {
		ibv_get_cq_event(dev->channel, &cq, (void *) &ep);

		cnt = 0;
		while (ibv_poll_cq(cq, 1, &wc) > 0) {
			cnt++;
			process_completion(&wc);
		}

		ibv_req_notify_cq(cq, 0);
		while (ibv_poll_cq(cq, 1, &wc) > 0) {
			cnt++;
			process_completion(&wc);
		}

		ibv_ack_cq_events(cq, cnt);
	}
```
We can not do this (yet) with the existing librpma API.
Se my alternative change proposal.
___
*[`engines/librpma_gpspm.c` line 768 at r17](https://reviewable.io/reviews/pmem/fio/272#-N1s82dwAZfJdGIj92lr:-N1s82dwAZfJdGIj92ls:b-bhzu4) ([raw file](https://github.com/pmem/fio/blob/45bdd5000eb3e0367b6603e4ea44954d65a1a36c/engines/librpma_gpspm.c#L768)):*
> ```C
> 			}
> 
> 			/* process a available receive or send completions */
> ```

Let's try to collect more send completions than only one per event.



_Suggestion:_
```C
			if (!is_rcq) {
				/* process as many as possible send completions */
				do {
					ret = server_cmpl_poll(td, cq, &cq_wc);
					if (ret < 0)
						return ret;
				} while (ret);
			} else {
				/* process ONE available receive completions */
				ret = server_cmpl_poll(td, cq, &rcq_wc);
			}
```


<!-- Sent from Reviewable.io -->

2022-05-13 02:52 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`engines/librpma_gpspm.c` line 753 at r16](https://reviewable.io/reviews/pmem/fio/272#-N1nMjouDOfVJaxLjcy1:-N1vKD_V0VDETCjS2Lm-:b2nhktp) ([raw file](https://github.com/pmem/fio/blob/687448418b0be5655a0ce9cdc0594856b00a0bb1/engines/librpma_gpspm.c#L753)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The sequence below shows an optimal algorithm for a queue with event channel processing.
1) we wait for an event
2) we process as many completions as possible
3) we set up the next event to be reported
4) we process completions that was received to HW between step 2 and 3
```
	while (1) {
		ibv_get_cq_event(dev->channel, &cq, (void *) &ep);

		cnt = 0;
		while (ibv_poll_cq(cq, 1, &wc) > 0) {
			cnt++;
			process_completion(&wc);
		}

		ibv_req_notify_cq(cq, 0);
		while (ibv_poll_cq(cq, 1, &wc) > 0) {
			cnt++;
			process_completion(&wc);
		}

		ibv_ack_cq_events(cq, cnt);
	}
```
We can not do this (yet) with the existing librpma API.
Se my alternative change proposal.

</blockquote></details>

OK.
___
*[`engines/librpma_gpspm.c` line 768 at r17](https://reviewable.io/reviews/pmem/fio/272#-N1s82dwAZfJdGIj92lr:-N1vKFejDz-xFMVwFxgH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/45bdd5000eb3e0367b6603e4ea44954d65a1a36c/engines/librpma_gpspm.c#L768)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's try to collect more send completions than only one per event.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 06:57 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-05-16 10:10 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/272)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/272#-MyMvW6e98yv1EUf3Hcx:-N2AznTWDauAQ8ea2waf:bal8gz3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The results are following:

![image.png](https://files.reviewableusercontent.io/images/reviewable/8492895/nNOSVBjJmUsmdGpkXrL86qbY/image.png)

</blockquote></details>

R18 fixes latency:
![image.png](https://files.reviewableusercontent.io/images/reviewable/2588411/nAnEXrpqL_R77PYX47fsrb7W/image.png)

 but still, there are still be issues:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/2588411/e7VqwzU7o4CTM336exPay_ed/image.png)

We need more time to check the root cause of such behavior. Some ideas:
* with RCQ we have more events as every completion generates an event, in the case of "CQ only" consecutive cq_wc and rcq_wc generate one event if come immediately one after another
* every event means context switching - many threads many context switching and kernel resources competition

Meanwhile, we could see if replacing rpma_cq_wait() with rpma_conn_wait() for the "only CQ" solution keeps the same performance.

Most probably we have to think about an alternative implementation of GPSPM in a long term. So far we can not promote GPSPM solution (without busy-wait polling) as an efficient one.

___


<!-- Sent from Reviewable.io -->

2024-12-09 09:15 UTC, closed without merging