rpma: add server_iomem_alloc allocating from PMem
pmem/fio pull request #36
Opened 2020-10-26 20:52 UTC by ldorau

2020-10-26 21:43 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/36#-MKarSB90ZZ3-FeLErgy:-MKarSBAETp-DUDTO1KX:b4rs4r0) (no related file):*
Rebase and undraft please.

---


<!-- Sent from Reviewable.io -->

2020-10-26 21:46 UTC, janekmi reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/36#-MKarzpL8h8A6LaDqFcr:-MKarzpL8h8A6LaDqFcs:by1jir7) (no related file):*
> Implement server_iomem_alloc() allocating from PMem
or using posix_memalign() **if** PMem is not available.

---


<!-- Sent from Reviewable.io -->

2020-10-26 22:00 UTC, janekmi reviewed
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[Makefile, line 104 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKas8pQ-ahxEmehUPZZ:-MKas8pQ-ahxEmehUPZ_:bjqfr5v) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/Makefile#L104)):*
> ```Makefile
> ifdef CONFIG_LIBRPMA
>   librpma_SRCS = engines/librpma.c
>   librpma_LIBS = -lrpma -lpmem
> ```

If `CONFIG_LIBRPMA` takes into consideration the presence of libpmem in the system?
___
*[engines/librpma.c, line 913 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKauS-CDujSeIIHqT-E:-MKauS-CDujSeIIHqT-F:b9gcz32) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L913)):*
> ```C
> 
> 	/* map the file */
> 	mem = pmem_map_file(td->o.filename, 0 /* len */, 0 /* flags */,
> ```

You should use options provided via https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-iomem:
- `td->o.mem_type` and
- `td->o.mmapfile`


<!-- Sent from Reviewable.io -->

2020-10-26 22:04 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 946 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKaw914BJaWeo8HhgVw:-MKaw914BJaWeo8HhgVx:bfij540) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L946)):*
> ```C
> 	sd->size_pmem = 0;
> 
> 	if (alloc_pmem_map_file(td, size)) {
> ```

Please take a look at this function: https://github.com/pmem/fio/blob/rpma/memory.c#L288
I think you should call `alloc_pmem_map_file` only if `td->o.mem_type == MEM_MMAP`.


<!-- Sent from Reviewable.io -->

2020-10-26 22:09 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/36#-MKarSB90ZZ3-FeLErgy:-MKaxAvV3UmxCzUI884S:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Rebase and undraft please.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/36#-MKarzpL8h8A6LaDqFcr:-MKaxI7L9oGxWQQYGwHd:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Implement server_iomem_alloc() allocating from PMem
or using posix_memalign() **if** PMem is not available.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-10-26 22:10 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKawU-J3QQc70fBvCGY:b-9adk40) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
> ```C
> 	if (alloc_pmem_map_file(td, size)) {
> 		log_info("fio: allocating memory using posix_memalign()\n");
> 		return alloc_aligned(td, size);
> ```

It seems the variables related to options steering this mechanism should be available during the `init()` hook.
So... we do not have to implement `alloc_aligned()`. We can just check if calling `alloc_pmem_map_file()` will be needed.
If not... we can reconfigure the engine to use the generic `iomem_alloc/free` hooks as follows:

```c
if (td->o.mem_type == MEM_MALLOC) {
    td->io_ops->iomem_alloc = NULL;
    td->io_ops->iomem_free = NULL;
}
```


<!-- Sent from Reviewable.io -->

2020-10-26 22:11 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2020-10-27 06:18 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKch57O13hMkja401QH:bt8u7rr) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems the variables related to options steering this mechanism should be available during the `init()` hook.
So... we do not have to implement `alloc_aligned()`. We can just check if calling `alloc_pmem_map_file()` will be needed.
If not... we can reconfigure the engine to use the generic `iomem_alloc/free` hooks as follows:

```c
if (td->o.mem_type == MEM_MALLOC) {
    td->io_ops->iomem_alloc = NULL;
    td->io_ops->iomem_free = NULL;
}
```
</blockquote></details>

Yes, that's right, but IMHO the condition should look rather like:

```
	if (td->o.mem_type != MEM_MMAP) {
       ...
```


<!-- Sent from Reviewable.io -->

2020-10-27 06:19 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKchOJ82o1WLrozhfA0:b-z3dnzb) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, that's right, but IMHO the condition should look rather like:

```
	if (td->o.mem_type != MEM_MMAP) {
       ...
```
</blockquote></details>

... because alloc_pmem_map_file should be called only if td->o.mem_type == MEM_MMAP.


<!-- Sent from Reviewable.io -->

2020-10-27 07:04 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKcqx0OEWQp3sZfT1bp:b4etpdo) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... because alloc_pmem_map_file should be called only if td->o.mem_type == MEM_MMAP.
</blockquote></details>

You will do it right. ;-) In my opinion, it will be more clear to have by default set both hooks:

```c
    .iomem_alloc    = server_iomem_alloc,
    .iomem_free     = server_iomem_free,
```

And in the `init()` hook use the condition I wrote above to remove these hooks and use the generic implementation for a `MEM_MALLOC`.


<!-- Sent from Reviewable.io -->

2020-10-27 07:10 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKcsYvCENge-icbZ7Xc:brgn2ri) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You will do it right. ;-) In my opinion, it will be more clear to have by default set both hooks:

```c
    .iomem_alloc    = server_iomem_alloc,
    .iomem_free     = server_iomem_free,
```

And in the `init()` hook use the condition I wrote above to remove these hooks and use the generic implementation for a `MEM_MALLOC`.
</blockquote></details>

Yes, exactly, my opinion is the same, but, as I wrote above, the condition should look rather like:

```
	/*
	 * Reset iomem hooks if mem_type != MEM_MMAP,
	 * because alloc_pmem_map_file should be called
	 * only if td->o.mem_type == MEM_MMAP.
	 */
	if (td->o.mem_type != MEM_MMAP) {
		td->io_ops->iomem_alloc = NULL;
		td->io_ops->iomem_free = NULL;
	}
```

because `alloc_pmem_map_file()` should be called only if td->o.mem_type == MEM_MMAP.


<!-- Sent from Reviewable.io -->

2020-10-27 07:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[Makefile, line 104 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKas8pQ-ahxEmehUPZZ:-MKctoFZAE19EaveWquh:bu7wgtd) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/Makefile#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If `CONFIG_LIBRPMA` takes into consideration the presence of libpmem in the system?
</blockquote></details>

No, not yet, `CONFIG_LIBRPMA` does not even take into consideration the presence of librpma in the system either ;-)


<!-- Sent from Reviewable.io -->

2020-10-27 07:41 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 913 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKauS-CDujSeIIHqT-E:-MKd-Kvd61l1OANZGAIB:b3kqx) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L913)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You should use options provided via https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-iomem:
- `td->o.mem_type` and
- `td->o.mmapfile`
</blockquote></details>

.
___
*[engines/librpma.c, line 946 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKaw914BJaWeo8HhgVw:-MKcwUPJ--vsuU_SJErL:bpgotnz) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L946)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please take a look at this function: https://github.com/pmem/fio/blob/rpma/memory.c#L288
I think you should call `alloc_pmem_map_file` only if `td->o.mem_type == MEM_MMAP`.
</blockquote></details>

No, it is impossible, because:

```
	/*
	 * If the IO engine has hooks to allocate/free memory, use those. But
	 * error out if the user explicitly asked for something else.
	 */
	if (td->io_ops->iomem_alloc) {
		if (fio_option_is_set(&td->o, mem_type)) {
			log_err("fio: option 'mem/iomem' conflicts with specified IO engine\n");
			ret = 1;
		} else
			ret = td->io_ops->iomem_alloc(td, total_mem);
```
___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKd-Dw29GfPEo71CMZm:bpvriq1) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, exactly, my opinion is the same, but, as I wrote above, the condition should look rather like:

```
	/*
	 * Reset iomem hooks if mem_type != MEM_MMAP,
	 * because alloc_pmem_map_file should be called
	 * only if td->o.mem_type == MEM_MMAP.
	 */
	if (td->o.mem_type != MEM_MMAP) {
		td->io_ops->iomem_alloc = NULL;
		td->io_ops->iomem_free = NULL;
	}
```

because `alloc_pmem_map_file()` should be called only if td->o.mem_type == MEM_MMAP.
</blockquote></details>

It turned out it is impossible - see the previous comment


<!-- Sent from Reviewable.io -->

2020-10-27 15:06 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 913 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKauS-CDujSeIIHqT-E:-MKe_v9N5thjEwrzroDf:b-896fix) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L913)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 946 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKaw914BJaWeo8HhgVw:-MKea5Tm1uf5lcW5KxHS:bb6un1j) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L946)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it is impossible, because:

```
	/*
	 * If the IO engine has hooks to allocate/free memory, use those. But
	 * error out if the user explicitly asked for something else.
	 */
	if (td->io_ops->iomem_alloc) {
		if (fio_option_is_set(&td->o, mem_type)) {
			log_err("fio: option 'mem/iomem' conflicts with specified IO engine\n");
			ret = 1;
		} else
			ret = td->io_ops->iomem_alloc(td, total_mem);
```
</blockquote></details>

Done
___
*[engines/librpma.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKawb8QDjSjcjG-an7e:-MKe_xzpD9NY3fc_w3La:b-896fix) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/engines/librpma.c#L948)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It turned out it is impossible - see the previous comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 08:16 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[Makefile, line 104 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKas8pQ-ahxEmehUPZZ:-MKdrr9DAB-cZlU60VzD:bz33vff) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/Makefile#L104)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, not yet, `CONFIG_LIBRPMA` does not even take into consideration the presence of librpma in the system either ;-)
</blockquote></details>

TBD xD
___
*[engines/librpma.c, line 986 at r3](https://reviewable.io/reviews/pmem/fio/36#-MKiGgzoE9luvIYw7tFI:-MKiGgzoE9luvIYw7tFJ:b-wygrh4) ([raw file](https://github.com/pmem/fio/blob/8f4b962de0a6d6abe3c8ca781442d5a851a7bebf/engines/librpma.c#L986)):*
> ```C
> 	}
> 
> 	sd->is_pmem = 1;
> ```

It seems this variable is not needed either.
___
*[engines/librpma.c, line 1004 at r3](https://reviewable.io/reviews/pmem/fio/36#-MKiGFE61bvIvOGr7pUu:-MKiGFE61bvIvOGr7pUv:buvsupf) ([raw file](https://github.com/pmem/fio/blob/8f4b962de0a6d6abe3c8ca781442d5a851a7bebf/engines/librpma.c#L1004)):*
> ```C
> 
> 	return alloc_pmem_map_file(td, size);
> }
> ```

This function seems empty.
___
*[engines/librpma.c, line 1016 at r3](https://reviewable.io/reviews/pmem/fio/36#-MKiGYaf2SPHrA_YaQpH:-MKiGYaf2SPHrA_YaQpI:b-i6wzhe) ([raw file](https://github.com/pmem/fio/blob/8f4b962de0a6d6abe3c8ca781442d5a851a7bebf/engines/librpma.c#L1016)):*
> ```C
> 		(void) pmem_unmap(td->orig_buffer, sd->size_pmem);
> 	else
> 		free(td->orig_buffer);
> ```

This case should never happen.


<!-- Sent from Reviewable.io -->

2020-10-28 08:46 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[Makefile, line 104 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKas8pQ-ahxEmehUPZZ:-MKiKYV02ifwiEeEpoyy:b-9zp6h1) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/Makefile#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBD xD
</blockquote></details>

I will do that in a separate PR
___
*[engines/librpma.c, line 986 at r3](https://reviewable.io/reviews/pmem/fio/36#-MKiGgzoE9luvIYw7tFI:-MKiLDm48NY-emUVyK_1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8f4b962de0a6d6abe3c8ca781442d5a851a7bebf/engines/librpma.c#L986)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems this variable is not needed either.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1004 at r3](https://reviewable.io/reviews/pmem/fio/36#-MKiGFE61bvIvOGr7pUu:-MKiNq9OA5TfKlpietzZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8f4b962de0a6d6abe3c8ca781442d5a851a7bebf/engines/librpma.c#L1004)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This function seems empty.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1016 at r3](https://reviewable.io/reviews/pmem/fio/36#-MKiGYaf2SPHrA_YaQpH:-MKiLCdc78AYNXE5peGz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8f4b962de0a6d6abe3c8ca781442d5a851a7bebf/engines/librpma.c#L1016)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This case should never happen.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 09:05 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 1034 at r4](https://reviewable.io/reviews/pmem/fio/36#-MKiRV9m9SsetVkxkO5a:-MKiRV9m9SsetVkxkO5b:b-kx2n68) ([raw file](https://github.com/pmem/fio/blob/aea9bb539d8a04a197c0aacd73185376170b915d/engines/librpma.c#L1034)):*
> ```C
> /*
>  * server_iomem_alloc -- allocates memory from PMem using pmem_map_file()
>  * (PMem version of mmap()) from the PMDK's libpmem library
> ```

`)` is missing.
___
*[examples/librpma-server.fio, line 22 at r4](https://reviewable.io/reviews/pmem/fio/36#-MKiRpNNC61Ahg7wd5JE:-MKiRpNNC61Ahg7wd5JF:bq7sk5m) ([raw file](https://github.com/pmem/fio/blob/aea9bb539d8a04a197c0aacd73185376170b915d/examples/librpma-server.fio#L22)):*
> ```
> num_conns=[total # of connections]
> size=[size of workspace for a single connection]
> mem=mmap:/path/to/pmem_file # [XXX device dax or an existing fsdax file]
> ```

This PR can remove the XXX from here.


<!-- Sent from Reviewable.io -->

2020-10-28 09:30 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/librpma-server.fio, line 22 at r4](https://reviewable.io/reviews/pmem/fio/36#-MKiRpNNC61Ahg7wd5JE:-MKiXqfvESCJ1OVp5kf1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/aea9bb539d8a04a197c0aacd73185376170b915d/examples/librpma-server.fio#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This PR can remove the XXX from here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 10:49 UTC, janekmi approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 10:49 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36#-:-MKioyxn9-JPRO4cJTxo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 11:32 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 3 of 4 files reviewed, all discussions resolved

___
*[Makefile, line 104 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKas8pQ-ahxEmehUPZZ:-MKiyfOr4GF5Xpm3_-7-:b-86ltmd) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/Makefile#L104)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I will do that in a separate PR
</blockquote></details>

and yet there it is already :-)


<!-- Sent from Reviewable.io -->

2020-10-28 11:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 3 of 4 files reviewed, all discussions resolved

___
*[Makefile, line 104 at r1](https://reviewable.io/reviews/pmem/fio/36#-MKas8pQ-ahxEmehUPZZ:-MKiz0ITAyZaVO34yrn9:bb6un1j) ([raw file](https://github.com/pmem/fio/blob/260b83cfbadf15b95d7e0d519684d5113dfe8f6a/Makefile#L104)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

and yet there it is already :-)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-10-28 11:50 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[configure, line 2807 at r6](https://reviewable.io/reviews/pmem/fio/36#-MKj1kcg-FMPEo_FYuk0:-MKj1kcg-FMPEo_FYuk1:b-bluis6) ([raw file](https://github.com/pmem/fio/blob/5d7ad06223edd6003a5f8314138e3b5be939b19d/configure#L2807)):*
> ```
> # XXX librpma specific test needed
> # librpma is supported on the 'x86_64' architecture for now
> if test "$cpu" = "x86_64" -a "$libverbs" = "yes" -a "$rdmacm" = "yes" -a "$libpmem" = "yes" ; then
> ```

Did you mean to add it here?


<!-- Sent from Reviewable.io -->

2020-10-28 11:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[configure, line 2807 at r6](https://reviewable.io/reviews/pmem/fio/36#-MKj1kcg-FMPEo_FYuk0:-MKj2Zwi3KiCm4Z4tOwq:bvuu701) ([raw file](https://github.com/pmem/fio/blob/5d7ad06223edd6003a5f8314138e3b5be939b19d/configure#L2807)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Did you mean to add it here?
</blockquote></details>

Yes, I have really added it here :-)


<!-- Sent from Reviewable.io -->

2020-10-28 12:03 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[configure, line 2807 at r6](https://reviewable.io/reviews/pmem/fio/36#-MKj1kcg-FMPEo_FYuk0:-MKj4eTqBQ9c1BMdYnMY:bb7kr4y) ([raw file](https://github.com/pmem/fio/blob/5d7ad06223edd6003a5f8314138e3b5be939b19d/configure#L2807)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, I have really added it here :-)
</blockquote></details>

I got it. Sorry. I saw something different. ;-)


<!-- Sent from Reviewable.io -->

2020-10-28 12:56 UTC, ldorau reviewed
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36#-:-MKjGrgJC0COhUket1Dn:b9x2p3v)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 13:57 UTC, grom72 reviewed
> Reviewed 1 of 6 files at r1, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 1087 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjQPNkCTPM0eixSFot:-MKjQPNkCTPM0eixSFou:b-wj15f8) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1087)):*
> ```C
> 	return FIO_Q_COMPLETED;
> }
> ```

what about an alternative approach:
```

static int server_iomem_alloc(struct thread_data *td, size_t size)
{
	struct server_data *sd =  td->io_ops_data;
	if (td->o.mem_type != MEM_MMAP) {
		td->io_ops->iomem_alloc = NULL;
		td->io_ops->iomem_free = NULL;
		return allocate_io_mem(td);
	} else {
		//original code of server_iomem_alloc() as below
	}
}

```
___
*[engines/librpma.c, line 1120 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjP4hM47FHwSwnF64K:-MKjP4hM47FHwSwnF64L:b-1x0m4s) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1120)):*
> ```C
> 		return 1;
> 	}
> ```

shall we verify size_pmem against size * num_conns?? or origin_buff_size
___
*[engines/librpma.c, line 1127 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjRs5ZDotmLLDp7IXo:-MKjRs5ZDotmLLDp7IXp:b5xqh4y) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1127)):*
> ```
> return td->orig_buffer == NULL;
> ```
```
return 0;
```
" td->orig_buffer == NULL " is already checked just after pmem_map_file() call
___
*[engines/librpma.c, line 1130 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUoLOEgUNBu0-0IEe:-MKjUoLOEgUNBu0-0IEf:b-ei6x6u) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1130)):*
> ```
> server_iomem_free
> ```
from free_io_mem:
```
...
	td->orig_buffer = NULL;
	td->orig_buffer_size = 0;
}
```

___
*[engines/librpma.c, line 1135 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUQhqEsKCwV2WZ7mb:-MKjUQhrDYjcPlGoJ-7D:bquykvt) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1135)):*
> ```
> pmem_unmap
> ```
does it work for td->orig_buffer == NULL?


<!-- Sent from Reviewable.io -->

2020-10-28 14:02 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 1087 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjQPNkCTPM0eixSFot:-MKjVETn4uIWdT5ofeEK:batqujc) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1087)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about an alternative approach:
```

static int server_iomem_alloc(struct thread_data *td, size_t size)
{
	struct server_data *sd =  td->io_ops_data;
	if (td->o.mem_type != MEM_MMAP) {
		td->io_ops->iomem_alloc = NULL;
		td->io_ops->iomem_free = NULL;
		return allocate_io_mem(td);
	} else {
		//original code of server_iomem_alloc() as below
	}
}

```
</blockquote></details>

Please don't. We can rewrite it many times. And probably we will. We have already agreed with @ldorau to leave it as is for now.
___
*[engines/librpma.c, line 1120 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjP4hM47FHwSwnF64K:-MKjVXYE6ZLFtMEjwi4V:b8ne2pn) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1120)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we verify size_pmem against size * num_conns?? or origin_buff_size
</blockquote></details>

Yes, we should. This is why this function accepts the `size` argument. Please fix it.
___
*[engines/librpma.c, line 1127 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjRs5ZDotmLLDp7IXo:-MKjVlVS-Yjderf-JSX4:bez7gt1) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1127)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return td->orig_buffer == NULL;
> ```
```
return 0;
```
" td->orig_buffer == NULL " is already checked just after pmem_map_file() call
</blockquote></details>

I guess we can just return here `0`.
___
*[engines/librpma.c, line 1130 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUoLOEgUNBu0-0IEe:-MKjVsXtEcUGZqUF8Awr:bp128vq) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1130)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> server_iomem_free
> ```
from free_io_mem:
```
...
	td->orig_buffer = NULL;
	td->orig_buffer_size = 0;
}
</blockquote></details>

I'm for it.
___
*[engines/librpma.c, line 1135 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUQhqEsKCwV2WZ7mb:-MKjVy5K2U_cJmulK1ww:b-y2znsg) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> pmem_unmap
> ```
does it work for td->orig_buffer == NULL?
</blockquote></details>

Why we should be ready for such a case?


<!-- Sent from Reviewable.io -->

2020-10-28 14:16 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/36#-MKjYwbZ2kwhipwAkOId:-MKjYwb_7ZVd_RHndc0j:bplmyi2) (no related file):*
I'm pretty sure need also `invalidate()` hook implemented just to do not care when and how FIO will try to invalidate our custom-opened PMem file:

```
fio: cache invalidation of server.0.0 failed: Bad file descriptor
```

---


<!-- Sent from Reviewable.io -->

2020-10-28 15:15 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/36#-MKjYwbZ2kwhipwAkOId:-MKjgFHZ7kkGPc4iYF4r:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm pretty sure need also `invalidate()` hook implemented just to do not care when and how FIO will try to invalidate our custom-opened PMem file:

```
fio: cache invalidation of server.0.0 failed: Bad file descriptor
```
</blockquote></details>

Done.

---
___
*[engines/librpma.c, line 1087 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjQPNkCTPM0eixSFot:-MKjiigi4K8_8eFecNoW:b-qg2yxa) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1087)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please don't. We can rewrite it many times. And probably we will. We have already agreed with @ldorau to leave it as is for now.
</blockquote></details>

Exactly, the discussion on the shape of this function was held some time ago.
___
*[engines/librpma.c, line 1120 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjP4hM47FHwSwnF64K:-MKjk2wj2Nw3C-MVcBxX:bes036n) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes, we should. This is why this function accepts the `size` argument. Please fix it.
</blockquote></details>

Why can it be wrong? This hook is not mandatory, so `size` has to be correct.  
Or do you mean to check if `size_pmem >= size` ?
___
*[engines/librpma.c, line 1127 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjRs5ZDotmLLDp7IXo:-MKjgcnI9CAGo5J62hwT:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I guess we can just return here `0`.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1130 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUoLOEgUNBu0-0IEe:-MKjh1KDAgnJ35-xDfie:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1130)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm for it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 15:27 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 1120 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjP4hM47FHwSwnF64K:-MKjnSm2EmXgkOD1XTRg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`size_pmem >= size` is what we mean.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 15:54 UTC, ldorau reviewed
Squashed commits into one.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36#-:-MKjugbm2BHpgP2LFeqB:bcn6nc7)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-10-28 16:02 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 1087 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjQPNkCTPM0eixSFot:-MKjwOnt9jSEZTbzKN7t:bjqwlof) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1087)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Exactly, the discussion on the shape of this function was held some time ago.
</blockquote></details>

I see it for the first time ;)
___
*[engines/librpma.c, line 1135 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUQhqEsKCwV2WZ7mb:-MKjwDp8EzCaq3vNhL5y:b2c8yk9) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1135)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why we should be ready for such a case?
</blockquote></details>

because free mem is also called when alloc mem fails


<!-- Sent from Reviewable.io -->

2020-10-28 16:05 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 1135 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUQhqEsKCwV2WZ7mb:-MKjx60y4hb-KOG12Ghw:bn1h5gr) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

because free mem is also called when alloc mem fails
</blockquote></details>

Check added.


<!-- Sent from Reviewable.io -->

2020-10-28 16:41 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 19:50 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[engines/librpma.c, line 1087 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjQPNkCTPM0eixSFot:-MKkhlut1Z1Ln0K_-fSa:b20b3st) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1087)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I see it for the first time ;)
</blockquote></details>

You are late. ;-)

Being serious, I am going out of this discussion. Both solutions are correct. Both solutions seem somewhat more or less hacky.
I'm maybe more leaning more towards @grom72 's type. But because at this point is not even certain if the server will prepare its memory as io_u, the whole discussion may be pointless.

So I'm voting for progressing quickly with the next revisions of the server. I leave it up to you @ldorau.
___
*[engines/librpma.c, line 1135 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjUQhqEsKCwV2WZ7mb:-MKkjjY20WUGeFoBOnmz:beqngdw) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Check added.
</blockquote></details>

Poor implementation on the FIO side. Don't like it very much. But you are right.

**I think we have to be vigilant all the time and take nothing for granted.**

Good catch.


<!-- Sent from Reviewable.io -->

2020-10-28 19:51 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 1142 at r10](https://reviewable.io/reviews/pmem/fio/36#-MKkktnF-S2pW2YLpLWS:-MKkktnF-S2pW2YLpLWT:bwqnqgq) ([raw file](https://github.com/pmem/fio/blob/f7a3dc5ce5d5d6b8ea83f863bad92c6f0ee939ad/engines/librpma.c#L1142)):*
> ```C
> 	struct server_data *sd = td->io_ops_data;
> 
> 	if (sd && td->orig_buffer)
> ```

Maybe the opposite condition with quick `return` will make more sense here.


<!-- Sent from Reviewable.io -->

2020-10-28 20:43 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[engines/librpma.c, line 1087 at r7](https://reviewable.io/reviews/pmem/fio/36#-MKjQPNkCTPM0eixSFot:-MKkvYggCWHtBO2j6eS_:bgecl6s) ([raw file](https://github.com/pmem/fio/blob/8be02b3d8ff2cd48e7a29513a2859cdffaca7a97/engines/librpma.c#L1087)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are late. ;-)

Being serious, I am going out of this discussion. Both solutions are correct. Both solutions seem somewhat more or less hacky.
I'm maybe more leaning more towards @grom72 's type. But because at this point is not even certain if the server will prepare its memory as io_u, the whole discussion may be pointless.

So I'm voting for progressing quickly with the next revisions of the server. I leave it up to you @ldorau.
</blockquote></details>

@grom72 Your proposition simply does not work - see: https://github.com/pmem/fio/blob/rpma/memory.c#L312:

```
	/*
	 * If the IO engine has hooks to allocate/free memory, use those. But
	 * error out if the user explicitly asked for something else.
	 */
	if (td->io_ops->iomem_alloc) {
		if (fio_option_is_set(&td->o, mem_type)) {
			log_err("fio: option 'mem/iomem' conflicts with specified IO engine\n");
			ret = 1;
		} else
			ret = td->io_ops->iomem_alloc(td, total_mem);
```

When the `iomem_alloc` hook is set and the `mem_type` option is set, fio exits with the error:

`fio: option 'mem/iomem' conflicts with specified IO engine`

and the `iomem_alloc` hook is not called.
___
*[engines/librpma.c, line 1142 at r10](https://reviewable.io/reviews/pmem/fio/36#-MKkktnF-S2pW2YLpLWS:-MKkwW3E4XsKKYJ7gR5P:bb6un1j) ([raw file](https://github.com/pmem/fio/blob/f7a3dc5ce5d5d6b8ea83f863bad92c6f0ee939ad/engines/librpma.c#L1142)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe the opposite condition with quick `return` will make more sense here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-10-28 20:55 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36#-:-MKkzab50lDqsxMRSNqv:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-10-28 20:55 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 22:17 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 22:19 UTC, merged