rpma: add write mode
pmem/fio pull request #38
Opened 2020-10-27 12:29 UTC by osalyk

2020-10-27 13:44 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 487 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeHkHe5xZ9mLa3GpC3:-MKeHkHe5xZ9mLa3GpC4:b-fg21r8) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L487)):*
> ```
> /* XXX - check the sequence */
> ```

What do you mean?
___
*[engines/librpma.c, line 489 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeHswvEtoXXWuxyFo-:-MKeHswvEtoXXWuxyFo0:bmc6fni) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L489)):*
> ```C
> 			/* XXX - check the sequence */
> 			/* post an RDMA write operation */
> 			flags = RPMA_F_COMPLETION_ON_ERROR;
> ```

It is already set in the line no. 466 above.
___
*[engines/librpma.c, line 493 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeI-wJ2Xq1T7r-wUjt:-MKeI-wJ2Xq1T7r-wUju:b2pjpmu) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L493)):*
> ```C
> 				return -1;
> 			if (i == cd->io_u_queued_nr - 1) {
> 				flags = RPMA_F_COMPLETION_ALWAYS;
> ```

It is already set in the line no. 480 above.
___
*[engines/librpma.c, line 494 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeIEz21UGyj6fdSWDC:-MKeIEz21UGyj6fdSWDD:b-xd11tb) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L494)):*
> ```
> if ((ret = rpma_flush(cd->conn, cd->server_mr,
> ```

Please use the:

```
ret = ...
if (ret) {
}
```

syntax here, the current one is unreadable.
___
*[engines/librpma.c, line 497 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeI4ueBy0s6o_5fiEP:-MKeI4ueBy0s6o_5fiEQ:bdsu830) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L497)):*
> ```
> 				io_u->offset, 0 /* XXX length of the sequence */,
> 				RPMA_FLUSH_TYPE_VISIBILITY, flags,
> 				(void *)(uintptr_t)io_u->index))) {
> ```

Wrong alignment


<!-- Sent from Reviewable.io -->

2020-10-27 14:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 490 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQOLGEI6rZ6L4K0rF:-MKeQOLGEI6rZ6L4K0rG:b-lt8y43) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L490)):*
> ```
> flags
> ```

RPMA_F_COMPLETION_ON_ERROR
___
*[engines/librpma.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQ5_A5oCzbfr47Une:-MKeQ5_A5oCzbfr47Unf:b-k3hpbq) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L496)):*
> ```
> RPMA_FLUSH_TYPE_VISIBILITY
> ```

RPMA_FLUSH_TYPE_PERSISTENT
___
*[engines/librpma.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQUpnD2ASi9aJKFAJ:-MKeQUpnD2ASi9aJKFAK:b-ab2pd8) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L496)):*
> ```
> flags
> ```

RPMA_F_COMPLETION_ALWAYS


<!-- Sent from Reviewable.io -->

2020-10-28 10:02 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 490 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQOLGEI6rZ6L4K0rF:-MKid_RT2wHAeEGkafyV:b-eb9pdo) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L490)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> flags
> ```

RPMA_F_COMPLETION_ON_ERROR
</blockquote></details>

I mean it can be just like that:

```
if ((ret = client_io_write(td, io_u, RPMA_F_COMPLETION_ON_ERROR)))
```
___
*[engines/librpma.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQUpnD2ASi9aJKFAJ:-MKidzG5Dg112aoB4hBO:bfafpl9) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L496)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> flags
> ```

RPMA_F_COMPLETION_ALWAYS
</blockquote></details>

I mean it can be just like that:

```
RPMA_FLUSH_TYPE_PERSISTENT, RPMA_F_COMPLETION_ALWAYS,
```


<!-- Sent from Reviewable.io -->

2020-10-28 10:47 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MKioNZM8uxJVnavFGFP:-MKioNZM8uxJVnavFGFQ:b-x8a2di) (no related file):*
Please rebase and undraft.

---


<!-- Sent from Reviewable.io -->

2020-10-28 11:18 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MKioNZM8uxJVnavFGFP:-MKiv_IqA-0pFxd7GP5E:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase and undraft.
</blockquote></details>

Done.

---
___
*[engines/librpma.c, line 487 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeHkHe5xZ9mLa3GpC3:-MKitTuuAcLgkF9TLeyH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L487)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* XXX - check the sequence */
> ```

What do you mean?
</blockquote></details>

Done.
___
*[engines/librpma.c, line 489 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeHswvEtoXXWuxyFo-:-MKithuG4kcwCt_Er1EZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L489)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is already set in the line no. 466 above.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 490 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQOLGEI6rZ6L4K0rF:-MKitsDhAE3PWhw30lbp:bd3zxh3) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L490)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I mean it can be just like that:

```
if ((ret = client_io_write(td, io_u, RPMA_F_COMPLETION_ON_ERROR)))
```
</blockquote></details>

If we have a variable flags, let's use it.
___
*[engines/librpma.c, line 493 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeI-wJ2Xq1T7r-wUjt:-MKiuHzB5hMVsytVRMH-:bq8rxsz) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L493)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is already set in the line no. 480 above.
</blockquote></details>

No longer
___
*[engines/librpma.c, line 494 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeIEz21UGyj6fdSWDC:-MKiuQAJCbSl5-xOp3B1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L494)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if ((ret = rpma_flush(cd->conn, cd->server_mr,
> ```

Please use the:

```
ret = ...
if (ret) {
}
```

syntax here, the current one is unreadable.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQ5_A5oCzbfr47Une:-MKiuUkd-glAIwUAA90G:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L496)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_FLUSH_TYPE_VISIBILITY
> ```

RPMA_FLUSH_TYPE_PERSISTENT
</blockquote></details>

Done.
___
*[engines/librpma.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQUpnD2ASi9aJKFAJ:-MKiuWi84-j9zPw_ugq_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L496)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I mean it can be just like that:

```
RPMA_FLUSH_TYPE_PERSISTENT, RPMA_F_COMPLETION_ALWAYS,
```

</blockquote></details>

Done.
___
*[engines/librpma.c, line 497 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeI4ueBy0s6o_5fiEP:-MKiuyQD1Si96LejNnNI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L497)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 				io_u->offset, 0 /* XXX length of the sequence */,
> 				RPMA_FLUSH_TYPE_VISIBILITY, flags,
> 				(void *)(uintptr_t)io_u->index))) {
> ```

Wrong alignment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 11:24 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 490 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQOLGEI6rZ6L4K0rF:-MKiwgq6EQ1gCo9KPBaO:baqfd9u) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L490)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

If we have a variable flags, let's use it.
</blockquote></details>

But if it should ALWAYS be equal `RPMA_F_COMPLETION_ON_ERROR` than we should use the constant, not the variable.
___
*[engines/librpma.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQUpnD2ASi9aJKFAJ:-MKiwbaZ6Yod3rpHdrKF:br7sr4m) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L496)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet


<!-- Sent from Reviewable.io -->

2020-10-28 11:32 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 490 at r1](https://reviewable.io/reviews/pmem/fio/38#-MKeQOLGEI6rZ6L4K0rF:-MKiyPes6iJY_3ya5WdJ:b-bw1n6h) ([raw file](https://github.com/pmem/fio/blob/1caec6458ebfd604729452c80f1162798c13e83b/engines/librpma.c#L490)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But if it should ALWAYS be equal `RPMA_F_COMPLETION_ON_ERROR` than we should use the constant, not the variable.
</blockquote></details>

ok, right


<!-- Sent from Reviewable.io -->

2020-10-28 11:34 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 11:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 532 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKizeJm916U_jNQEDlO:-MKizeJn3DP9j-ndvtlt:b-2330lg) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L532)):*
> ```
>  0 /* XXX length of all write */,
> ```

@janekmi Should it be `io_u->xfer_buflen` ?


<!-- Sent from Reviewable.io -->

2020-10-28 14:33 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MKjXjVgAx5Vqdtv47Uu:-MKjXjVh63Q5E4mEAA0Z:b-ocplu5) (no related file):*
> ```
> DDIR_WRITE
> ```
shall we check at startup/init if we allowed executing flush to pmem?

---
___
*[engines/librpma.c, line 533 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKjYxsFEa-kmnRJ4BDy:-MKjYxsFEa-kmnRJ4BDz:b-go8agb) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L533)):*
> ```
> RPMA_FLUSH_TYPE_PERSISTENT
> ```
would it be better to take possible flush from server_mr and based on peer cfg?
by the way, @janekmi  do we have space to pass peer cfg from server to client?
see: rpma_mr_remote_get_flush_type(), rpma_peer_cfg_get_direct_write_to_pmem() in example05/07


<!-- Sent from Reviewable.io -->

2020-10-29 08:13 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[engines/librpma.c, line 532 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKizeJm916U_jNQEDlO:-MKnP5Y98n8OV5nCPtNF:b-r75xr1) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L532)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  0 /* XXX length of all write */,
> ```

@janekmi Should it be `io_u->xfer_buflen` ?
</blockquote></details>

will be in  PR #43 
___
*[engines/librpma.c, line 533 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKjYxsFEa-kmnRJ4BDy:-MKnPK4R24RnlWgbIBIf:bsdf4qy) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L533)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_FLUSH_TYPE_PERSISTENT
> ```
would it be better to take possible flush from server_mr and based on peer cfg?
by the way, @janekmi  do we have space to pass peer cfg from server to client?
see: rpma_mr_remote_get_flush_type(), rpma_peer_cfg_get_direct_write_to_pmem() in example05/07
</blockquote></details>

As far as I know, there is no space in private_data.
We operate on the basis of assumption.


<!-- Sent from Reviewable.io -->

2020-10-29 08:15 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 533 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKjYxsFEa-kmnRJ4BDy:-MKnPyR8ChyzBjkdl-Yl:brrmaoz) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L533)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

As far as I know, there is no space in private_data.
We operate on the basis of assumption.
</blockquote></details>

at least rpma_mr_remote_get_flush_type() either we could use RPMA_FLUSH_TYPE_PERSISTENT or RPMA_FLUSH_TYPE_VISIBILITY


<!-- Sent from Reviewable.io -->

2020-10-29 08:44 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MKjXjVgAx5Vqdtv47Uu:-MKnWxnmALCFf-l0Vi4q:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> DDIR_WRITE
> ```
shall we check at startup/init if we allowed executing flush to pmem?
</blockquote></details>

Done.

---
___
*[engines/librpma.c, line 533 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKjYxsFEa-kmnRJ4BDy:-MKnWvJH4sd_97EiS2A6:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L533)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

at least rpma_mr_remote_get_flush_type() either we could use RPMA_FLUSH_TYPE_PERSISTENT or RPMA_FLUSH_TYPE_VISIBILITY
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 10:01 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma.c, line 547 at r4](https://reviewable.io/reviews/pmem/fio/38#-MKn_76T8dFifRanM4Ih:-MKn_76T8dFifRanM4Ii:bsscubr) ([raw file](https://github.com/pmem/fio/blob/d391cccc171546efbeda16efd8b6390cc745de1c/engines/librpma.c#L547)):*
> ```C
> 		flush_type = RPMA_FLUSH_TYPE_PERSISTENT;
> 	else
> 		flush_type = RPMA_FLUSH_TYPE_VISIBILITY;
> ```

All of this should be part of `client_init()`. TBH you probably even take it to another PR since it should also affect the synchronous path.


<!-- Sent from Reviewable.io -->

2020-10-29 10:16 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 547 at r4](https://reviewable.io/reviews/pmem/fio/38#-MKn_76T8dFifRanM4Ih:-MKnr-_hCdO5IpxPPZmZ:bpuigrs) ([raw file](https://github.com/pmem/fio/blob/d391cccc171546efbeda16efd8b6390cc745de1c/engines/librpma.c#L547)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All of this should be part of `client_init()`. TBH you probably even take it to another PR since it should also affect the synchronous path.
</blockquote></details>

Done in PR #45


<!-- Sent from Reviewable.io -->

2020-10-29 10:48 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-29 11:13 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 532 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKizeJm916U_jNQEDlO:-MKo2vimE1HROP6E77lH:b-1zqzyc) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L532)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

will be in  PR #43 
</blockquote></details>

Why cannot it be set to the correct value here?


<!-- Sent from Reviewable.io -->

2020-10-29 12:12 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 532 at r3](https://reviewable.io/reviews/pmem/fio/38#-MKizeJm916U_jNQEDlO:-MKoGTJw61qhPb-Z9T34:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d494a5f55fd068169434744c1c0aec2b6c999aa6/engines/librpma.c#L532)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why cannot it be set to the correct value here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 12:46 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-29 12:46 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-29 15:27 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-MKovwhs-UGEbGpglXDq:b-1e4zk4) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
> ```C
> 				return -1;
> 		} else if (io_u->ddir == DDIR_WRITE) {
> 			/* XXX - random read/write */
> ```

Please take this comment above the `if`.
```
XXX this implementation work only for readwrite=read,write
- to support readwrite=rw it has to consider interlaced sequences of reads and writes
- to support readwrite=randwrite,randrw it has to consider flush_len for nonadjacent writes
```
___
*[engines/librpma.c, line 547 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovXRr7e3a0jtoPVH4:-MKovXRr7e3a0jtoPVH5:bb9a1uj) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L547)):*
> ```C
> 				return -1;
> 			flush_len += io_u->xfer_buflen;
> 			if (i == cd->io_u_queued_nr - 1) {
> ```

I think it will be easier to follow with something like:
```c
if (i < cd->io_u_queued_nr - 1)
    continue;
```


<!-- Sent from Reviewable.io -->

2020-10-29 15:27 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-10-30 07:14 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-MKsKBq-3rZb75y4RSO0:b-896fix) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please take this comment above the `if`.
```
XXX this implementation work only for readwrite=read,write
- to support readwrite=rw it has to consider interlaced sequences of reads and writes
- to support readwrite=randwrite,randrw it has to consider flush_len for nonadjacent writes
```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 547 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovXRr7e3a0jtoPVH4:-MKsL6dKDGOabMWW4QGh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L547)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be easier to follow with something like:
```c
if (i < cd->io_u_queued_nr - 1)
    continue;
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-30 07:38 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 570 at r6](https://reviewable.io/reviews/pmem/fio/38#-MKsQqkzBxXJvl8kikZL:-MKsQql-9HZkULjWjCP8:b-pw2r5i) ([raw file](https://github.com/pmem/fio/blob/624e4b1ffe6ffebb5b16eb1720eda0d78ef50675/engines/librpma.c#L570)):*
> ```
> work
> ```

works


<!-- Sent from Reviewable.io -->

2020-10-30 07:39 UTC, ldorau reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38#-:-MKsRcsr7ufiL5OqPpxH:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-10-30 07:55 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 570 at r6](https://reviewable.io/reviews/pmem/fio/38#-MKsQqkzBxXJvl8kikZL:-MKsV6zHDrj98ZJUiNhz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/624e4b1ffe6ffebb5b16eb1720eda0d78ef50675/engines/librpma.c#L570)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> work
> ```

works
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-30 08:43 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-02 10:58 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-ML7ajXW5H_p52-ZOynS:bihajgu) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
> this implementation work only for readwrite=read,write
shall we add this filter to init()?


<!-- Sent from Reviewable.io -->

2020-11-02 11:08 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-ML7czJZ7oDjT-7kqmlo:bvilotx) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
> add this filter to init()?

What do you mean by "add this filter to init()" ?


<!-- Sent from Reviewable.io -->

2020-11-02 11:43 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-ML7ktlD7c_p77wMTGXp:brlwcep) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> add this filter to init()?

What do you mean by "add this filter to init()" ?
</blockquote></details>

we only support now  "readwrite=read, write" what if somebody put here another type of workload?


<!-- Sent from Reviewable.io -->

2020-11-02 11:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-ML7mUJu8pZwoQ61cmUe:b-ub53yl) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we only support now  "readwrite=read, write" what if somebody put here another type of workload?
</blockquote></details>

Yes, you are right.

@osalyk such check should be added


<!-- Sent from Reviewable.io -->

2020-11-03 07:11 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 542 at r5](https://reviewable.io/reviews/pmem/fio/38#-MKovwhs-UGEbGpglXDp:-MLBwUN22zOme6C_nLOo:b-896fix) ([raw file](https://github.com/pmem/fio/blob/711115cfe238fb1d2a6f062cb5d700d5ac538a9b/engines/librpma.c#L542)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, you are right.

@osalyk such check should be added
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-03 10:52 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MLCj7px5kR05E03V2ts:-MLCj7px5kR05E03V2tt:bd7aj1p) (no related file):*
To be merged when sync implementation will be working correctly.

---


<!-- Sent from Reviewable.io -->

2020-11-03 12:25 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38#-:-MLD3Ni8CzdOlK8BMBn0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2020-11-03 13:02 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 128 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLDBXwc3UuBtrxkdwRd:-MLDBXwd-bZov0C3HPVl:b-dsbiqt) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L128)):*
> ```C
> 	/* XXX not supported readwrite= rw/randwrite/randrw */
> 	if (td_random(td) || td_rw(td)) {
> 		log_err("Not supported mode. ");
> ```

Can this message be more verbose? What non-supported mode was set here and what modes are supported ?


<!-- Sent from Reviewable.io -->

2020-11-03 13:02 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-11-03 13:12 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[engines/librpma.c, line 128 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLDBXwc3UuBtrxkdwRd:-MLDE0TO8fj8S0GdlVyy:b29htij) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L128)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Can this message be more verbose? What non-supported mode was set here and what modes are supported ?
</blockquote></details>

In the next PR we remove this condition. 


<!-- Sent from Reviewable.io -->

2020-11-03 13:59 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 128 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLDBXwc3UuBtrxkdwRd:-MLDOpJm11cgXxvcRkXl:b32w0x) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L128)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

In the next PR we remove this condition. 
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2020-11-04 13:51 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 581 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLIOfpgBd8PBAfrSlfa:-MLIOfpgBd8PBAfrSlfb:b-fuhozp) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L581)):*
> ```C
>  * - to support readwrite=randwrite,randrw it has to consider
>  *   flush_len for nonadjacent writes
>  */
> ```

Indentation?


<!-- Sent from Reviewable.io -->

2020-11-04 14:07 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MLI_Hia3puxFXrbeRHP:-MLI_Hia3puxFXrbeRHQ:b-gazutd) (no related file):*
Please set sq_size according to the async write implementation you are introducing.

---


<!-- Sent from Reviewable.io -->

2020-11-05 07:38 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/38#-MLI_Hia3puxFXrbeRHP:-MLMKg6UAYjTkxrAF5W1:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please set sq_size according to the async write implementation you are introducing.
</blockquote></details>

Done.

---
___
*[engines/librpma.c, line 581 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLIOfpgBd8PBAfrSlfa:-MLMKeyYAgkhyf6it__4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L581)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 08:28 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 581 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLIOfpgBd8PBAfrSlfa:-MLMU8miDOdpjcMIuHpe:bmrm7ff) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L581)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi Is it really what you meant? This is the first time I see such formatting (tabs after asterisks in the comment). IMHO the previous formatting was the correct one:

```
/*
 * XXX this implementation works only for readwrite=read,write
 * - to support readwrite=rw it has to consider interlaced sequences
 *   of reads and writes
 * - to support readwrite=randwrite,randrw it has to consider
 *   flush_len for nonadjacent writes
 */
```

The current one looks strange for me:

```
/*
 * XXX this implementation works only for readwrite=read,write
 *	- to support readwrite=rw it has to consider interlaced sequences
 *	of reads and writes
 *	- to support readwrite=randwrite,randrw it has to consider
 *	flush_len for nonadjacent writes
 */
```
 
___
*[engines/librpma.c, line 182 at r9](https://reviewable.io/reviews/pmem/fio/38#-MLMVS2h2fb4MP4b4MTE:-MLMVS2h2fb4MP4b4MTF:by7o7y5) ([raw file](https://github.com/pmem/fio/blob/682eaa5d5c9f850e6a5939a193a29ab11cdb4e13/engines/librpma.c#L182)):*
> ```
> 	/* N x WRITE + N x FLUSH */
> 	sq_size = td->o.iodepth +
> 		td->o.iodepth / td->o.iodepth_batch + 1;
> ```

To be honest, I don't understand why:

```
sq_size = td->o.iodepth + td->o.iodepth / td->o.iodepth_batch + 1;
```

is a correct formula for `/* N x WRITE + N x FLUSH */` ? - could you explain it better in a comment here?


<!-- Sent from Reviewable.io -->

2020-11-05 13:23 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 182 at r9](https://reviewable.io/reviews/pmem/fio/38#-MLMVS2h2fb4MP4b4MTE:-MLNZsvr0ODa1Jl44TpK:b-896fix) ([raw file](https://github.com/pmem/fio/blob/682eaa5d5c9f850e6a5939a193a29ab11cdb4e13/engines/librpma.c#L182)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* N x WRITE + N x FLUSH */
> 	sq_size = td->o.iodepth +
> 		td->o.iodepth / td->o.iodepth_batch + 1;
> ```

To be honest, I don't understand why:

```
sq_size = td->o.iodepth + td->o.iodepth / td->o.iodepth_batch + 1;
```

is a correct formula for `/* N x WRITE + N x FLUSH */` ? - could you explain it better in a comment here?

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 14:17 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 581 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLIOfpgBd8PBAfrSlfa:-MLNeKK3E_xXxNGB8CDJ:bxw7ler) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L581)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi Is it really what you meant? This is the first time I see such formatting (tabs after asterisks in the comment). IMHO the previous formatting was the correct one:

```
/*
 * XXX this implementation works only for readwrite=read,write
 * - to support readwrite=rw it has to consider interlaced sequences
 *   of reads and writes
 * - to support readwrite=randwrite,randrw it has to consider
 *   flush_len for nonadjacent writes
 */
```

The current one looks strange for me:

```
/*
 * XXX this implementation works only for readwrite=read,write
 *	- to support readwrite=rw it has to consider interlaced sequences
 *	of reads and writes
 *	- to support readwrite=randwrite,randrw it has to consider
 *	flush_len for nonadjacent writes
 */
```
 
</blockquote></details>

I mean the whole block should be indented by 3x tabs.
___
*[engines/librpma.c, line 182 at r9](https://reviewable.io/reviews/pmem/fio/38#-MLMVS2h2fb4MP4b4MTE:-MLNjvCL7PD545riCgC9:ba3f35x) ([raw file](https://github.com/pmem/fio/blob/682eaa5d5c9f850e6a5939a193a29ab11cdb4e13/engines/librpma.c#L182)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe go with something like:

```c
/*
 * N * WRITE + B * FLUSH where:
 * - B == ceil(iodepth / iodepth_batch) ~= iodepth / iodepth_batch + 1
 *   which is the number of batches for N writes
 */
```


<!-- Sent from Reviewable.io -->

2020-11-05 14:23 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[engines/librpma.c, line 127 at r10](https://reviewable.io/reviews/pmem/fio/38#-MLNlaiL7RyeXtN2d9n5:-MLNlaiL7RyeXtN2d9n6:b-4c96w2) ([raw file](https://github.com/pmem/fio/blob/d1e0bf3d058ed953983af02704d261fb2b4971eb/engines/librpma.c#L127)):*
> ```C
> 	rpma_log_set_threshold(RPMA_LOG_THRESHOLD_AUX, RPMA_LOG_LEVEL_ERROR);
> 
> 	/* XXX not supported readwrite= rw/randwrite/randrw */
> ```

The space after the equal sign seems weird.
___
*[engines/librpma.c, line 129 at r10](https://reviewable.io/reviews/pmem/fio/38#-MLNlmQb9CR3Jw9rSILL:-MLNlmQb9CR3Jw9rSILM:bsas6jc) ([raw file](https://github.com/pmem/fio/blob/d1e0bf3d058ed953983af02704d261fb2b4971eb/engines/librpma.c#L129)):*
> ```C
> 	/* XXX not supported readwrite= rw/randwrite/randrw */
> 	if (td_random(td) || td_rw(td)) {
> 		log_err("Not supported mode. ");
> ```

` ` -> `\n`
___
*[engines/librpma.c, line 179 at r10](https://reviewable.io/reviews/pmem/fio/38#-MLNmU9l90cEkGpJtDjM:-MLNmU9m3KPZ_sxrBltd:b7cw9ig) ([raw file](https://github.com/pmem/fio/blob/d1e0bf3d058ed953983af02704d261fb2b4971eb/engines/librpma.c#L179)):*
> ```C
> 		if (td->o.sync_io)
> 			sq_size = 2; /* WRITE + FLUSH */
> 		else {
> ```

I recommend adding braces `{}` for all if-else cases if any of them needs them.


<!-- Sent from Reviewable.io -->

2020-11-05 14:31 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 129 at r10](https://reviewable.io/reviews/pmem/fio/38#-MLNlmQb9CR3Jw9rSILL:-MLNnhL64hsnhg6bPxy3:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1e0bf3d058ed953983af02704d261fb2b4971eb/engines/librpma.c#L129)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

` ` -> `\n`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 179 at r10](https://reviewable.io/reviews/pmem/fio/38#-MLNmU9l90cEkGpJtDjM:-MLNo1uHC3QJ4CR2cQy4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1e0bf3d058ed953983af02704d261fb2b4971eb/engines/librpma.c#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend adding braces `{}` for all if-else cases if any of them needs them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 14:40 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38#-:-MLNqavWEhFohDBW7BvO:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2020-11-05 15:04 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[engines/librpma.c, line 581 at r8](https://reviewable.io/reviews/pmem/fio/38#-MLIOfpgBd8PBAfrSlfa:-MLNvjkJ09UqJ_ODL8Y-:bemrylj) ([raw file](https://github.com/pmem/fio/blob/389e85a6e455a89cf8a1f0c8c05bfcb95578f5df/engines/librpma.c#L581)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I mean the whole block should be indented by 3x tabs.
</blockquote></details>

Oh, yes, of course :-D I didn't notice that :-D
___
*[engines/librpma.c, line 182 at r9](https://reviewable.io/reviews/pmem/fio/38#-MLMVS2h2fb4MP4b4MTE:-MLNw00R-XBPsNnzhDc8:b-ucfknh) ([raw file](https://github.com/pmem/fio/blob/682eaa5d5c9f850e6a5939a193a29ab11cdb4e13/engines/librpma.c#L182)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe go with something like:

```c
/*
 * N * WRITE + B * FLUSH where:
 * - B == ceil(iodepth / iodepth_batch) ~= iodepth / iodepth_batch + 1
 *   which is the number of batches for N writes
 */
```
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2020-11-05 15:04 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/38#-:-MLNw3Nw3Rz1FOer6HIo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 15:05 UTC, merged