Rpma client multi
pmem/fio pull request #40
Opened 2020-10-27 13:25 UTC by janekmi

Requires:

- [ ] #37

2020-10-27 20:36 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKenusl8bQsv5ywKJAF:-MKenusl8bQsv5ywKJAG:b5np6y) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L30)):*
> ```
> rdma_connect
> ```
are we limited by rdma_connect or by rdma_accept?
___
*[engines/librpma.c, line 93 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKen6XV6whfnJafZaAH:-MKen6XV6whfnJafZaAI:b8rww5v) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L93)):*
> ```
> wspace
> ```
I do not like "wsparcie" ;) 
what about workspace  or ws
___
*[engines/librpma.c, line 916 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfjWLdCysFHHwTTuBj:-MKfjWLeDmocLJ_UTaW4:b-xebn8a) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L916)):*
> ```
> init
> ```
establish
___
*[engines/librpma.c, line 961 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfjamg7tKbLg022UB1:-MKfjamg7tKbLg022UB2:b-unziv9) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L961)):*
> ```
> cleanup
> ```
shutdown
___
*[engines/librpma.c, line 990 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfjsBF3bHNF9209Xk0:-MKfjsBF3bHNF9209Xk1:bl1k4ps) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L990)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	/* prepare space for connection objects */
> 	conns = calloc(o->num_conns, sizeof(struct rpma_conn *));
> 	if (conns == NULL) {
> 		td->terminate = true;
> 		return FIO_Q_COMPLETED;
> 	}
> ```
</details>

shall this be moved to post_init?
___
*[engines/librpma.c, line 1002 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfl4E11MJFMMJ5006Z:-MKfl4E28VuCnTzX52nu:bez7dyl) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L1002)):*
> ```
> break
> ```
shall we force the server part to close all connections in case of any error?
present implementation waits for clients to disconnect.
___
*[engines/librpma.c, line 1013 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKflV4F5YLY7i9doG2g:-MKflV4F5YLY7i9doG2h:bnw39tj) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L1013)):*
> ```
> free(conns);
> ```
a part of server cleanup?
___
*[examples/librpma-client.fio, line 16 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKeoT7D7yC1X5CBBCvQ:-MKeoT7D7yC1X5CBBCvR:bxycz0b) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-client.fio#L16)):*
> ```
> [client]
> ```
is this still async version?


<!-- Sent from Reviewable.io -->

2020-10-27 20:37 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 18 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfldUG9Q7ak_rVGsea:-MKfldUH8VKffvjRkrfM:bz37tsk) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-client.fio#L18)):*
> ```
> [client]
> create_serialize=0
> numjobs=1
> ```

does it mean that we can use more than one job here?


<!-- Sent from Reviewable.io -->

2020-10-28 08:27 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKenusl8bQsv5ywKJAF:-MKiH4uv7quifEgx-Gne:br1gm2i) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L30)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rdma_connect
> ```
are we limited by rdma_connect or by rdma_accept?
</blockquote></details>

The comment from our example has luckily preserved this information for future generations, the limit comes from `rdma_connect()`.
___
*[engines/librpma.c, line 93 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKen6XV6whfnJafZaAH:-MKiIEVN-ijQsHe9OVbZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L93)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> wspace
> ```
I do not like "wsparcie" ;) 
what about workspace  or ws
</blockquote></details>

Done.
___
*[engines/librpma.c, line 916 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfjWLdCysFHHwTTuBj:-MKiIHeR246sx1pqD6TG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L916)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> init
> ```
establish
</blockquote></details>

Done.
___
*[engines/librpma.c, line 961 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfjamg7tKbLg022UB1:-MKiII418lap3gWxnQAW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L961)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> cleanup
> ```
shutdown
</blockquote></details>

Done.
___
*[engines/librpma.c, line 990 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfjsBF3bHNF9209Xk0:-MKiIMwY5zucMhjH6BtS:b-ovdyc5) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L990)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	/* prepare space for connection objects */
> 	conns = calloc(o->num_conns, sizeof(struct rpma_conn *));
> 	if (conns == NULL) {
> 		td->terminate = true;
> 		return FIO_Q_COMPLETED;
> 	}
> ```
shall this be moved to post_init?
</blockquote></details>

This array is completely local.
___
*[engines/librpma.c, line 1013 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKflV4F5YLY7i9doG2g:-MKiIZytCBlOShNtCNxF:bzgw65n) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L1013)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> free(conns);
> ```
a part of server cleanup?
</blockquote></details>

A local array. No point.
___
*[examples/librpma-client.fio, line 16 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKeoT7D7yC1X5CBBCvQ:-MKiIggE36P5AqsLepbV:b-hyjap4) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-client.fio#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> [client]
> ```
is this still async version?
</blockquote></details>

As long as you won't use `sync=1` you are working asynchronously.
___
*[examples/librpma-client.fio, line 18 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfldUG9Q7ak_rVGsea:-MKiIs9E8mLTRXxbJ7vP:blb1jy) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-client.fio#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

does it mean that we can use more than one job here?
</blockquote></details>

This is the whole point of making the client multithreading-capable. Don't you think? ;-)


<!-- Sent from Reviewable.io -->

2020-10-28 08:33 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 1002 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfl4E11MJFMMJ5006Z:-MKiKghD8y_Q18WnE-e3:be7pvdn) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L1002)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> break
> ```
shall we force the server part to close all connections in case of any error?
present implementation waits for clients to disconnect.
</blockquote></details>

I think we should. I will prepare another PR for this.


<!-- Sent from Reviewable.io -->

2020-10-28 10:38 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 225 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKiiQHS67vmuV_r2PXC:-MKiiQHTA3PYUMnNX5T4:b-ba9zke) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L225)):*
> ```
> 		goto err_conn_delete;
> 	cd->ws = pdata.ptr;
> ```

Add one empty line between, please
___
*[engines/librpma.c, line 229 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKilpQW9BX_z_UHv4YI:-MKilpQW9BX_z_UHv4YJ:bika04a) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L229)):*
> ```C
> 	/* validate the received workspace size */
> 	if (cd->ws->size < td->o.size) {
> 		td_vmsg(td, ENOMEM, "received workspace size is too small",
> ```

It would be very helpful to print out the value of the minimum required size.
___
*[engines/librpma.c, line 249 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKimQ2U-atNzmAAMg-h:-MKimQ2U-atNzmAAMg-i:b3kqx) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L249)):*
> ```C
> 	if (cd->ws_offset > server_mr_size ||
> 			cd->ws_offset + cd->ws->size > server_mr_size) {
> 		td_vmsg(td, ENOMEM, "received workspace is too small",
> ```

.


<!-- Sent from Reviewable.io -->

2020-10-28 11:01 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKenusl8bQsv5ywKJAF:-MKiXSIw45rDv1rQPxi6:b-ww22tn) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The comment from our example has luckily preserved this information for future generations, the limit comes from `rdma_connect()`.
</blockquote></details>

does it mean that we have more space? I would rather prefer to have a particular client offset and size calculated on the server-side.
___
*[engines/librpma.c, line 803 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKiHtNP2u1inPuwQ5jG:-MKiHtNP2u1inPuwQ5jH:bx0c80p) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L803)):*
> ```
> td->o.max_bs[DDIR_READ] = td->o.size
> ```
my proposal is:
o.size - the total size that server used for all connection
o.iodept = 1 io_u <-> ep (listen one) 
___
*[engines/librpma.c, line 889 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKiLVX5DnTbbif0SjLO:-MKiLVX5DnTbbif0SjLP:b54inp7) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L889)):*
> ```
> prepare a workspace description
> ```
I do not like the solution that it is the same record for every client
___
*[examples/librpma-client.fio, line 18 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKfldUG9Q7ak_rVGsea:-MKiKBtJAvNZ5r40Cfp3:b32w0x) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-client.fio#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is the whole point of making the client multithreading-capable. Don't you think? ;-)
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2020-10-28 11:07 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 225 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKiiQHS67vmuV_r2PXC:-MKiq6lS5GC-1F_LlQNT:b-896fix) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L225)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		goto err_conn_delete;
> 	cd->ws = pdata.ptr;
> ```

Add one empty line between, please
</blockquote></details>

Done.
___
*[engines/librpma.c, line 229 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKilpQW9BX_z_UHv4YI:-MKiqtVTBCVCKTD1iom9:b-896fix) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L229)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It would be very helpful to print out the value of the minimum required size.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 249 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKimQ2U-atNzmAAMg-h:-MKit-SG7VlG_ZIJT6Uo:b-896fix) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L249)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 11:10 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 252 at r3](https://reviewable.io/reviews/pmem/fio/40#-MKitb1J6MwrKnVv0QJm:-MKitb1J6MwrKnVv0QJn:bugtwu5) ([raw file](https://github.com/pmem/fio/blob/c6b2a618c89b3b8b338c27a76c5a6637fcf0bdd6/engines/librpma.c#L252)):*
> ```
>  < 
> ```

`>`
___
*[engines/librpma.c, line 257 at r3](https://reviewable.io/reviews/pmem/fio/40#-MKitfDK3Gevhhwb8s7q:-MKitfDK3Gevhhwb8s7r:b-ej1xav) ([raw file](https://github.com/pmem/fio/blob/c6b2a618c89b3b8b338c27a76c5a6637fcf0bdd6/engines/librpma.c#L257)):*
> ```
>  < 
> ```

.


<!-- Sent from Reviewable.io -->

2020-10-28 11:11 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKenusl8bQsv5ywKJAF:-MKitE5X27N81aSoeWqq:b856msa) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L30)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

does it mean that we have more space? I would rather prefer to have a particular client offset and size calculated on the server-side.
</blockquote></details>

Yeah, you are right. It may be something we can consider for the next sprint.
___
*[engines/librpma.c, line 252 at r3](https://reviewable.io/reviews/pmem/fio/40#-MKitb1J6MwrKnVv0QJm:-MKityKY9-jTh2yKyKyh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c6b2a618c89b3b8b338c27a76c5a6637fcf0bdd6/engines/librpma.c#L252)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  < 
> ```

`>`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 257 at r3](https://reviewable.io/reviews/pmem/fio/40#-MKitfDK3Gevhhwb8s7q:-MKitycJ0RpLBXzwPFD5:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c6b2a618c89b3b8b338c27a76c5a6637fcf0bdd6/engines/librpma.c#L257)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  < 
> ```

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 11:16 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKenusl8bQsv5ywKJAF:-MKiueyQ7BQWFoJsTatg:b4qfrty) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah, you are right. It may be something we can consider for the next sprint.
</blockquote></details>

Because it includes an experimental detection of what the limit is for the `rdma_accept()`.
___
*[engines/librpma.c, line 803 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKiHtNP2u1inPuwQ5jG:-MKiu3Rt8Othj4wcgkEz:b-mivlg5) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L803)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> td->o.max_bs[DDIR_READ] = td->o.size
> ```
my proposal is:
o.size - the total size that server used for all connection
o.iodept = 1 io_u <-> ep (listen one) 

</blockquote></details>

To be discussed in a separate PR.
___
*[engines/librpma.c, line 889 at r2](https://reviewable.io/reviews/pmem/fio/40#-MKiLVX5DnTbbif0SjLO:-MKiuDiU8ke-5xeqfFxI:b7ta8pq) ([raw file](https://github.com/pmem/fio/blob/522f39fe42d7c606fd9eadbe276c0142f7b05eb6/engines/librpma.c#L889)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> prepare a workspace description
> ```
I do not like the solution that it is the same record for every client
</blockquote></details>

If I understand correctly, I should consider this comment with the idea of calculating an offset for each client on the server-side.
It is an idea which we can discuss later.

Considering, the current architecture it makes sense to use the same structure.


<!-- Sent from Reviewable.io -->

2020-10-28 11:21 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-10-28 12:07 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 93 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKj5Lv2As65qTI6xD4P:-MKj5Lv2As65qTI6xD4Q:btvbns4) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L93)):*
> ```
> struct workspace *ws;
> ```
do we need the whole structure or only ws_size?


<!-- Sent from Reviewable.io -->

2020-10-28 12:31 UTC, grom72 reviewed
shall we split the librpma.c into two files?

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40#-:-MKj8ttO7XDX7OpYvpsj:bs4f80q)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 803 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKiHtNP2u1inPuwQ5jG:-MKj8cEt9lhBGk2Xf0oA:b-3iqdp) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L803)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To be discussed in a separate PR.
</blockquote></details>

but with this implementation, we have n-1 io_us that will not be used. Am I right?
___
*[engines/librpma.c, line 227 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKj5yXx7GNHibqRIZ6y:-MKj5yXyDoxRZklFh1m-:bn9uvxl) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L227)):*
> ```
> cd->ws = pdata.ptr;
> ```
```
struct workspace *ws  = pdata.ptr;
```
it is not needed to store the whole ws as part of cd
___
*[engines/librpma.c, line 406 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKj71mj6-yQqB6YKxMb:-MKj71mj6-yQqB6YKxMc:b-d3h2e8) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L406)):*
> ```
> 	struct fio_file *f = td->files[0];
> 	f->real_file_size = cd->ws->size;
> ```
```
td->files[0]->real_file_size = cd->ws->size;  //or just cd->ws_size
```
___
*[engines/librpma.c, line 406 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKjB2msB10jb6NFE3ZJ:-MKjB2msB10jb6NFE3ZK:bipk6vm) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L406)):*
> ```
> real_file_size
> ```
shall this be moved to .get_file_size hook?
___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKj8EBqCR1Obbotr8oO:bax9wgu) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
> ```
> iomem_align=[page size]
> ```
```
iomem_align=[page size e.g. 4096/...]
```
or
we need a huge manual ;)


<!-- Sent from Reviewable.io -->

2020-10-28 12:31 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 12:34 UTC, janekmi reviewed
Gosh... why? I thought we have already agreed, at least preliminary, to try to keep one file per engine (client+server). What made you start thinking about it?

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40#-:-MKjBSK7AfQSpQiZYzDa:bo0ydk1)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 93 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKj5Lv2As65qTI6xD4P:-MKjBpUy46vdeMFNzkV8:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L93)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct workspace *ws;
> ```
do we need the whole structure or only ws_size?

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 12:38 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 803 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKiHtNP2u1inPuwQ5jG:-MKjC28ZCs5gAtQepFUg:b1ldo4a) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L803)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but with this implementation, we have n-1 io_us that will not be used. Am I right?
</blockquote></details>

io_us yes. But by io_us I mean only `struct io_u` instances. The underlaying `orig_buffer` is used in its entirety.
___
*[engines/librpma.c, line 227 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKj5yXx7GNHibqRIZ6y:-MKjBt7F8TOpMSZrhwUa:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L227)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> cd->ws = pdata.ptr;
> ```
```
struct workspace *ws  = pdata.ptr;
```
it is not needed to store the whole ws as part of cd
</blockquote></details>

Done.
___
*[engines/librpma.c, line 406 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKj71mj6-yQqB6YKxMb:-MKjBv9PCOg9vJLMf4sJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L406)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	struct fio_file *f = td->files[0];
> 	f->real_file_size = cd->ws->size;
> ```
```
td->files[0]->real_file_size = cd->ws->size;  //or just cd->ws_size
```

</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjCVto7FDDYLv0NYcl:b-bibbo0) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> iomem_align=[page size]
> ```
```
iomem_align=[page size e.g. 4096/...]
```
or
we need a huge manual ;)
</blockquote></details>

I think we do not have to explain the concept of the page size. It should be obvious for any Linux administrator. If it is not you should not run the benchmark because the results will be crappy anyway.


<!-- Sent from Reviewable.io -->

2020-10-28 12:43 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 12:44 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 12:46 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 406 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKjB2msB10jb6NFE3ZJ:-MKjEfqo0VmUFy-9Kmw9:b5jgit) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L406)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> real_file_size
> ```
shall this be moved to .get_file_size hook?
</blockquote></details>

A neat idea.


<!-- Sent from Reviewable.io -->

2020-10-28 12:51 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-10-28 12:53 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 406 at r4](https://reviewable.io/reviews/pmem/fio/40#-MKjB2msB10jb6NFE3ZJ:-MKjFCigDWxqZebdZMHF:b-y8js7i) ([raw file](https://github.com/pmem/fio/blob/9776e833f57ef48d6f43e5e464303a15248f25b8/engines/librpma.c#L406)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A neat idea.
</blockquote></details>

let's use as many hooks as possible for better FIO understanding
___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjFTME5U2stwBf12mK:b-at0u8x) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we do not have to explain the concept of the page size. It should be obvious for any Linux administrator. If it is not you should not run the benchmark because the results will be crappy anyway.
</blockquote></details>

what values do we expect people to use here?


<!-- Sent from Reviewable.io -->

2020-10-28 12:56 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 13:48 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjSc523ui5pwUSJ-ZK:b-6ahbpz) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what values do we expect people to use here?
</blockquote></details>

I know at least three possible values: 4KiB, 2MiB, 1GiB.


<!-- Sent from Reviewable.io -->

2020-10-28 14:03 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjW-tz3MbqNlxn0sLF:b-tpd7bp) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know at least three possible values: 4KiB, 2MiB, 1GiB.
</blockquote></details>

so let's suggest them to avoid  wrong benchmark results due to the wrong page  size


<!-- Sent from Reviewable.io -->

2020-10-28 14:30 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 15:28 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjokdnEWuKvK9PE9EK:bqqonl6) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

so let's suggest them to avoid  wrong benchmark results due to the wrong page  size
</blockquote></details>

@janekmi here also?


<!-- Sent from Reviewable.io -->

2020-10-28 15:29 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-10-28 15:32 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjpX-g1eAx26-HOQ6U:bkmgz4q) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi here also?
</blockquote></details>

I think at some point we can just query the page size and set `iomem_align` by our selves. ;-)


<!-- Sent from Reviewable.io -->

2020-10-28 15:33 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKj8EBqCR1Obbotr8oN:-MKjpz3lAQ7WRYgbqDcK:bowo3b3) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think at some point we can just query the page size and set `iomem_align` by our selves. ;-)
</blockquote></details>

Yes, I agree


<!-- Sent from Reviewable.io -->

2020-10-28 16:03 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 803 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKiHtNP2u1inPuwQ5jG:-MKjwmUM2ZN51aMB_b17:b-em22qy) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L803)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

io_us yes. But by io_us I mean only `struct io_u` instances. The underlaying `orig_buffer` is used in its entirety.
</blockquote></details>

so it should be fixed before upstream 


<!-- Sent from Reviewable.io -->

2020-10-28 16:05 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 19:55 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 803 at r1](https://reviewable.io/reviews/pmem/fio/40#-MKiHtNP2u1inPuwQ5jG:-MKklRfTDSJALAjJ8_Sc:bgcu259) ([raw file](https://github.com/pmem/fio/blob/4141c23394609338838b010720ab2c7ac07183c2/engines/librpma.c#L803)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

so it should be fixed before upstream 
</blockquote></details>

Or we will learn that despite it is not ideal there is no better way to do this. ;-)
Nonetheless, it is not part of this PR. We should discuss the general direction offline.


<!-- Sent from Reviewable.io -->

2020-10-28 20:12 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-10-28 20:57 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40#-:-MKl-4V0CqslFuOigDPO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 21:14 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/40)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 22:18 UTC, merged