rpma: mix read/write
pmem/fio pull request #43
Opened 2020-10-29 08:07 UTC by osalyk

2020-10-29 08:18 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 550 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnQowj5fa802dPkpRp:-MKnQowk2dYMKSy63KYJ:bx60zyi) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L550)):*
> ```
> last_read -= 1;
> ```
last_read --;


<!-- Sent from Reviewable.io -->

2020-10-29 08:34 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 550 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnQowj5fa802dPkpRp:-MKnQvXqB3BANB6gAzw4:b3wz4to) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L550)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> last_read -= 1;
> ```
last_read --;
</blockquote></details>

or
(cd->io_us_queued[last_read--]->ddir == DDIR_READ);
___
*[engines/librpma.c, line 560 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnRrhG16vsHeHCdtpt:-MKnRrhG16vsHeHCdtpu:b-z3s5uo) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L560)):*
> ```
> flags = RPMA_F_COMPLETION_ALWAYS;
> ```
Completion not needed if we expect Flush to be sent after the Read command
___
*[engines/librpma.c, line 570 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnTHSJAgeIDCX5hzlB:-MKnTHSJAgeIDCX5hzlC:b84682v) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L570)):*
> ```
> rpma_flush
> ```
In the case of td_random, we should Flush only in one case (having in mind that read also force Flush of data):
at the end of the sequence, but only if we have any write already sent 
so basically the flush should be done only once after the whole sequence and only in the case when the Write was the last operation in a sequence


<!-- Sent from Reviewable.io -->

2020-10-29 08:35 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnUczvAE7gsf-ZVYuT:-MKnUczvAE7gsf-ZVYuU:b-xa31tg) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L551)):*
> ```
> while (cd->io_us_queued[last_read]->ddir == DDIR_READ);
> ```
while (!last_read || (cd->io_us_queued[last_read]->ddir == DDIR_READ));


<!-- Sent from Reviewable.io -->

2020-10-29 12:43 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 550 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnQowj5fa802dPkpRp:-MKoLu0r0mfwLE9i5ITW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L550)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

or
(cd->io_us_queued[last_read--]->ddir == DDIR_READ);

</blockquote></details>

Done.
___
*[engines/librpma.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnUczvAE7gsf-ZVYuT:-MKoM7Dr4NHUKLiGNSnj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L551)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> while (cd->io_us_queued[last_read]->ddir == DDIR_READ);
> ```
while (!last_read || (cd->io_us_queued[last_read]->ddir == DDIR_READ));
</blockquote></details>

Done.
___
*[engines/librpma.c, line 560 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnRrhG16vsHeHCdtpt:-MKoMnpE8CUpyPYAR4Wd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L560)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> flags = RPMA_F_COMPLETION_ALWAYS;
> ```
Completion not needed if we expect Flush to be sent after the Read command
</blockquote></details>

Done.
___
*[engines/librpma.c, line 570 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnTHSJAgeIDCX5hzlB:-MKoNEPyBk-Ht1gubzOv:bq3ac11) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_flush
> ```
In the case of td_random, we should Flush only in one case (having in mind that read also force Flush of data):
at the end of the sequence, but only if we have any write already sent 
so basically the flush should be done only once after the whole sequence and only in the case when the Write was the last operation in a sequence
</blockquote></details>

Then the len variable with rpma_flush() loses its meaning.


<!-- Sent from Reviewable.io -->

2020-10-29 14:46 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[engines/librpma.c, line 570 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnTHSJAgeIDCX5hzlB:-MKoofZk4Cb6U8OOK5dp:b-49phdf) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L570)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Then the len variable with rpma_flush() loses its meaning.
</blockquote></details>

what about only one unconditional Flush at the end?


<!-- Sent from Reviewable.io -->

2020-10-29 14:55 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 570 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnTHSJAgeIDCX5hzlB:-MKoqjt9DUF31VPICI3m:b-77rwgb) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about only one unconditional Flush at the end?
</blockquote></details>

It seems to me that we want to flush a particular piece of memory. If it is random, we cannot guarantee that the writes are next to each other so we flush each write


<!-- Sent from Reviewable.io -->

2020-10-30 06:54 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 570 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnTHSJAgeIDCX5hzlB:-MKsGR9x3jLslUkW8LGk:basy496) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L570)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It seems to me that we want to flush a particular piece of memory. If it is random, we cannot guarantee that the writes are next to each other so we flush each write
</blockquote></details>

this assumption is also not valid in the case of the "only-write" workload when we have several writes that might use different areas of remote memory. 
@janekmi  - we have to consider the librpma API extension to support mode when rpma_flush will behave exactly like it is implemented in librpmem - flush everything related to particular MR, flush everything related to the particular connection (QP)
Such modes will be introduced by IETF spec.


<!-- Sent from Reviewable.io -->

2020-11-02 10:55 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-03 12:26 UTC, grom72 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43#-:-MLD3a7X6vORXW_sIfCW:bdycpsm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-03 12:26 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-05 15:06 UTC, ldorau reviewed
@osalyk please rebase, #38 has been merged

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43#-:-MLNwLe_D7K7Op2toL4A:b-h5j2g)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-06 08:39 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma.c, line 582 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRg3a_-unt-PtTakMl:-MLRg3a_-unt-PtTakMm:bf196q6) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L582)):*
> ```
> find last
> ```

find THE last
___
*[engines/librpma.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRgmGL36zhUx41VPhj:-MLRgmGL36zhUx41VPhk:binpb5) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L583)):*
> ```
> cd->io_u_queued_nr != 0
> ```

`cd->io_u_queued_nr > 0`
___
*[engines/librpma.c, line 597 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRhJxb0GE0S009RfnL:-MLRhJxb0GE0S009RfnM:b2y2vrt) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L597)):*
> ```
> if (last_read == cd->io_u_queued_nr - 1)
> ```

`if (i == last_read)`


<!-- Sent from Reviewable.io -->

2020-11-06 08:46 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRiQ5MEVt6U1oZv27O:-MLRiQ5MEVt6U1oZv27P:b-en71mt) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L583)):*
> ```
> if (td_read(td) && cd->io_u_queued_nr != 0) {
> ```

Maybe I do not understand something, but shouldn't it be rather ?

```
if ((td_random(td) || td_rw(td)) && cd->io_u_queued_nr > 0) {
```


<!-- Sent from Reviewable.io -->

2020-11-06 09:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma.c, line 588 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRp5jRDcSp4BjPEesr:-MLRp5jS8KIZVM8PJvXb:b-epiw5d) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L588)):*
> ```
> } while (!last_read || cd->io_us_queued[last_read]->ddir == DDIR_READ);
> ```

As far as I understand, this condition is wrong - it should be reverted:

```
} while (last_read > 0 && cd->io_us_queued[last_read]->ddir != DDIR_READ);
```


<!-- Sent from Reviewable.io -->

2020-11-06 09:17 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 589 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRplPS35qjbn2mif-_:-MLRplPS35qjbn2mif-a:b96kyqe) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L589)):*
The following lines:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		last_read = cd->io_u_queued_nr - 1;
> 		if (cd->io_us_queued[last_read]->ddir != DDIR_READ) {
> 			do {
> 				last_read --;
> 			} while (!last_read || cd->io_us_queued[last_read]->ddir == DDIR_READ);
> 		}
> ```
</details>


can be replaced with just:

```
		last_read = cd->io_u_queued_nr;
		while (last_read > 0 && cd->io_us_queued[--last_read]->ddir != DDIR_READ)
			;
```


<!-- Sent from Reviewable.io -->

2020-11-06 11:11 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 582 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRg3a_-unt-PtTakMl:-MLS8VDO7tmtB9iZ_M4i:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L582)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> find last
> ```

find THE last
</blockquote></details>

Done.
___
*[engines/librpma.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRiQ5MEVt6U1oZv27O:-MLS-0cP5U-JPWkKtKuP:b7jvmtv) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L583)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if (td_read(td) && cd->io_u_queued_nr != 0) {
> ```

Maybe I do not understand something, but shouldn't it be rather ?

```
if ((td_random(td) || td_rw(td)) && cd->io_u_queued_nr > 0) {
```
</blockquote></details>

when setting the flags = RPMA_F_COMPLETION_ALWAYS;
I use the last_read variable
___
*[engines/librpma.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRgmGL36zhUx41VPhj:-MLS8_TR9BKRFss7lktZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L583)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> cd->io_u_queued_nr != 0
> ```

`cd->io_u_queued_nr > 0`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 588 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRp5jRDcSp4BjPEesr:-MLS-gRi1yY9kj7_bYEw:b783fwm) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L588)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> } while (!last_read || cd->io_us_queued[last_read]->ddir == DDIR_READ);
> ```

As far as I understand, this condition is wrong - it should be reverted:

```
} while (last_read > 0 && cd->io_us_queued[last_read]->ddir != DDIR_READ);
```
</blockquote></details>

Checking last_read will be faster.
The second condition is ok
___
*[engines/librpma.c, line 589 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRplPS35qjbn2mif-_:-MLS9NdE50B_jx_vu_KR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L589)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The following lines:

> ```
> 		last_read = cd->io_u_queued_nr - 1;
> 		if (cd->io_us_queued[last_read]->ddir != DDIR_READ) {
> 			do {
> 				last_read --;
> 			} while (!last_read || cd->io_us_queued[last_read]->ddir == DDIR_READ);
> 		}
> ```

can be replaced with just:

```
		last_read = cd->io_u_queued_nr;
		while (last_read > 0 && cd->io_us_queued[--last_read]->ddir != DDIR_READ)
			;
```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 597 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRhJxb0GE0S009RfnL:-MLS9TftB3oqm97l6aKh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L597)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if (last_read == cd->io_u_queued_nr - 1)
> ```

`if (i == last_read)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-06 11:18 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRiQ5MEVt6U1oZv27O:-MLSGOARC1jV54T1_IGw:b6nlpt7) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L583)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

when setting the flags = RPMA_F_COMPLETION_ALWAYS;
I use the last_read variable
</blockquote></details>

You didn't understand me. I was asking whether `td_read(td)` should be replaced with `((td_random(td) || td_rw(td))`.


<!-- Sent from Reviewable.io -->

2020-11-06 11:24 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/43#-MLRiQ5MEVt6U1oZv27O:-MLSHTEp8GMHeTTOXAvo:bj7twof) ([raw file](https://github.com/pmem/fio/blob/9de2d015f379883fb6b2603d5a48cd07d1e0e121/engines/librpma.c#L583)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You didn't understand me. I was asking whether `td_read(td)` should be replaced with `((td_random(td) || td_rw(td))`.
</blockquote></details>

That's not the answer to this question, sorry ;)
td_read(td) checks if TD_DDIR_READ is possible. It is ok


<!-- Sent from Reviewable.io -->

2020-11-06 11:26 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/43#-MLSIdR11nnzPethPqDo:-MLSIdR11nnzPethPqDp:b-uqcgg7) (no related file):*
Please fix `readwrite=[read/write/randread/randwrite/readwrite/rw]` in examples/librpma-client.fio

---


<!-- Sent from Reviewable.io -->

2020-11-06 11:27 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/43#-MLSIdR11nnzPethPqDo:-MLSIq3z6i2Dd2DzgG7N:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix `readwrite=[read/write/randread/randwrite/readwrite/rw]` in examples/librpma-client.fio
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-11-06 11:27 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-09 07:11 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-12-28 11:15 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 570 at r1](https://reviewable.io/reviews/pmem/fio/43#-MKnTHSJAgeIDCX5hzlB:-MPd-BSV0tB5G3IUDndi:b-hxphng) ([raw file](https://github.com/pmem/fio/blob/56ed88be0caa861bc4276b020eead18efc4f999f/engines/librpma.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

this assumption is also not valid in the case of the "only-write" workload when we have several writes that might use different areas of remote memory. 
@janekmi  - we have to consider the librpma API extension to support mode when rpma_flush will behave exactly like it is implemented in librpmem - flush everything related to particular MR, flush everything related to the particular connection (QP)
Such modes will be introduced by IETF spec.
</blockquote></details>

@grom72 can you submit a feature request for this? Maybe add to the roadmap if we know when IETF spec will be ready?

Although, using the `rpma_flush()` as it is defined now the only optimization we can do is to flush a sequence of sequential `rpma_write()`s. In case of random `rpma_write()` sequence, we have to flush after each `rpma_write()`.
___
*[engines/librpma.c, line 128 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcpoET3UJZsjiu3F7L:-MPcpoET3UJZsjiu3F7M:b-6knv1c) ([raw file](https://github.com/pmem/fio/blob/a464a198f37d183700202991e47e237a7415791c/engines/librpma.c#L128)):*
> ```C
> 
> 	/* XXX not supported readwrite = rw/randwrite/randrw */
> 	if (td_random(td) || td_rw(td)) {
> ```

I think we need here `td_trim()`
___
*[engines/librpma.c, line 170 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPctjgbA4PPhHU0VeXh:-MPctjgbA4PPhHU0VeXi:b-1mo6yq) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L170)):*
> ```C
> 
> 	/* the send queue has to be big enough to accommodate all io_u's */
> 	if (td_random(td) || td_rw(td)) {
> ```

```c
/*
 * sq_size = max(rand_read_sq_size, rand_write_sq_size)
 * where rand_read_sq_size < rand_write_sq_size because read does not require flush afterwards
 * rand_write_sq_size = N * (WRITE + FLUSH)
 *
 * Note: rw is no different from random write since having interleaved reads with writes
 * in extreme forces you to flush as often as when the writes are random.
 */
```
___
*[engines/librpma.c, line 171 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcvDZc5s8Uc4dg3E6b:-MPcvDZc5s8Uc4dg3E6c:b-sayjs4) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L171)):*
> ```C
> 	/* the send queue has to be big enough to accommodate all io_u's */
> 	if (td_random(td) || td_rw(td)) {
> 		sq_size = 2 * td->o.iodepth; /* N x (WRITE + FLUSH) */
> ```

Having the comment above you do not need the comment here.
___
*[engines/librpma.c, line 172 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcqRct2FiJ91NzhaG-:-MPcqRct2FiJ91NzhaG0:b-8z869m) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L172)):*
> ```C
> 	if (td_random(td) || td_rw(td)) {
> 		sq_size = 2 * td->o.iodepth; /* N x (WRITE + FLUSH) */
> 	} else if (td_write(td)) {
> ```

`/* sequential TD_DDIR_WRITE only */`
___
*[engines/librpma.c, line 185 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcqH2f99iL8Ehh8SPi:-MPcqH2f99iL8Ehh8SPj:bvzzmsg) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L185)):*
> ```C
> 				td->o.iodepth / td->o.iodepth_batch + 1;
> 		}
> 	} else {
> ```

`/* TD_DDIR_READ only */`
___
*[engines/librpma.c, line 594 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPczCgW9uCX8HEaNZVx:-MPczCgX47oMNOtsE_qP:bnwyb) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L594)):*
> ```C
> 
> 		if (io_u->ddir == DDIR_READ) {
> 			if (i == last_read)
> ```

I know we have to a little bit about it and previously I have recommended the way you have already implemented but now... now I think we should go with something like this:

```c
if (i + 1 == cd->io_u_queued_nr || cd->io_us_queued[i + 1]->ddir == DDIR_WRITE)
	flags = RPMA_F_COMPLETION_ALWAYS;
```

to make the mixed-mode as similar to the plain read mode.
___
*[engines/librpma.c, line 601 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcxWPh0RzDhCw1bi_n:-MPcxWPh0RzDhCw1bi_o:b-qlyalo) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L601)):*
> ```C
> 		} else if (io_u->ddir == DDIR_WRITE) {
> 			/* post an RDMA write operation */
> 			if (td_random(td) || (td_random(td) && td_write(td))) {
> ```

I think what you mean here is:

```c
if (td_random(td) || td_rw(td)) {
```
___
*[engines/librpma.c, line 606 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPd1zL35BUuU7MIZjSK:-MPd1zL35BUuU7MIZjSL:b68hkt0) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L606)):*
> ```C
> 					return -1;
> 				ret = rpma_flush(cd->conn, cd->server_mr,
> 					io_u->offset, io_u->xfer_buflen,
> ```

`cd->ws_offset + io_u->offset`
___
*[engines/librpma.c, line 620 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPd0lkm7oDm4RXI02B3:-MPd0lkm7oDm4RXI02B4:b-uf4tuq) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L620)):*
> ```C
> 				flush_len += io_u->xfer_buflen;
> 
> 				if ((i < cd->io_u_queued_nr - 1) && (cd->io_us_queued[i + 1]->ddir == DDIR_WRITE))
> ```

In my opinion, when you are using `i + 1` in the second condition it is more natural to use the same expression in the first condition e.g. `i + 1 < cd->io_u_queued_nr`.
___
*[engines/librpma.c, line 623 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPd1hgUBTlwFoUfYn4I:-MPd1hgUBTlwFoUfYn4J:b-3owlka) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L623)):*
> ```C
> 					continue;
> 
> 				ret = rpma_flush(cd->conn, cd->server_mr, io_u->offset,
> ```

1. You have to cache the offset of the first io_u in the sequence you are flushing and use it here.
2. `cd->ws_offset + flush_offset`


<!-- Sent from Reviewable.io -->

2020-12-29 13:23 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 128 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcpoET3UJZsjiu3F7L:-MPiYAqe72dvyMhpIa6B:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a464a198f37d183700202991e47e237a7415791c/engines/librpma.c#L128)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we need here `td_trim()`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 170 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPctjgbA4PPhHU0VeXh:-MPiYd3x1iEh19e2qise:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L170)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/*
 * sq_size = max(rand_read_sq_size, rand_write_sq_size)
 * where rand_read_sq_size < rand_write_sq_size because read does not require flush afterwards
 * rand_write_sq_size = N * (WRITE + FLUSH)
 *
 * Note: rw is no different from random write since having interleaved reads with writes
 * in extreme forces you to flush as often as when the writes are random.
 */
```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 171 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcvDZc5s8Uc4dg3E6b:-MPiYfr8EQGos7z_9PcN:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L171)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Having the comment above you do not need the comment here.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 172 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcqRct2FiJ91NzhaG-:-MPiYnlyECxVQZ6VLqnt:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L172)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* sequential TD_DDIR_WRITE only */`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 185 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcqH2f99iL8Ehh8SPi:-MPiYrYa-axIrICq8lTq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L185)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* TD_DDIR_READ only */`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 594 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPczCgW9uCX8HEaNZVx:-MPiZiZP5cwMk1ipG-MU:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L594)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know we have to a little bit about it and previously I have recommended the way you have already implemented but now... now I think we should go with something like this:

```c
if (i + 1 == cd->io_u_queued_nr || cd->io_us_queued[i + 1]->ddir == DDIR_WRITE)
	flags = RPMA_F_COMPLETION_ALWAYS;
```

to make the mixed-mode as similar to the plain read mode.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 601 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPcxWPh0RzDhCw1bi_n:-MPiZpa8CzTzoCp6WopO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L601)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think what you mean here is:

```c
if (td_random(td) || td_rw(td)) {
```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 606 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPd1zL35BUuU7MIZjSK:-MPiZyMjEWaLa0m2QAaI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L606)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cd->ws_offset + io_u->offset`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 620 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPd0lkm7oDm4RXI02B3:-MPi_FZm7mF4SbAa7uN4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L620)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In my opinion, when you are using `i + 1` in the second condition it is more natural to use the same expression in the first condition e.g. `i + 1 < cd->io_u_queued_nr`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-29 13:36 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-12-29 16:27 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 623 at r6](https://reviewable.io/reviews/pmem/fio/43#-MPd1hgUBTlwFoUfYn4I:-MPjHBdC-AuIyZFBE182:b32v57) ([raw file](https://github.com/pmem/fio/blob/7db26aaba5f102d1df354ca41c56c59ad95164ba/engines/librpma.c#L623)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. You have to cache the offset of the first io_u in the sequence you are flushing and use it here.
2. `cd->ws_offset + flush_offset`
</blockquote></details>

+1
___
*[engines/librpma.c, line 612 at r7](https://reviewable.io/reviews/pmem/fio/43#-MPjGt2UAq4epI6ivOwQ:-MPjGt2UAq4epI6ivOwR:b-mhqaq6) ([raw file](https://github.com/pmem/fio/blob/fb851110f3d8b5588f75dd5521b41dad0bf5da5b/engines/librpma.c#L612)):*
> ```
> 				ret = client_io_write(td, io_u, RPMA_F_COMPLETION_ON_ERROR);
> 				if (ret)
> 					return -1;
> ```
put this before if() { ..

and add to flush_len
```
flush_len += io_u->xfer_buflen;
```

if the first writ in a sequence memorize its io_u-> offset
```
if (flush_offset == -1)
flush_offsett = io_u->offset
```
if( td_random(td)  || (i + 1 >= cd->io_u_queued_nr) || (cd->io_us_queued[i + 1]->ddir != DDIR_WRITE) ) {
				ret = rpma_flush(cd->conn, cd->server_mr, flush_offsett ,
					flush_len, cd->flush_type, RPMA_F_COMPLETION_ALWAYS,
					(void *)(uintptr_t)io_u->index);
				if (ret) {
					rpma_td_verror(td, ret, "rpma_flush");
					return -1;
				}
flush_len = 0;
flush_offsett  = -1
}

/* and remove the code below */


<!-- Sent from Reviewable.io -->

2020-12-29 16:28 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-12-29 22:15 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 612 at r7](https://reviewable.io/reviews/pmem/fio/43#-MPjGt2UAq4epI6ivOwQ:-MPkZJ1-7CmPPglZdo36:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fb851110f3d8b5588f75dd5521b41dad0bf5da5b/engines/librpma.c#L612)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 				ret = client_io_write(td, io_u, RPMA_F_COMPLETION_ON_ERROR);
> 				if (ret)
> 					return -1;
> ```
put this before if() { ..

and add to flush_len
```
flush_len += io_u->xfer_buflen;
```

if the first writ in a sequence memorize its io_u-> offset
```
if (flush_offset == -1)
flush_offsett = io_u->offset
```
if( td_random(td)  || (i + 1 >= cd->io_u_queued_nr) || (cd->io_us_queued[i + 1]->ddir != DDIR_WRITE) ) {
				ret = rpma_flush(cd->conn, cd->server_mr, flush_offsett ,
					flush_len, cd->flush_type, RPMA_F_COMPLETION_ALWAYS,
					(void *)(uintptr_t)io_u->index);
				if (ret) {
					rpma_td_verror(td, ret, "rpma_flush");
					return -1;
				}
flush_len = 0;
flush_offsett  = -1
}

/* and remove the code below */
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-30 09:07 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43#-:-MPmtfwlAFcgns2reI4K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-12-30 09:56 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-12-30 09:56 UTC, merged