Gpspm client commit
pmem/fio pull request #65
Opened 2020-11-18 08:18 UTC by osalyk

- [ ] #63

2020-11-18 11:29 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/65#-MMPxSvSABRz46HgxdWF:-MMPxSvSABRz46HgxdWG:bylhhiq) (no related file):*
This PR does not really depend on #63, does it?

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/65#-MMPxeVtBJTWrI4pB2qy:-MMPxeVtBJTWrI4pB2qz:b-kuevnb) (no related file):*
It sounds really bad when the commit message starts with "implement". It is kinda default.
Maybe go with something like: `rpma: gpspm client commit`?

---
___
*[engines/librpma_gpspm.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ1B7h3lq69ioacMuf:-MMQ1B7h3lq69ioacMug:bmt04i3) ([raw file](https://github.com/pmem/fio/blob/4786645dadf284d138c943ce408ccd7e0be30b70/engines/librpma_gpspm.c#L30)):*
> ```C
> 	td_vmsg((td), (err), rpma_err_2str(err), (func))
> 
> #define IO_U_BUF_LEN (1024)
> ```

I think it will be easier to follow this way:
```c
#define MAX_MSG_SIZE (512)
#define IO_U_BUF_LEN (2 * MAX_MSG_SIZE)
#define IO_U_BUF_OFF(td, i) \
    (((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)

#define SEND_OFFSET (0)
#define RECV_OFFSET (SEND_OFFSET + MAX_MSG_SIZE)
```
___
*[engines/librpma_gpspm.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ0eaN7IZpfEX23Fl9:-MMQ0eaN7IZpfEX23FlA:bp6s2ws) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L100)):*
> ```C
> 	struct rpma_mr_local *orig_mr;
> 
> 	/* memory for sending and reciving buffered */
> ```

@osalyk `receiving`
___
*[engines/librpma_gpspm.c, line 297 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ-jNCExF38PIga1YN:-MMQ-jNCExF38PIga1YO:b-gz9wyw) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L297)):*
> ```C
> 
> 	if ((ret = posix_memalign((void **)&cd->io_us_msgs,
> 			page_mask, io_us_msgs_size))) {
> ```

I know it is an unrelated comment but... page_mask is not a `page_size`.
@osalyk can you fix it in a separate PR?
___
*[engines/librpma_gpspm.c, line 449 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ1R-GBmcQSdLa8wtx:-MMQ1R-GBmcQSdLa8wty:b-5b2y4f) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L449)):*
> ```C
> 		struct io_u *io_u = cd->io_us_queued[i];
> 
> 		max_msg_size = io_u->xfer_buflen / 2;
> ```

This should be replaced with the use of `MAX_MSG_SIZE`.
Please see the comment at the beginning of this file.
___
*[engines/librpma_gpspm.c, line 452 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ4FfODWFbqGOkhwxw:-MMQ4FfODWFbqGOkhwxx:b-e5i5l4) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L452)):*
> ```C
> 		send_offset = 0;
> 		recv_offset = max_msg_size;
> 		send_ptr = (char *)io_u->xfer_buf + send_offset;
> ```

```c
io_u_buf_off = IO_U_BUF_OFF(td, i);
send_offset = io_u_buf_off + SEND_OFFSET;
recv_offset = io_u_buf_off + RECV_OFFSET;
send_ptr = cd->io_us_msgs + send_offset;
```
___
*[engines/librpma_gpspm.c, line 460 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ62t9Bf1YGW9HaD35:-MMQ62t9Bf1YGW9HaD36:be3e0wp) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L460)):*
> ```C
> 			/* post an RDMA write operation */
> 			size_t dst_offset = (char *)(io_u->xfer_buf) - td->orig_buffer;
> 			size_t src_offset = io_u->offset;
> ```

You have messed something up here. Please see `client_io_write()` in the previous engine.
___
*[engines/librpma_gpspm.c, line 480 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ4s9NDPCl5fFHc6ev:-MMQ4s9NDPCl5fFHc6ew:bprl0xa) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L480)):*
> ```C
> 				rpma_td_verror(td, ret, "rpma_read");
> 				return -1;
> 			}
> ```

A newline is missing.
___
*[engines/librpma_gpspm.c, line 483 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ57orE9gnKwlXeJCc:-MMQ57orE9gnKwlXeJCd:b-ewo804) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L483)):*
> ```C
> 			/* prepare a flush message and pack it to a send buffer */
> 			flush_req.offset = send_offset;
> 			flush_req.length = 0;
> ```

```c
flush_req.offset = the_first_io_u->xfer_buf; /* XXX on the server side you need add here a virtual base address of the registration */
flush_req.length = sum_of_all_io_us_length;
```
___
*[engines/librpma_gpspm.c, line 498 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ4V_SCZ_ksWLVkSJy:-MMQ4V_SCZ_ksWLVkSJz:bhgrd34) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L498)):*
> ```C
> 			if ((ret = rpma_send(cd->conn, cd->msg_mr, send_offset, flush_req_size,
> 				RPMA_F_COMPLETION_ON_ERROR, NULL)))
> 				rpma_td_verror(td, ret, "rpma_send");
> ```

All of the recv/send things should be done only for the last message in the batch.
At least till we do not implement random offsets here.
___
*[engines/librpma_gpspm.c, line 531 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ6Nrh484JbCMjac7v:-MMQ6Nrh484JbCMjac7w:b-ce4lnu) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L531)):*
> ```C
> 	cd->io_u_queued_nr = 0;
> ```

You can take a newline from here.
___
*[engines/librpma_gpspm.c, line 533 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ6L9H73LVtQEpC7No:-MMQ6L9H73LVtQEpC7Np:b6wuto9) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L533)):*
> ```C
> 
> 	return 0;
> }
> ```

Missing newline.


<!-- Sent from Reviewable.io -->

2020-11-18 11:37 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 15 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 476 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7xGT4UqbqXBXtHVl:-MMQ7xGU8l5SLqsn8EPX:b4dqwkd) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L476)):*
> ```C
> 					cd->msg_mr, recv_offset,
> 					max_msg_size,
> 					(void *)(uintptr_t)io_u->index);
> ```

Passing this here does not make much sense. Please see my comment to `client_getevent_process()`.
___
*[engines/librpma_gpspm.c, line 564 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7izRDks-vbLf1z94:-MMQ7MBv8frLsw28_BK9:bmj22d9) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L564)):*
> ```C
> 
> 	/* look for an io_u being completed */
> 	memcpy(&io_u_index, &cmpl.op_context, sizeof(unsigned int));
> ```

You have to unpack the received buffer and use the op_context from `struct _GPSPMFlushResponse`.


<!-- Sent from Reviewable.io -->

2020-11-18 16:13 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/65#-MMPxSvSABRz46HgxdWF:-MMQL-Z7EulJVLkRlmxX:b2nhll9) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This PR does not really depend on #63, does it?
</blockquote></details>

Ok.

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/65#-MMPxeVtBJTWrI4pB2qy:-MMR7PgV2DdfCuvvMhsj:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It sounds really bad when the commit message starts with "implement". It is kinda default.
Maybe go with something like: `rpma: gpspm client commit`?
</blockquote></details>

Done.

---
___
*[engines/librpma_gpspm.c, line 30 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ1B7h3lq69ioacMuf:-MMQjhs0-OBPaQlYWe_o:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4786645dadf284d138c943ce408ccd7e0be30b70/engines/librpma_gpspm.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be easier to follow this way:
```c
#define MAX_MSG_SIZE (512)
#define IO_U_BUF_LEN (2 * MAX_MSG_SIZE)
#define IO_U_BUF_OFF(td, i) \
    (((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)

#define SEND_OFFSET (0)
#define RECV_OFFSET (SEND_OFFSET + MAX_MSG_SIZE)
```
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 449 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ1R-GBmcQSdLa8wtx:-MMQk1ki57QnTwV80so7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L449)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This should be replaced with the use of `MAX_MSG_SIZE`.
Please see the comment at the beginning of this file.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 452 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ4FfODWFbqGOkhwxw:-MMQk2pG-rgQTfs0orPx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L452)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
io_u_buf_off = IO_U_BUF_OFF(td, i);
send_offset = io_u_buf_off + SEND_OFFSET;
recv_offset = io_u_buf_off + RECV_OFFSET;
send_ptr = cd->io_us_msgs + send_offset;
```
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 460 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ62t9Bf1YGW9HaD35:-MMQxrSr6pqxZUVdleFp:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L460)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have messed something up here. Please see `client_io_write()` in the previous engine.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 476 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7xGT4UqbqXBXtHVl:-MMR6zrA5IdnTFN-nE9Z:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L476)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Passing this here does not make much sense. Please see my comment to `client_getevent_process()`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 480 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ4s9NDPCl5fFHc6ev:-MMQn9LFCZgo2ODaTtrl:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L480)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A newline is missing.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 483 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ57orE9gnKwlXeJCc:-MMR7-zK9PqVzN4OWCMO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L483)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
flush_req.offset = the_first_io_u->xfer_buf; /* XXX on the server side you need add here a virtual base address of the registration */
flush_req.length = sum_of_all_io_us_length;
```
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 498 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ4V_SCZ_ksWLVkSJy:-MMR09zp8LBW3aXwCfZ4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L498)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All of the recv/send things should be done only for the last message in the batch.
At least till we do not implement random offsets here.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 531 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ6Nrh484JbCMjac7v:-MMQx8YV8GI_rzFuK8AB:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L531)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can take a newline from here.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 533 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ6L9H73LVtQEpC7No:-MMQxD-53HEIuD4gqc_c:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L533)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing newline.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 564 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7izRDks-vbLf1z94:-MMR6yNe--oN3NXV9_XQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L564)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to unpack the received buffer and use the op_context from `struct _GPSPMFlushResponse`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-18 20:59 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 33 at r2](https://reviewable.io/reviews/pmem/fio/65#-MMS804a451e1HiwC5vh:-MMS804a451e1HiwC5vi:b-2v16pd) ([raw file](https://github.com/pmem/fio/blob/fb9e3aa3d88d92971431310c8c7bbcaa8640cb0a/engines/librpma_gpspm.c#L33)):*
> ```
>(((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch * IO_U_BUF_LEN)
> ```

It should be:

```
((((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)
```
or:
```
(IO_U_BUF_LEN * (((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch))
```


<!-- Sent from Reviewable.io -->

2020-11-19 08:43 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 33 at r2](https://reviewable.io/reviews/pmem/fio/65#-MMS804a451e1HiwC5vh:-MMUemly-XEKLFIZaQI_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fb9e3aa3d88d92971431310c8c7bbcaa8640cb0a/engines/librpma_gpspm.c#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>(((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch * IO_U_BUF_LEN)
> ```

It should be:

```
((((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)
```
or:
```
(IO_U_BUF_LEN * (((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch))
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-19 08:45 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 32 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMUf933-7aAGuBgf2PD:-MMUf934BR2A6u8uNWOi:bgn58eu) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L32)):*
> ```
> IO_U_BUF_OFF
> ```

Please rename it to `IO_U_BUF_OFF_CLIENT` and move it below `/* client side implementation */`, because it is client-specific. The srever has its own `IO_U_BUF_OFF_SERVER`.


<!-- Sent from Reviewable.io -->

2020-11-19 14:45 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 476 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7xGT4UqbqXBXtHVl:-MMVwf5-9SUG3yGev2oi:br7sr4m) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L476)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet
___
*[engines/librpma_gpspm.c, line 461 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMVwQxmAKN5TVxLY5Zg:-MMVwQxmAKN5TVxLY5Zh:bdrnk2e) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L461)):*
> ```
>  (char *)io_u->xfer_buf 
> ```

cd->io_us_msgs
___
*[engines/librpma_gpspm.c, line 462 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMVwTQH2LQ95t2ySa-K:-MMVwTQH2LQ95t2ySa-L:b-wq2mwm) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L462)):*
> ```
>  (char *)io_u->xfer_buf
> ```

cd->io_us_msgs
___
*[engines/librpma_gpspm.c, line 583 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMVwxv01jOSMtcKq5cp:-MMVwxv01jOSMtcKq5cq:b-4cybgy) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L583)):*
> ```
> 	/* unpack a response from the received buffer */
> 	flush_resp = gpspm_flush_response__unpack(NULL, cmpl.byte_len,
> 			cd->recv_ptr);
> ```

You have mixed handling two different completions here.
The first one you receive is a completion of the last `rpma_read/rpma_write` and this one should be handled like in the old engine.
`gpspm_flush_response__unpack()` should be called only on the second one - of `rpma_send()`


<!-- Sent from Reviewable.io -->

2020-11-20 05:50 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 16 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 583 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMVwxv01jOSMtcKq5cp:-MMZBMLvBwKVvj46E_ie:b-2rzl9p) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L583)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* unpack a response from the received buffer */
> 	flush_resp = gpspm_flush_response__unpack(NULL, cmpl.byte_len,
> 			cd->recv_ptr);
> ```

You have mixed handling two different completions here.
The first one you receive is a completion of the last `rpma_read/rpma_write` and this one should be handled like in the old engine.
`gpspm_flush_response__unpack()` should be called only on the second one - of `rpma_send()`
</blockquote></details>

Stop, I was wrong. This completion handling part is OK, only the completion of `rpma_write()` is not needed, so just `rpma_write()` should be corrected.


<!-- Sent from Reviewable.io -->

2020-11-20 06:01 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 23 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 476 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7xGT4UqbqXBXtHVl:-MMZDrr1EiLUDiyT6QlN:b-mos5pi) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L476)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet
</blockquote></details>

`recv_ptr` should be passed here instead of `io_u->index`
___
*[engines/librpma_gpspm.c, line 112 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZCF9W268fir4llxyz:-MMZCF9W268fir4llxz-:b-lgj9t4) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L112)):*
> ```C
> 	struct rpma_mr_local *msg_mr;
> 
> 	void *recv_ptr;
> ```

Not needed, it should be passed via the completion context, please move this declaration to `client_commit()`
___
*[engines/librpma_gpspm.c, line 439 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZCjVj52u9EiRdG48O:-MMZCjVj52u9EiRdG48P:b-ip90cb) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L439)):*
> ```C
> {
> 	struct client_data *cd = td->io_ops_data;
> 	int flags = RPMA_F_COMPLETION_ON_ERROR;
> ```

Not needed, see below.
___
*[engines/librpma_gpspm.c, line 445 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZCqnt4awfhj996vVf:-MMZCqnt4awfhj996vVg:b-cc0m84) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L445)):*
> ```C
> 	size_t send_offset;
> 	size_t recv_offset;
> 	void *send_ptr;
> ```

Add `void *recv_ptr;` here
___
*[engines/librpma_gpspm.c, line 462 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZD8NpD9CE4EhEpyXC:-MMZD8NpD9CE4EhEpyXD:b-smwnaz) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L462)):*
> ```
> cd->recv_ptr 
> ```

just `recv_ptr`
___
*[engines/librpma_gpspm.c, line 465 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZDI1n3OYQ0EdlnlG6:-MMZDI1oEyX8QiVF9-N3:byjsn2z) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L465)):*
> ```
> 		if (i == cd->io_u_queued_nr - 1)
> 			flags = RPMA_F_COMPLETION_ALWAYS;
> ```

Not needed, please remove, all `rpma_write()s` will be sent with `RPMA_F_COMPLETION_ON_ERROR`. We will wait only for completion of `rpma_send()`.
___
*[engines/librpma_gpspm.c, line 480 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZDYoZAC5wpeJyjwjz:-MMZDYoZAC5wpeJyjwk-:b-fe9tct) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L480)):*
> ```
> flags
> ```

`RPMA_F_COMPLETION_ON_ERROR`
___
*[engines/librpma_gpspm.c, line 583 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZE8JHEq3uoO8eqIgz:-MMZE8JHEq3uoO8eqIh-:b-q3t1u2) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L583)):*
> ```
> cd->recv_ptr
> ```

`cmpl.op_context` instead of `cd->recv_ptr` here.  `cmpl.op_context` contains `recv_ptr`.


<!-- Sent from Reviewable.io -->

2020-11-20 07:01 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 24 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 585 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZSKFD9lT2sEOvsyTP:-MMZSKFD9lT2sEOvsyTQ:b213de8) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L585)):*
> ```C
> 			cd->recv_ptr);
> 	if (flush_resp == NULL) {
> 		fprintf(stderr, "Cannot unpack the flush response buffer\n");
> ```

`log_err()`


<!-- Sent from Reviewable.io -->

2020-11-20 12:29 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 32 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMUf933-7aAGuBgf2PD:-MM_bGUQ2KWdSZUgu0A1:b-6i84t0) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> IO_U_BUF_OFF
> ```

Please rename it to `IO_U_BUF_OFF_CLIENT` and move it below `/* client side implementation */`, because it is client-specific. The srever has its own `IO_U_BUF_OFF_SERVER`.
</blockquote></details>

It will become kinda obvious when #64 will be merged. ;-)


<!-- Sent from Reviewable.io -->

2020-11-20 13:22 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 32 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMUf933-7aAGuBgf2PD:-MM_oWfW600ToYl4g0f7:b-t67mzs) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It will become kinda obvious when #64 will be merged. ;-)
</blockquote></details>

Yes :-)


<!-- Sent from Reviewable.io -->

2020-11-20 13:56 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 476 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ7xGT4UqbqXBXtHVl:-MM_idQH03DgFkdc9kyz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L476)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`recv_ptr` should be passed here instead of `io_u->index`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 32 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMUf933-7aAGuBgf2PD:-MM_wJ12BacjzvMMaJkd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes :-)
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 112 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZCF9W268fir4llxyz:-MM_i1nk8FZGkKCJ3I6y:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed, it should be passed via the completion context, please move this declaration to `client_commit()`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 439 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZCjVj52u9EiRdG48O:-MM_i5ZQ9KTjad_eY2e4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L439)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed, see below.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 445 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZCqnt4awfhj996vVf:-MM_i6T4CmswyJuJl1Ls:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L445)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add `void *recv_ptr;` here
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 461 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMVwQxmAKN5TVxLY5Zg:-MMZdfCcBEHJy5R8y-an:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L461)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  (char *)io_u->xfer_buf 
> ```

cd->io_us_msgs
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 462 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMVwTQH2LQ95t2ySa-K:-MMW1GtP685y8wrY9ACq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L462)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  (char *)io_u->xfer_buf
> ```

cd->io_us_msgs
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 462 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZD8NpD9CE4EhEpyXC:-MMZdyI13fmO1ugIbdig:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L462)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> cd->recv_ptr 
> ```

just `recv_ptr`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 465 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZDI1n3OYQ0EdlnlG6:-MM_iJJ8AZxG6sqLj6Ih:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L465)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		if (i == cd->io_u_queued_nr - 1)
> 			flags = RPMA_F_COMPLETION_ALWAYS;
> ```

Not needed, please remove, all `rpma_write()s` will be sent with `RPMA_F_COMPLETION_ON_ERROR`. We will wait only for completion of `rpma_send()`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 480 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZDYoZAC5wpeJyjwjz:-MM_iLgz8pVyILLc37Rs:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L480)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> flags
> ```

`RPMA_F_COMPLETION_ON_ERROR`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 583 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZE8JHEq3uoO8eqIgz:-MM_iyLZ8dehD9h9rtYC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L583)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> cd->recv_ptr
> ```

`cmpl.op_context` instead of `cd->recv_ptr` here.  `cmpl.op_context` contains `recv_ptr`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 585 at r3](https://reviewable.io/reviews/pmem/fio/65#-MMZSKFD9lT2sEOvsyTP:-MM_jK6lB82wAUpB0zIl:b-896fix) ([raw file](https://github.com/pmem/fio/blob/06b460b07d90ef1076af70e94c7c6c3224f01338/engines/librpma_gpspm.c#L585)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`log_err()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-20 15:13 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-21 00:10 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 297 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ-jNCExF38PIga1YN:-MMc5JgGCDSEhGrGiCtZ:btvg18o) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L297)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know it is an unrelated comment but... page_mask is not a `page_size`.
@osalyk can you fix it in a separate PR?
</blockquote></details>

I don't like that you have fixed it along with this unrelated change. I can turn out my head but please at least mention this change in the commit message.

I at least hope you know why I don't like you doing this. ;-)


<!-- Sent from Reviewable.io -->

2020-11-21 00:32 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 476 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMc9o_Z9czZT5o-y_i9:-MMc9o_Z9czZT5o-y_iA:bem85z7) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L476)):*
> ```C
> 					io_u->xfer_buflen,
> 					RPMA_F_COMPLETION_ON_ERROR,
> 					(void *)(uintptr_t)io_u->index);
> ```

No completion so no user context needed. It won't be used anywhere.
___
*[engines/librpma_gpspm.c, line 484 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcADvZ6vSWDi_jHEld:-MMcADv_EL9P-K2-TXOy:b-2orks1) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L484)):*
> ```C
> 			if (i != cd->io_u_queued_nr - 1)
> 				continue;
> ```

All of these:

```c
		io_u_buf_off = IO_U_BUF_OFF_CLIENT(td, i);
		send_offset = io_u_buf_off + SEND_OFFSET;
		recv_offset = io_u_buf_off + RECV_OFFSET;
		send_ptr = cd->io_us_msgs + send_offset;
		recv_ptr = cd->io_us_msgs + recv_offset;
```

will be needed from here where only a single round (the last one) of this for-loop reaches.
___
*[engines/librpma_gpspm.c, line 484 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcAk646TuNVos9oNfp:-MMcAk646TuNVos9oNfq:b-43bsj6) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L484)):*
> ```C
> 			if (i != cd->io_u_queued_nr - 1)
> 				continue;
> ```

# Research question
FIO calls a `commit()` hook when `iodepth_batch` io_us are queued. Is it possible to have more than one batch queued at this point?
___
*[engines/librpma_gpspm.c, line 491 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcBKnl7XEYQVnxtzhY:-MMcBKnl7XEYQVnxtzhZ:baqzrey) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L491)):*
> ```C
> 					recv_ptr);
> 			if (ret) {
> 				rpma_td_verror(td, ret, "rpma_read");
> ```

`"rpma_recv"`
___
*[engines/librpma_gpspm.c, line 510 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcBlLS4SWrre-yapV5:-MMcBlLS4SWrre-yapV6:b-97u5q3) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L510)):*
> ```C
> 			if ((ret = rpma_send(cd->conn, cd->msg_mr, send_offset, flush_req_size,
> 				RPMA_F_COMPLETION_ON_ERROR, NULL)))
> 				rpma_td_verror(td, ret, "rpma_send");
> ```

I believe in this situation we should also return with error (-1). What do you think?
___
*[engines/librpma_gpspm.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcCfrV436Mii6m6pml:-MMcCfrV436Mii6m6pmm:bqkhmey) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L583)):*
> ```C
> 		return -1;
> 	}
> 	gpspm_flush_response__free_unpacked(flush_resp, NULL);
> ```

You can NOT call `free` before you are attempting to access the data in the `memcpy` below.
You can do this after the `memcpy`.


<!-- Sent from Reviewable.io -->

2020-11-23 08:23 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 297 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ-jNCExF38PIga1YN:-MMoBloeD55hGn6P2rF9:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L297)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like that you have fixed it along with this unrelated change. I can turn out my head but please at least mention this change in the commit message.

I at least hope you know why I don't like you doing this. ;-)
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 476 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMc9o_Z9czZT5o-y_i9:-MMo8-MF4xOvoLHkS-AG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L476)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No completion so no user context needed. It won't be used anywhere.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 484 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcADvZ6vSWDi_jHEld:-MMo8mdv9zOnDR4JSNCv:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L484)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All of these:

```c
		io_u_buf_off = IO_U_BUF_OFF_CLIENT(td, i);
		send_offset = io_u_buf_off + SEND_OFFSET;
		recv_offset = io_u_buf_off + RECV_OFFSET;
		send_ptr = cd->io_us_msgs + send_offset;
		recv_ptr = cd->io_us_msgs + recv_offset;
```

will be needed from here where only a single round (the last one) of this for-loop reaches.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 491 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcBKnl7XEYQVnxtzhY:-MMo8uK24phSYRzCfgYe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L491)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`"rpma_recv"`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 510 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcBlLS4SWrre-yapV5:-MMoAAOBCJ3raArCSDxs:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L510)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe in this situation we should also return with error (-1). What do you think?
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 583 at r4](https://reviewable.io/reviews/pmem/fio/65#-MMcCfrV436Mii6m6pml:-MMoAWfPE0_H4skWODVz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ed5e1cd1cbd8d74fc9634b1a5dc725861b567ea4/engines/librpma_gpspm.c#L583)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can NOT call `free` before you are attempting to access the data in the `memcpy` below.
You can do this after the `memcpy`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-23 10:49 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-11-23 13:46 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 297 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ-jNCExF38PIga1YN:-MMpKUbR9INCX2NG3I0g:b-v6fst7) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L297)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean commit message. Github comments are harder to track via `git`. ;-)


<!-- Sent from Reviewable.io -->

2020-11-23 13:51 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 297 at r1](https://reviewable.io/reviews/pmem/fio/65#-MMQ-jNCExF38PIga1YN:-MMpMSc8Al4Y0RMV7FUA:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad2791659bb12654da295f2cb58984294b52730/engines/librpma_gpspm.c#L297)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I mean commit message. Github comments are harder to track via `git`. ;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-23 13:56 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-11-24 14:01 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-11-24 14:22 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/65#-:-MMucZOUA-K8idXEY6cG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-11-24 14:22 UTC, merged